"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

import importlib.metadata

__title__: str = "ascend-sdk"
__version__: str = "1.8.12"
__openapi_doc_version__: str = "v1:20260710:uat:0c2ab6cbe347"
__gen_version__: str = "2.691.6"
__user_agent__: str = (
    "speakeasy-sdk/python 1.8.12 2.691.6 v1:20260710:uat:0c2ab6cbe347 ascend-sdk"
)

try:
    if __package__ is not None:
        __version__ = importlib.metadata.version(__package__)
except importlib.metadata.PackageNotFoundError:
    pass
