"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

import importlib.metadata

__title__: str = "ascend-sdk"
__version__: str = "1.8.4"
__openapi_doc_version__: str = "v1:20260323:uat:35c1f0c6e7e6"
__gen_version__: str = "2.691.6"
__user_agent__: str = (
    "speakeasy-sdk/python 1.8.4 2.691.6 v1:20260323:uat:35c1f0c6e7e6 ascend-sdk"
)

try:
    if __package__ is not None:
        __version__ = importlib.metadata.version(__package__)
except importlib.metadata.PackageNotFoundError:
    pass
