"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from ascend_sdk import SDK
from ascend_sdk.models import components
import os
from tests.test_client import create_test_http_client


def test_pre_ipo_funding_rounds_pre_ipo_company_funding_rounds_list_pre_ipo_company_funding_rounds():
    test_http_client = create_test_http_client(
        "PreIpoCompanyFundingRounds_ListPreIpoCompanyFundingRounds"
    )

    with SDK(
        server_url=os.getenv("SERVICE_ACCOUNT_CREDS_URL", ""),
        security=components.Security(
            api_key=os.getenv("API_KEY", "value"),
            service_account_creds=components.ServiceAccountCreds(
                private_key=os.getenv("SERVICE_ACCOUNT_CREDS_PRIVATE_KEY", "value"),
                name=os.getenv("SERVICE_ACCOUNT_CREDS_NAME", "value"),
                organization=os.getenv("SERVICE_ACCOUNT_CREDS_ORGANIZATION", "value"),
                type=os.getenv("SERVICE_ACCOUNT_CREDS_TYPE", "value"),
            ),
        ),
        client=test_http_client,
    ) as sdk:
        assert sdk is not None

        res = sdk.pre_ipo_funding_rounds.list_pre_ipo_company_funding_rounds(
            pre_ipo_company_id="a6c63e95-fe8a-4703-a74a-f2a90c0a9c6d",
            page_size=25,
            page_token="",
        )
        assert res.http_meta is not None
        assert res.http_meta.response is not None
        assert res.http_meta.response.status_code == 200


def test_pre_ipo_funding_rounds_pre_ipo_company_funding_rounds_get_pre_ipo_company_funding_round():
    test_http_client = create_test_http_client(
        "PreIpoCompanyFundingRounds_GetPreIpoCompanyFundingRound"
    )

    with SDK(
        server_url=os.getenv("SERVICE_ACCOUNT_CREDS_URL", ""),
        security=components.Security(
            api_key=os.getenv("API_KEY", "value"),
            service_account_creds=components.ServiceAccountCreds(
                private_key=os.getenv("SERVICE_ACCOUNT_CREDS_PRIVATE_KEY", "value"),
                name=os.getenv("SERVICE_ACCOUNT_CREDS_NAME", "value"),
                organization=os.getenv("SERVICE_ACCOUNT_CREDS_ORGANIZATION", "value"),
                type=os.getenv("SERVICE_ACCOUNT_CREDS_TYPE", "value"),
            ),
        ),
        client=test_http_client,
    ) as sdk:
        assert sdk is not None

        res = sdk.pre_ipo_funding_rounds.get_pre_ipo_company_funding_round(
            pre_ipo_company_id="a6c63e95-fe8a-4703-a74a-f2a90c0a9c6d",
            funding_round_id="019c6a2b-6801-7759-9e1d-3d5aaa64bc2a",
        )
        assert res.http_meta is not None
        assert res.http_meta.response is not None
        assert res.http_meta.response.status_code == 200
