"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from ascend_sdk import SDK
import uuid
from ascend_sdk.models import components
from ascend_sdk.models import errors
import os
from tests.test_client import create_test_http_client
from tests.conftest import ALTS_ACCOUNT_ID, ALTS_ORDER_ID


def test_alternative_orders_alternative_orders_create_alternative_order():
    test_http_client = create_test_http_client(
        "AlternativeOrders_CreateAlternativeOrder"
    )

    with SDK(
        server_url=os.getenv("SERVICE_ACCOUNT_CREDS_URL", ""),
        security=components.Security(
            api_key=os.getenv("API_KEY", "value"),
            service_account_creds=components.ServiceAccountCreds(
                private_key=os.getenv("SERVICE_ACCOUNT_CREDS_PRIVATE_KEY", "value"),
                name=os.getenv("SERVICE_ACCOUNT_CREDS_NAME", "value"),
                organization=os.getenv("SERVICE_ACCOUNT_CREDS_ORGANIZATION", "value"),
                type=os.getenv("SERVICE_ACCOUNT_CREDS_TYPE", "value"),
            ),
        ),
        client=test_http_client,
    ) as sdk:
        assert sdk is not None

        res = sdk.alternative_orders.create_alternative_order(
            account_id=ALTS_ACCOUNT_ID,
            alternative_order_create=components.AlternativeOrderCreate(
                client_order_id=str(uuid.uuid4()),
                identifier="13607391",
                identifier_type=components.AlternativeOrderCreateIdentifierType.ASSET_ID,
                notional_value=components.DecimalCreate(
                    value="15000",
                ),
                side=components.AlternativeOrderCreateSide.BUY,
            ),
        )
        assert res.http_meta is not None
        assert res.http_meta.response is not None
        assert res.http_meta.response.status_code == 200


def test_alternative_orders_alternative_orders_list_alternative_orders():
    test_http_client = create_test_http_client(
        "AlternativeOrders_ListAlternativeOrders"
    )

    with SDK(
        server_url=os.getenv("SERVICE_ACCOUNT_CREDS_URL", ""),
        security=components.Security(
            api_key=os.getenv("API_KEY", "value"),
            service_account_creds=components.ServiceAccountCreds(
                private_key=os.getenv("SERVICE_ACCOUNT_CREDS_PRIVATE_KEY", "value"),
                name=os.getenv("SERVICE_ACCOUNT_CREDS_NAME", "value"),
                organization=os.getenv("SERVICE_ACCOUNT_CREDS_ORGANIZATION", "value"),
                type=os.getenv("SERVICE_ACCOUNT_CREDS_TYPE", "value"),
            ),
        ),
        client=test_http_client,
    ) as sdk:
        assert sdk is not None

        res = sdk.alternative_orders.list_alternative_orders(
            account_id=ALTS_ACCOUNT_ID,
            page_size=25,
            page_token="",
            filter_="",
        )
        assert res.http_meta is not None
        assert res.http_meta.response is not None
        assert res.http_meta.response.status_code == 200


def test_alternative_orders_alternative_orders_get_alternative_order():
    test_http_client = create_test_http_client("AlternativeOrders_GetAlternativeOrder")

    with SDK(
        server_url=os.getenv("SERVICE_ACCOUNT_CREDS_URL", ""),
        security=components.Security(
            api_key=os.getenv("API_KEY", "value"),
            service_account_creds=components.ServiceAccountCreds(
                private_key=os.getenv("SERVICE_ACCOUNT_CREDS_PRIVATE_KEY", "value"),
                name=os.getenv("SERVICE_ACCOUNT_CREDS_NAME", "value"),
                organization=os.getenv("SERVICE_ACCOUNT_CREDS_ORGANIZATION", "value"),
                type=os.getenv("SERVICE_ACCOUNT_CREDS_TYPE", "value"),
            ),
        ),
        client=test_http_client,
    ) as sdk:
        assert sdk is not None

        res = sdk.alternative_orders.get_alternative_order(
            account_id=ALTS_ACCOUNT_ID,
            alternative_order_id=ALTS_ORDER_ID,
        )
        assert res.http_meta is not None
        assert res.http_meta.response is not None
        assert res.http_meta.response.status_code == 200


def test_alternative_orders_alternative_orders_retrieve_pending_investor_actions():
    test_http_client = create_test_http_client(
        "AlternativeOrders_RetrievePendingInvestorActions"
    )

    with SDK(
        server_url=os.getenv("SERVICE_ACCOUNT_CREDS_URL", ""),
        security=components.Security(
            api_key=os.getenv("API_KEY", "value"),
            service_account_creds=components.ServiceAccountCreds(
                private_key=os.getenv("SERVICE_ACCOUNT_CREDS_PRIVATE_KEY", "value"),
                name=os.getenv("SERVICE_ACCOUNT_CREDS_NAME", "value"),
                organization=os.getenv("SERVICE_ACCOUNT_CREDS_ORGANIZATION", "value"),
                type=os.getenv("SERVICE_ACCOUNT_CREDS_TYPE", "value"),
            ),
        ),
        client=test_http_client,
    ) as sdk:
        assert sdk is not None

        res = sdk.alternative_orders.retrieve_pending_investor_actions(
            account_id=ALTS_ACCOUNT_ID,
            alternative_order_id=ALTS_ORDER_ID,
        )
        assert res.http_meta is not None
        assert res.http_meta.response is not None
        assert res.http_meta.response.status_code == 200


def test_alternative_orders_alternative_orders_settle_alternative_order():
    test_http_client = create_test_http_client(
        "AlternativeOrders_SettleAlternativeOrder"
    )

    with SDK(
        server_url=os.getenv("SERVICE_ACCOUNT_CREDS_URL", ""),
        security=components.Security(
            api_key=os.getenv("API_KEY", "value"),
            service_account_creds=components.ServiceAccountCreds(
                private_key=os.getenv("SERVICE_ACCOUNT_CREDS_PRIVATE_KEY", "value"),
                name=os.getenv("SERVICE_ACCOUNT_CREDS_NAME", "value"),
                organization=os.getenv("SERVICE_ACCOUNT_CREDS_ORGANIZATION", "value"),
                type=os.getenv("SERVICE_ACCOUNT_CREDS_TYPE", "value"),
            ),
        ),
        client=test_http_client,
    ) as sdk:
        assert sdk is not None

        # This hardcoded order is already FILLED, so settling it again is expected
        # to fail with a SETTLEMENT_POST_FAILURE precondition error -- but accept
        # a genuine 200 too, in case the order's state ever changes.
        try:
            res = sdk.alternative_orders.settle_alternative_order(
                account_id=ALTS_ACCOUNT_ID,
                alternative_order_id=ALTS_ORDER_ID,
                settle_alternative_order_request_create={
                    "name": f"accounts/{ALTS_ACCOUNT_ID}/alternativeOrders/{ALTS_ORDER_ID}",
                    "order_settlement_target": components.OrderSettlementTarget.FILLED,
                },
            )
            assert res.http_meta is not None
            assert res.http_meta.response is not None
            assert res.http_meta.response.status_code == 200
        except errors.Status as status:
            assert status.data.code == 9
            assert "SETTLEMENT_POST_FAILURE" in status.data.message
