"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from ascend_sdk import SDK
import uuid
from ascend_sdk.models import components
import os
from tests.test_client import create_test_http_client


def test_alternative_orders_alternative_orders_create_alternative_order():
    test_http_client = create_test_http_client(
        "AlternativeOrders_CreateAlternativeOrder"
    )

    with SDK(
        server_url=os.getenv("SERVICE_ACCOUNT_CREDS_URL", ""),
        security=components.Security(
            api_key=os.getenv("API_KEY", "value"),
            service_account_creds=components.ServiceAccountCreds(
                private_key=os.getenv("SERVICE_ACCOUNT_CREDS_PRIVATE_KEY", "value"),
                name=os.getenv("SERVICE_ACCOUNT_CREDS_NAME", "value"),
                organization=os.getenv("SERVICE_ACCOUNT_CREDS_ORGANIZATION", "value"),
                type=os.getenv("SERVICE_ACCOUNT_CREDS_TYPE", "value"),
            ),
        ),
        client=test_http_client,
    ) as sdk:
        assert sdk is not None

        res = sdk.alternative_orders.create_alternative_order(
            account_id="01JHGTEPC6ZTAHCFRH2MD3VJJT",
            alternative_order_create=components.AlternativeOrderCreate(
                client_order_id=str(uuid.uuid4()),
                identifier="6684398",
                identifier_type=components.AlternativeOrderCreateIdentifierType.ASSET_ID,
                notional_value=components.DecimalCreate(
                    value="10000",
                ),
                side=components.AlternativeOrderCreateSide.BUY,
            ),
        )
        assert res.http_meta is not None
        assert res.http_meta.response is not None
        assert res.http_meta.response.status_code == 200


def test_alternative_orders_alternative_orders_list_alternative_orders():
    test_http_client = create_test_http_client(
        "AlternativeOrders_ListAlternativeOrders"
    )

    with SDK(
        server_url=os.getenv("SERVICE_ACCOUNT_CREDS_URL", ""),
        security=components.Security(
            api_key=os.getenv("API_KEY", "value"),
            service_account_creds=components.ServiceAccountCreds(
                private_key=os.getenv("SERVICE_ACCOUNT_CREDS_PRIVATE_KEY", "value"),
                name=os.getenv("SERVICE_ACCOUNT_CREDS_NAME", "value"),
                organization=os.getenv("SERVICE_ACCOUNT_CREDS_ORGANIZATION", "value"),
                type=os.getenv("SERVICE_ACCOUNT_CREDS_TYPE", "value"),
            ),
        ),
        client=test_http_client,
    ) as sdk:
        assert sdk is not None

        res = sdk.alternative_orders.list_alternative_orders(
            account_id="01JHGTEPC6ZTAHCFRH2MD3VJJT",
            page_size=25,
            page_token="",
            filter_="",
        )
        assert res.http_meta is not None
        assert res.http_meta.response is not None
        assert res.http_meta.response.status_code == 200


def test_alternative_orders_alternative_orders_get_alternative_order():
    test_http_client = create_test_http_client("AlternativeOrders_GetAlternativeOrder")

    with SDK(
        server_url=os.getenv("SERVICE_ACCOUNT_CREDS_URL", ""),
        security=components.Security(
            api_key=os.getenv("API_KEY", "value"),
            service_account_creds=components.ServiceAccountCreds(
                private_key=os.getenv("SERVICE_ACCOUNT_CREDS_PRIVATE_KEY", "value"),
                name=os.getenv("SERVICE_ACCOUNT_CREDS_NAME", "value"),
                organization=os.getenv("SERVICE_ACCOUNT_CREDS_ORGANIZATION", "value"),
                type=os.getenv("SERVICE_ACCOUNT_CREDS_TYPE", "value"),
            ),
        ),
        client=test_http_client,
    ) as sdk:
        assert sdk is not None

        res = sdk.alternative_orders.get_alternative_order(
            account_id="01JHGTEPC6ZTAHCFRH2MD3VJJT",
            alternative_order_id="01KHYEFHKS7VM17YC8BQC6A8PV",
        )
        assert res.http_meta is not None
        assert res.http_meta.response is not None
        assert res.http_meta.response.status_code == 200


def test_alternative_orders_alternative_orders_retrieve_pending_investor_actions():
    test_http_client = create_test_http_client(
        "AlternativeOrders_RetrievePendingInvestorActions"
    )

    with SDK(
        server_url=os.getenv("SERVICE_ACCOUNT_CREDS_URL", ""),
        security=components.Security(
            api_key=os.getenv("API_KEY", "value"),
            service_account_creds=components.ServiceAccountCreds(
                private_key=os.getenv("SERVICE_ACCOUNT_CREDS_PRIVATE_KEY", "value"),
                name=os.getenv("SERVICE_ACCOUNT_CREDS_NAME", "value"),
                organization=os.getenv("SERVICE_ACCOUNT_CREDS_ORGANIZATION", "value"),
                type=os.getenv("SERVICE_ACCOUNT_CREDS_TYPE", "value"),
            ),
        ),
        client=test_http_client,
    ) as sdk:
        assert sdk is not None

        res = sdk.alternative_orders.retrieve_pending_investor_actions(
            account_id="01JHGTEPC6ZTAHCFRH2MD3VJJT",
            alternative_order_id="01KHYEFHKS7VM17YC8BQC6A8PV",
        )
        assert res.http_meta is not None
        assert res.http_meta.response is not None
        assert res.http_meta.response.status_code == 200


def test_alternative_orders_alternative_orders_settle_alternative_order():
    test_http_client = create_test_http_client(
        "AlternativeOrders_SettleAlternativeOrder"
    )

    with SDK(
        server_url=os.getenv("SERVICE_ACCOUNT_CREDS_URL", ""),
        security=components.Security(
            api_key=os.getenv("API_KEY", "value"),
            service_account_creds=components.ServiceAccountCreds(
                private_key=os.getenv("SERVICE_ACCOUNT_CREDS_PRIVATE_KEY", "value"),
                name=os.getenv("SERVICE_ACCOUNT_CREDS_NAME", "value"),
                organization=os.getenv("SERVICE_ACCOUNT_CREDS_ORGANIZATION", "value"),
                type=os.getenv("SERVICE_ACCOUNT_CREDS_TYPE", "value"),
            ),
        ),
        client=test_http_client,
    ) as sdk:
        assert sdk is not None

        res = sdk.alternative_orders.settle_alternative_order(
            account_id="01JHGTEPC6ZTAHCFRH2MD3VJJT",
            alternative_order_id="01KHYEFHKS7VM17YC8BQC6A8PV",
            settle_alternative_order_request_create={
                "name": "accounts/01JHGTEPC6ZTAHCFRH2MD3VJJT/alternativeOrders/01KHYEFHKS7VM17YC8BQC6A8PV",
                "order_settlement_target": components.OrderSettlementTarget.FILLED,
            },
        )
        assert res.http_meta is not None
        assert res.http_meta.response is not None
        assert res.http_meta.response.status_code == 400
