"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from ascend_sdk import SDK
from ascend_sdk.models import components
import os


def test_investigations_investigation_service_get_investigation_get_investigation1():
    s = SDK(
        server_url="https://uat.apexapis.com",
        security=components.Security(
            api_key=os.getenv("API_KEY", ""),
            service_account_creds=components.ServiceAccountCreds(
                private_key=os.getenv("SERVICE_ACCOUNT_CREDS_PRIVATE_KEY", ""),
                name=os.getenv("SERVICE_ACCOUNT_CREDS_NAME", ""),
                organization=os.getenv("SERVICE_ACCOUNT_CREDS_ORGANIZATION", ""),
                type="serviceAccount",
            ),
        ),
    )

    assert s is not None

    res = s.investigations.get_investigation(
        investigation_id="01JHGRJG62CZ0TV805CSWYHJ31"
    )
    assert res.http_meta is not None
    assert res.http_meta.response is not None
    assert res.http_meta.response.status_code == 200


def test_investigations_investigation_service_list_investigations_list_investigations1():
    s = SDK(
        server_url="https://uat.apexapis.com",
        security=components.Security(
            api_key=os.getenv("API_KEY", ""),
            service_account_creds=components.ServiceAccountCreds(
                private_key=os.getenv("SERVICE_ACCOUNT_CREDS_PRIVATE_KEY", ""),
                name=os.getenv("SERVICE_ACCOUNT_CREDS_NAME", ""),
                organization=os.getenv("SERVICE_ACCOUNT_CREDS_ORGANIZATION", ""),
                type="serviceAccount",
            ),
        ),
    )

    assert s is not None

    res = s.investigations.list_investigations()
    assert res.http_meta is not None
    assert res.http_meta.response is not None
    assert res.http_meta.response.status_code == 200


def test_investigations_watchlist_service_get_watchlist_item_get_watchlist_item1():
    s = SDK(
        server_url="https://uat.apexapis.com",
        security=components.Security(
            api_key=os.getenv("API_KEY", ""),
            service_account_creds=components.ServiceAccountCreds(
                private_key=os.getenv("SERVICE_ACCOUNT_CREDS_PRIVATE_KEY", ""),
                name=os.getenv("SERVICE_ACCOUNT_CREDS_NAME", ""),
                organization=os.getenv("SERVICE_ACCOUNT_CREDS_ORGANIZATION", ""),
                type="serviceAccount",
            ),
        ),
    )

    assert s is not None

    res = s.investigations.get_watchlist_item(watchlist_id="DOWJONES", item_id="123456")
    assert res.http_meta is not None
    assert res.http_meta.response is not None
    assert res.http_meta.response.status_code == 200
