"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from ascend_sdk import SDK
from ascend_sdk.models import components, errors
import os
from tests.test_client import create_test_http_client


def test_test_simulation_check_deposits_simulate_create_check_deposit():
    test_http_client = create_test_http_client(
        "CheckDeposits_SimulateCreateCheckDeposit"
    )

    with SDK(
        server_url=os.getenv("SERVICE_ACCOUNT_CREDS_URL", ""),
        security=components.Security(
            api_key=os.getenv("API_KEY", "value"),
            service_account_creds=components.ServiceAccountCreds(
                private_key=os.getenv("SERVICE_ACCOUNT_CREDS_PRIVATE_KEY", "value"),
                name=os.getenv("SERVICE_ACCOUNT_CREDS_NAME", "value"),
                organization=os.getenv("SERVICE_ACCOUNT_CREDS_ORGANIZATION", "value"),
                type=os.getenv("SERVICE_ACCOUNT_CREDS_TYPE", "value"),
            ),
        ),
        client=test_http_client,
    ) as sdk:
        assert sdk is not None

        res = sdk.test_simulation.simulate_create_check_deposit(
            account_id="01JHGTEPC6ZTAHCFRH2MD3VJJT",
            simulate_create_check_deposit_request_create={
                "amount": {
                    "value": "100",
                },
                "parent": "01JHGTEPC6ZTAHCFRH2MD3VJJT",
            },
        )
        assert res.http_meta is not None
        assert res.http_meta.response is not None
        assert res.http_meta.response.status_code == 200


def test_test_simulation_check_deposits_force_approve_check_deposit():
    test_http_client = create_test_http_client("CheckDeposits_ForceApproveCheckDeposit")

    account_id = os.getenv("ACCOUNT_ID", "01JHGTEPC6ZTAHCFRH2MD3VJJT")

    with SDK(
        server_url=os.getenv("SERVICE_ACCOUNT_CREDS_URL", ""),
        security=components.Security(
            api_key=os.getenv("API_KEY", "value"),
            service_account_creds=components.ServiceAccountCreds(
                private_key=os.getenv("SERVICE_ACCOUNT_CREDS_PRIVATE_KEY", "value"),
                name=os.getenv("SERVICE_ACCOUNT_CREDS_NAME", "value"),
                organization=os.getenv("SERVICE_ACCOUNT_CREDS_ORGANIZATION", "value"),
                type=os.getenv("SERVICE_ACCOUNT_CREDS_TYPE", "value"),
            ),
        ),
        client=test_http_client,
    ) as sdk:
        assert sdk is not None

        # First, create a check deposit
        create_res = sdk.test_simulation.simulate_create_check_deposit(
            account_id=account_id,
            simulate_create_check_deposit_request_create={
                "amount": {
                    "value": "100",
                },
                "parent": account_id,
            },
        )
        assert create_res.http_meta is not None
        assert create_res.http_meta.response is not None
        assert create_res.http_meta.response.status_code == 200
        assert create_res.check_deposit is not None
        assert create_res.check_deposit.name is not None

        # Extract check deposit ID from the name
        name = create_res.check_deposit.name
        check_deposit_id = name.split("/")[-1]

        # Force approve the check deposit
        # Accept either success (200) or expected error when deposit doesn't need review
        try:
            res = sdk.test_simulation.force_approve_check_deposit(
                account_id=account_id,
                check_deposit_id=check_deposit_id,
                force_approve_check_deposit_request_create={
                    "name": name,
                },
            )
            assert res.http_meta is not None
            assert res.http_meta.response is not None
            assert res.http_meta.response.status_code == 200
        except errors.Status as e:
            # Expected when check deposit is not in PENDING_REVIEW state
            assert e.status_code == 400
            assert "does not need review" in str(e)
