"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from ascend_sdk.models.components import (
    accountaccreditation as components_accountaccreditation,
    httpmetadata as components_httpmetadata,
    setaccountaccreditationtyperequestcreate as components_setaccountaccreditationtyperequestcreate,
    status as components_status,
)
from ascend_sdk.types import BaseModel
from ascend_sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class AccountAccreditationServiceSetAccountAccreditationTypeRequestTypedDict(TypedDict):
    account_id: str
    r"""The account id."""
    set_account_accreditation_type_request_create: components_setaccountaccreditationtyperequestcreate.SetAccountAccreditationTypeRequestCreateTypedDict


class AccountAccreditationServiceSetAccountAccreditationTypeRequest(BaseModel):
    account_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The account id."""

    set_account_accreditation_type_request_create: Annotated[
        components_setaccountaccreditationtyperequestcreate.SetAccountAccreditationTypeRequestCreate,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]


class AccountAccreditationServiceSetAccountAccreditationTypeResponseTypedDict(
    TypedDict
):
    http_meta: components_httpmetadata.HTTPMetadataTypedDict
    account_accreditation: NotRequired[
        components_accountaccreditation.AccountAccreditationTypedDict
    ]
    r"""OK"""
    status: NotRequired[components_status.StatusTypedDict]
    r"""INVALID_ARGUMENT: The request has an invalid argument."""


class AccountAccreditationServiceSetAccountAccreditationTypeResponse(BaseModel):
    http_meta: Annotated[
        Optional[components_httpmetadata.HTTPMetadata], pydantic.Field(exclude=True)
    ] = None

    account_accreditation: Optional[
        components_accountaccreditation.AccountAccreditation
    ] = None
    r"""OK"""

    status: Optional[components_status.Status] = None
    r"""INVALID_ARGUMENT: The request has an invalid argument."""
