"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from ascend_sdk.models.components import (
    alternativeorder as components_alternativeorder,
    httpmetadata as components_httpmetadata,
    settlealternativeorderrequestcreate as components_settlealternativeorderrequestcreate,
    status as components_status,
)
from ascend_sdk.types import BaseModel
from ascend_sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class AlternativeOrdersSettleAlternativeOrderRequestTypedDict(TypedDict):
    account_id: str
    r"""The account id."""
    alternative_order_id: str
    r"""The alternativeOrder id."""
    settle_alternative_order_request_create: components_settlealternativeorderrequestcreate.SettleAlternativeOrderRequestCreateTypedDict


class AlternativeOrdersSettleAlternativeOrderRequest(BaseModel):
    account_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The account id."""

    alternative_order_id: Annotated[
        str,
        pydantic.Field(alias="alternativeOrder_id"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The alternativeOrder id."""

    settle_alternative_order_request_create: Annotated[
        components_settlealternativeorderrequestcreate.SettleAlternativeOrderRequestCreate,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]


class AlternativeOrdersSettleAlternativeOrderResponseTypedDict(TypedDict):
    http_meta: components_httpmetadata.HTTPMetadataTypedDict
    alternative_order: NotRequired[
        components_alternativeorder.AlternativeOrderTypedDict
    ]
    r"""OK"""
    status: NotRequired[components_status.StatusTypedDict]
    r"""INVALID_ARGUMENT: The request has an invalid argument.
    FAILED_PRECONDITION: The requested resource is not in the expected state.
    """


class AlternativeOrdersSettleAlternativeOrderResponse(BaseModel):
    http_meta: Annotated[
        Optional[components_httpmetadata.HTTPMetadata], pydantic.Field(exclude=True)
    ] = None

    alternative_order: Optional[components_alternativeorder.AlternativeOrder] = None
    r"""OK"""

    status: Optional[components_status.Status] = None
    r"""INVALID_ARGUMENT: The request has an invalid argument.
    FAILED_PRECONDITION: The requested resource is not in the expected state.
    """
