"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from ascend_sdk.models.components import (
    alternativeinvestment as components_alternativeinvestment,
    httpmetadata as components_httpmetadata,
    status as components_status,
)
from ascend_sdk.types import BaseModel
from ascend_sdk.utils import FieldMetadata, PathParamMetadata
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class AlternativeInvestmentsGetAlternativeInvestmentRequestTypedDict(TypedDict):
    asset_id: str
    r"""The asset id."""


class AlternativeInvestmentsGetAlternativeInvestmentRequest(BaseModel):
    asset_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The asset id."""


class AlternativeInvestmentsGetAlternativeInvestmentResponseTypedDict(TypedDict):
    http_meta: components_httpmetadata.HTTPMetadataTypedDict
    alternative_investment: NotRequired[
        components_alternativeinvestment.AlternativeInvestmentTypedDict
    ]
    r"""OK"""
    status: NotRequired[components_status.StatusTypedDict]
    r"""INVALID_ARGUMENT: The request has an invalid argument."""


class AlternativeInvestmentsGetAlternativeInvestmentResponse(BaseModel):
    http_meta: Annotated[
        Optional[components_httpmetadata.HTTPMetadata], pydantic.Field(exclude=True)
    ] = None

    alternative_investment: Optional[
        components_alternativeinvestment.AlternativeInvestment
    ] = None
    r"""OK"""

    status: Optional[components_status.Status] = None
    r"""INVALID_ARGUMENT: The request has an invalid argument."""
