"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from ascend_sdk.models.components import (
    httpmetadata as components_httpmetadata,
    listalternativeinvestmentsresponse as components_listalternativeinvestmentsresponse,
    status as components_status,
)
from ascend_sdk.types import BaseModel
from ascend_sdk.utils import FieldMetadata, PathParamMetadata, QueryParamMetadata
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class AlternativeInvestmentsListAlternativeInvestmentsRequestTypedDict(TypedDict):
    asset_id: str
    r"""The asset id."""
    page_size: NotRequired[int]
    r"""The maximum number of orders to return.  - Max value =100  - Values above 100 will be coerced to 100.  - If the specified value is greater than the number of orders, the service will return fewer than the specified value.  - If unspecified, at most 100 orders will be returned."""
    page_token: NotRequired[str]
    r"""For pagination, provide the page token, received from a previous `ListAlternativeInvestments` call, to retrieve the subsequent page.  All other parameters provided to `ListAlternativeInvestments` must match the request that provided the page token."""
    filter_: NotRequired[str]
    r"""A CEL string to filter results. All fields from the response can be used as filters.

    See the [CEL Search](https://developer.apexclearing.com/apex-fintech-solutions/docs/cel-search) guide for syntax details and examples.
    """


class AlternativeInvestmentsListAlternativeInvestmentsRequest(BaseModel):
    asset_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The asset id."""

    page_size: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""The maximum number of orders to return.  - Max value =100  - Values above 100 will be coerced to 100.  - If the specified value is greater than the number of orders, the service will return fewer than the specified value.  - If unspecified, at most 100 orders will be returned."""

    page_token: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""For pagination, provide the page token, received from a previous `ListAlternativeInvestments` call, to retrieve the subsequent page.  All other parameters provided to `ListAlternativeInvestments` must match the request that provided the page token."""

    filter_: Annotated[
        Optional[str],
        pydantic.Field(alias="filter"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""A CEL string to filter results. All fields from the response can be used as filters.

    See the [CEL Search](https://developer.apexclearing.com/apex-fintech-solutions/docs/cel-search) guide for syntax details and examples.
    """


class AlternativeInvestmentsListAlternativeInvestmentsResponseTypedDict(TypedDict):
    http_meta: components_httpmetadata.HTTPMetadataTypedDict
    list_alternative_investments_response: NotRequired[
        components_listalternativeinvestmentsresponse.ListAlternativeInvestmentsResponseTypedDict
    ]
    r"""OK"""
    status: NotRequired[components_status.StatusTypedDict]
    r"""INVALID_ARGUMENT: The request has an invalid argument."""


class AlternativeInvestmentsListAlternativeInvestmentsResponse(BaseModel):
    http_meta: Annotated[
        Optional[components_httpmetadata.HTTPMetadata], pydantic.Field(exclude=True)
    ] = None

    list_alternative_investments_response: Optional[
        components_listalternativeinvestmentsresponse.ListAlternativeInvestmentsResponse
    ] = None
    r"""OK"""

    status: Optional[components_status.Status] = None
    r"""INVALID_ARGUMENT: The request has an invalid argument."""
