"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from ascend_sdk.models.components import (
    alternativeinvestmentdocument as components_alternativeinvestmentdocument,
    httpmetadata as components_httpmetadata,
    status as components_status,
)
from ascend_sdk.types import BaseModel
from ascend_sdk.utils import FieldMetadata, PathParamMetadata
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class AlternativeInvestmentDocumentsGetAlternativeInvestmentDocumentRequestTypedDict(
    TypedDict
):
    asset_id: str
    r"""The asset id."""
    alternative_investment_document_id: str
    r"""The alternativeInvestmentDocument id."""


class AlternativeInvestmentDocumentsGetAlternativeInvestmentDocumentRequest(BaseModel):
    asset_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The asset id."""

    alternative_investment_document_id: Annotated[
        str,
        pydantic.Field(alias="alternativeInvestmentDocument_id"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The alternativeInvestmentDocument id."""


class AlternativeInvestmentDocumentsGetAlternativeInvestmentDocumentResponseTypedDict(
    TypedDict
):
    http_meta: components_httpmetadata.HTTPMetadataTypedDict
    alternative_investment_document: NotRequired[
        components_alternativeinvestmentdocument.AlternativeInvestmentDocumentTypedDict
    ]
    r"""OK"""
    status: NotRequired[components_status.StatusTypedDict]
    r"""INVALID_ARGUMENT: The request has an invalid argument."""


class AlternativeInvestmentDocumentsGetAlternativeInvestmentDocumentResponse(BaseModel):
    http_meta: Annotated[
        Optional[components_httpmetadata.HTTPMetadata], pydantic.Field(exclude=True)
    ] = None

    alternative_investment_document: Optional[
        components_alternativeinvestmentdocument.AlternativeInvestmentDocument
    ] = None
    r"""OK"""

    status: Optional[components_status.Status] = None
    r"""INVALID_ARGUMENT: The request has an invalid argument."""
