"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from ascend_sdk.models.components import (
    cashjournalschedule as components_cashjournalschedule,
    cashjournalscheduleupdate as components_cashjournalscheduleupdate,
    httpmetadata as components_httpmetadata,
    status as components_status,
)
from ascend_sdk.types import BaseModel
from ascend_sdk.utils import (
    FieldMetadata,
    PathParamMetadata,
    QueryParamMetadata,
    RequestMetadata,
)
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CashJournalSchedulesUpdateCashJournalScheduleRequestTypedDict(TypedDict):
    cash_journal_schedule_id: str
    r"""The cashJournalSchedule id."""
    cash_journal_schedule_update: (
        components_cashjournalscheduleupdate.CashJournalScheduleUpdateTypedDict
    )
    update_mask: NotRequired[str]
    r"""A field mask representing the update. Note: only the 'schedule_details.amount' field of a schedule is currently updatable"""


class CashJournalSchedulesUpdateCashJournalScheduleRequest(BaseModel):
    cash_journal_schedule_id: Annotated[
        str,
        pydantic.Field(alias="cashJournalSchedule_id"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The cashJournalSchedule id."""

    cash_journal_schedule_update: Annotated[
        components_cashjournalscheduleupdate.CashJournalScheduleUpdate,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]

    update_mask: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""A field mask representing the update. Note: only the 'schedule_details.amount' field of a schedule is currently updatable"""


class CashJournalSchedulesUpdateCashJournalScheduleResponseTypedDict(TypedDict):
    http_meta: components_httpmetadata.HTTPMetadataTypedDict
    cash_journal_schedule: NotRequired[
        components_cashjournalschedule.CashJournalScheduleTypedDict
    ]
    r"""OK"""
    status: NotRequired[components_status.StatusTypedDict]
    r"""INVALID_ARGUMENT: The request has an invalid argument."""


class CashJournalSchedulesUpdateCashJournalScheduleResponse(BaseModel):
    http_meta: Annotated[
        Optional[components_httpmetadata.HTTPMetadata], pydantic.Field(exclude=True)
    ] = None

    cash_journal_schedule: Optional[
        components_cashjournalschedule.CashJournalSchedule
    ] = None
    r"""OK"""

    status: Optional[components_status.Status] = None
    r"""INVALID_ARGUMENT: The request has an invalid argument."""
