"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from ascend_sdk.models.components import (
    cashjournalschedule as components_cashjournalschedule,
    httpmetadata as components_httpmetadata,
    status as components_status,
)
from ascend_sdk.types import BaseModel
from ascend_sdk.utils import FieldMetadata, PathParamMetadata
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CashJournalSchedulesGetCashJournalScheduleRequestTypedDict(TypedDict):
    cash_journal_schedule_id: str
    r"""The cashJournalSchedule id."""


class CashJournalSchedulesGetCashJournalScheduleRequest(BaseModel):
    cash_journal_schedule_id: Annotated[
        str,
        pydantic.Field(alias="cashJournalSchedule_id"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The cashJournalSchedule id."""


class CashJournalSchedulesGetCashJournalScheduleResponseTypedDict(TypedDict):
    http_meta: components_httpmetadata.HTTPMetadataTypedDict
    cash_journal_schedule: NotRequired[
        components_cashjournalschedule.CashJournalScheduleTypedDict
    ]
    r"""OK"""
    status: NotRequired[components_status.StatusTypedDict]
    r"""INVALID_ARGUMENT: The request has an invalid argument."""


class CashJournalSchedulesGetCashJournalScheduleResponse(BaseModel):
    http_meta: Annotated[
        Optional[components_httpmetadata.HTTPMetadata], pydantic.Field(exclude=True)
    ] = None

    cash_journal_schedule: Optional[
        components_cashjournalschedule.CashJournalSchedule
    ] = None
    r"""OK"""

    status: Optional[components_status.Status] = None
    r"""INVALID_ARGUMENT: The request has an invalid argument."""
