"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from ascend_sdk.models.components import (
    httpmetadata as components_httpmetadata,
    searchclosedlotsrequestcreate as components_searchclosedlotsrequestcreate,
    searchclosedlotsresponse as components_searchclosedlotsresponse,
    status as components_status,
)
from ascend_sdk.types import BaseModel
from ascend_sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CostBasisServiceSearchClosedLotsRequestTypedDict(TypedDict):
    account_id: str
    r"""The account id."""
    search_closed_lots_request_create: (
        components_searchclosedlotsrequestcreate.SearchClosedLotsRequestCreateTypedDict
    )


class CostBasisServiceSearchClosedLotsRequest(BaseModel):
    account_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The account id."""

    search_closed_lots_request_create: Annotated[
        components_searchclosedlotsrequestcreate.SearchClosedLotsRequestCreate,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]


class CostBasisServiceSearchClosedLotsResponseTypedDict(TypedDict):
    http_meta: components_httpmetadata.HTTPMetadataTypedDict
    search_closed_lots_response: NotRequired[
        components_searchclosedlotsresponse.SearchClosedLotsResponseTypedDict
    ]
    r"""OK"""
    status: NotRequired[components_status.StatusTypedDict]
    r"""INVALID_ARGUMENT: The request was not well formed. Check the error message for more details."""


class CostBasisServiceSearchClosedLotsResponse(BaseModel):
    http_meta: Annotated[
        Optional[components_httpmetadata.HTTPMetadata], pydantic.Field(exclude=True)
    ] = None

    search_closed_lots_response: Optional[
        components_searchclosedlotsresponse.SearchClosedLotsResponse
    ] = None
    r"""OK"""

    status: Optional[components_status.Status] = None
    r"""INVALID_ARGUMENT: The request was not well formed. Check the error message for more details."""
