"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from ascend_sdk.models.components import (
    canceloptioninstructionrequestcreate as components_canceloptioninstructionrequestcreate,
    httpmetadata as components_httpmetadata,
    optioninstruction as components_optioninstruction,
    status as components_status,
)
from ascend_sdk.types import BaseModel
from ascend_sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ExerciseServiceCancelOptionInstructionRequestTypedDict(TypedDict):
    account_id: str
    r"""The account id."""
    asset_id: str
    r"""The asset id."""
    instruction_id: str
    r"""The instruction id."""
    cancel_option_instruction_request_create: components_canceloptioninstructionrequestcreate.CancelOptionInstructionRequestCreateTypedDict


class ExerciseServiceCancelOptionInstructionRequest(BaseModel):
    account_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The account id."""

    asset_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The asset id."""

    instruction_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The instruction id."""

    cancel_option_instruction_request_create: Annotated[
        components_canceloptioninstructionrequestcreate.CancelOptionInstructionRequestCreate,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]


class ExerciseServiceCancelOptionInstructionResponseTypedDict(TypedDict):
    http_meta: components_httpmetadata.HTTPMetadataTypedDict
    option_instruction: NotRequired[
        components_optioninstruction.OptionInstructionTypedDict
    ]
    r"""OK"""
    status: NotRequired[components_status.StatusTypedDict]
    r"""Default error response"""


class ExerciseServiceCancelOptionInstructionResponse(BaseModel):
    http_meta: Annotated[
        Optional[components_httpmetadata.HTTPMetadata], pydantic.Field(exclude=True)
    ] = None

    option_instruction: Optional[components_optioninstruction.OptionInstruction] = None
    r"""OK"""

    status: Optional[components_status.Status] = None
    r"""Default error response"""
