"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from ascend_sdk.models.components import (
    assetbuyingpower as components_assetbuyingpower,
    httpmetadata as components_httpmetadata,
    status as components_status,
)
from ascend_sdk.types import BaseModel
from ascend_sdk.utils import FieldMetadata, PathParamMetadata
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class MarginsRealTimeGetAssetBuyingPowerRequestTypedDict(TypedDict):
    account_id: str
    r"""The account id."""
    asset_id: str
    r"""The asset id."""


class MarginsRealTimeGetAssetBuyingPowerRequest(BaseModel):
    account_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The account id."""

    asset_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The asset id."""


class MarginsRealTimeGetAssetBuyingPowerResponseTypedDict(TypedDict):
    http_meta: components_httpmetadata.HTTPMetadataTypedDict
    asset_buying_power: NotRequired[
        components_assetbuyingpower.AssetBuyingPowerTypedDict
    ]
    r"""OK"""
    status: NotRequired[components_status.StatusTypedDict]
    r"""INVALID_ARGUMENT: The request was not well formed. Check the error message for more details."""


class MarginsRealTimeGetAssetBuyingPowerResponse(BaseModel):
    http_meta: Annotated[
        Optional[components_httpmetadata.HTTPMetadata], pydantic.Field(exclude=True)
    ] = None

    asset_buying_power: Optional[components_assetbuyingpower.AssetBuyingPower] = None
    r"""OK"""

    status: Optional[components_status.Status] = None
    r"""INVALID_ARGUMENT: The request was not well formed. Check the error message for more details."""
