"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from ascend_sdk.models.components import (
    canceloptionorderrequestcreate as components_canceloptionorderrequestcreate,
    httpmetadata as components_httpmetadata,
    optionorder as components_optionorder,
    status as components_status,
)
from ascend_sdk.types import BaseModel
from ascend_sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class OptionOrderServiceCancelOptionOrderRequestTypedDict(TypedDict):
    account_id: str
    r"""The account id."""
    option_order_id: str
    r"""The optionOrder id."""
    cancel_option_order_request_create: components_canceloptionorderrequestcreate.CancelOptionOrderRequestCreateTypedDict


class OptionOrderServiceCancelOptionOrderRequest(BaseModel):
    account_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The account id."""

    option_order_id: Annotated[
        str,
        pydantic.Field(alias="optionOrder_id"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The optionOrder id."""

    cancel_option_order_request_create: Annotated[
        components_canceloptionorderrequestcreate.CancelOptionOrderRequestCreate,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]


class OptionOrderServiceCancelOptionOrderResponseTypedDict(TypedDict):
    http_meta: components_httpmetadata.HTTPMetadataTypedDict
    option_order: NotRequired[components_optionorder.OptionOrderTypedDict]
    r"""OK"""
    status: NotRequired[components_status.StatusTypedDict]
    r"""INVALID_ARGUMENT: The account_id or the option_order_id could not be determined for the request.
    FAILED_PRECONDITION: The order is not in a cancelable state
    """


class OptionOrderServiceCancelOptionOrderResponse(BaseModel):
    http_meta: Annotated[
        Optional[components_httpmetadata.HTTPMetadata], pydantic.Field(exclude=True)
    ] = None

    option_order: Optional[components_optionorder.OptionOrder] = None
    r"""OK"""

    status: Optional[components_status.Status] = None
    r"""INVALID_ARGUMENT: The account_id or the option_order_id could not be determined for the request.
    FAILED_PRECONDITION: The order is not in a cancelable state
    """
