"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from ascend_sdk.models.components import (
    httpmetadata as components_httpmetadata,
    optionorder as components_optionorder,
    setoptionextrareportingdatarequestcreate as components_setoptionextrareportingdatarequestcreate,
    status as components_status,
)
from ascend_sdk.types import BaseModel
from ascend_sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class OptionOrderServiceSetOptionExtraReportingDataRequestTypedDict(TypedDict):
    account_id: str
    r"""The account id."""
    option_order_id: str
    r"""The optionOrder id."""
    set_option_extra_reporting_data_request_create: components_setoptionextrareportingdatarequestcreate.SetOptionExtraReportingDataRequestCreateTypedDict


class OptionOrderServiceSetOptionExtraReportingDataRequest(BaseModel):
    account_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The account id."""

    option_order_id: Annotated[
        str,
        pydantic.Field(alias="optionOrder_id"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The optionOrder id."""

    set_option_extra_reporting_data_request_create: Annotated[
        components_setoptionextrareportingdatarequestcreate.SetOptionExtraReportingDataRequestCreate,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]


class OptionOrderServiceSetOptionExtraReportingDataResponseTypedDict(TypedDict):
    http_meta: components_httpmetadata.HTTPMetadataTypedDict
    option_order: NotRequired[components_optionorder.OptionOrderTypedDict]
    r"""OK"""
    status: NotRequired[components_status.StatusTypedDict]
    r"""INVALID_ARGUMENT: There was an issue with one or more fields in the request. The message field will contain details about which field failed validation and why.
    FAILED_PRECONDITION: The option order is not in a state that allows extra reporting data to be set.
    """


class OptionOrderServiceSetOptionExtraReportingDataResponse(BaseModel):
    http_meta: Annotated[
        Optional[components_httpmetadata.HTTPMetadata], pydantic.Field(exclude=True)
    ] = None

    option_order: Optional[components_optionorder.OptionOrder] = None
    r"""OK"""

    status: Optional[components_status.Status] = None
    r"""INVALID_ARGUMENT: There was an issue with one or more fields in the request. The message field will contain details about which field failed validation and why.
    FAILED_PRECONDITION: The option order is not in a state that allows extra reporting data to be set.
    """
