"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from ascend_sdk.models.components import (
    httpmetadata as components_httpmetadata,
    listpreipocompanyresearchdocumentsresponse as components_listpreipocompanyresearchdocumentsresponse,
    status as components_status,
)
from ascend_sdk.types import BaseModel
from ascend_sdk.utils import FieldMetadata, PathParamMetadata, QueryParamMetadata
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class PreIpoCompanyResearchDocumentsListPreIpoCompanyResearchDocumentsRequestTypedDict(
    TypedDict
):
    pre_ipo_company_id: str
    r"""The preIpoCompany id."""
    page_size: NotRequired[int]
    r"""The maximum number of Pre IPO Company Research Documents to return. The service may return fewer than this value. If unspecified, at most 100 Pre IPO Company Research Documents will be returned. The maximum value is 100; values above 100 will be coerced to 100."""
    page_token: NotRequired[str]
    r"""A page token, received from a previous `ListPreIpoCompanyResearchDocumentsRequest` call. Provide this to retrieve the subsequent page. When paginating, all other parameters provided to `ListPreIpoCompanyResearchDocumentsRequest` must match the call that provided the page token."""
    filter_: NotRequired[str]
    r"""A CEL string to filter results. Filterable fields:
    - type
    - relation
    Only `&&` and `==` operators are allowed.
    See the [CEL Search](https://developer.apexclearing.com/apex-fintech-solutions/docs/cel-search)
    page in Guides for more information;
    """


class PreIpoCompanyResearchDocumentsListPreIpoCompanyResearchDocumentsRequest(
    BaseModel
):
    pre_ipo_company_id: Annotated[
        str,
        pydantic.Field(alias="preIpoCompany_id"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The preIpoCompany id."""

    page_size: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""The maximum number of Pre IPO Company Research Documents to return. The service may return fewer than this value. If unspecified, at most 100 Pre IPO Company Research Documents will be returned. The maximum value is 100; values above 100 will be coerced to 100."""

    page_token: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""A page token, received from a previous `ListPreIpoCompanyResearchDocumentsRequest` call. Provide this to retrieve the subsequent page. When paginating, all other parameters provided to `ListPreIpoCompanyResearchDocumentsRequest` must match the call that provided the page token."""

    filter_: Annotated[
        Optional[str],
        pydantic.Field(alias="filter"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""A CEL string to filter results. Filterable fields:
    - type
    - relation
    Only `&&` and `==` operators are allowed.
    See the [CEL Search](https://developer.apexclearing.com/apex-fintech-solutions/docs/cel-search)
    page in Guides for more information;
    """


class PreIpoCompanyResearchDocumentsListPreIpoCompanyResearchDocumentsResponseTypedDict(
    TypedDict
):
    http_meta: components_httpmetadata.HTTPMetadataTypedDict
    list_pre_ipo_company_research_documents_response: NotRequired[
        components_listpreipocompanyresearchdocumentsresponse.ListPreIpoCompanyResearchDocumentsResponseTypedDict
    ]
    r"""OK"""
    status: NotRequired[components_status.StatusTypedDict]
    r"""INVALID_ARGUMENT: The request has an invalid argument."""


class PreIpoCompanyResearchDocumentsListPreIpoCompanyResearchDocumentsResponse(
    BaseModel
):
    http_meta: Annotated[
        Optional[components_httpmetadata.HTTPMetadata], pydantic.Field(exclude=True)
    ] = None

    list_pre_ipo_company_research_documents_response: Optional[
        components_listpreipocompanyresearchdocumentsresponse.ListPreIpoCompanyResearchDocumentsResponse
    ] = None
    r"""OK"""

    status: Optional[components_status.Status] = None
    r"""INVALID_ARGUMENT: The request has an invalid argument."""
