"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from ascend_sdk.models.components import (
    httpmetadata as components_httpmetadata,
    listpreipocompanyfundingroundsresponse as components_listpreipocompanyfundingroundsresponse,
    status as components_status,
)
from ascend_sdk.types import BaseModel
from ascend_sdk.utils import FieldMetadata, PathParamMetadata, QueryParamMetadata
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class PreIpoCompanyFundingRoundsListPreIpoCompanyFundingRoundsRequestTypedDict(
    TypedDict
):
    pre_ipo_company_id: str
    r"""The preIpoCompany id."""
    page_size: NotRequired[int]
    r"""The maximum number of Pre IPO Company Funding Rounds to return. The service may return fewer than this value. If unspecified, at most 100 Pre IPO Company Funding Rounds will be returned. The maximum value is 100; values above 100 will be coerced to 100."""
    page_token: NotRequired[str]
    r"""A page token, received from a previous `ListPreIpoCompanyFundingRoundsRequest` call. Provide this to retrieve the subsequent page. When paginating, all other parameters provided to `ListPreIpoCompanyFundingRoundsRequest` must match the call that provided the page token."""


class PreIpoCompanyFundingRoundsListPreIpoCompanyFundingRoundsRequest(BaseModel):
    pre_ipo_company_id: Annotated[
        str,
        pydantic.Field(alias="preIpoCompany_id"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The preIpoCompany id."""

    page_size: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""The maximum number of Pre IPO Company Funding Rounds to return. The service may return fewer than this value. If unspecified, at most 100 Pre IPO Company Funding Rounds will be returned. The maximum value is 100; values above 100 will be coerced to 100."""

    page_token: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""A page token, received from a previous `ListPreIpoCompanyFundingRoundsRequest` call. Provide this to retrieve the subsequent page. When paginating, all other parameters provided to `ListPreIpoCompanyFundingRoundsRequest` must match the call that provided the page token."""


class PreIpoCompanyFundingRoundsListPreIpoCompanyFundingRoundsResponseTypedDict(
    TypedDict
):
    http_meta: components_httpmetadata.HTTPMetadataTypedDict
    list_pre_ipo_company_funding_rounds_response: NotRequired[
        components_listpreipocompanyfundingroundsresponse.ListPreIpoCompanyFundingRoundsResponseTypedDict
    ]
    r"""OK"""
    status: NotRequired[components_status.StatusTypedDict]
    r"""INVALID_ARGUMENT: The request has an invalid argument."""


class PreIpoCompanyFundingRoundsListPreIpoCompanyFundingRoundsResponse(BaseModel):
    http_meta: Annotated[
        Optional[components_httpmetadata.HTTPMetadata], pydantic.Field(exclude=True)
    ] = None

    list_pre_ipo_company_funding_rounds_response: Optional[
        components_listpreipocompanyfundingroundsresponse.ListPreIpoCompanyFundingRoundsResponse
    ] = None
    r"""OK"""

    status: Optional[components_status.Status] = None
    r"""INVALID_ARGUMENT: The request has an invalid argument."""
