"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from ascend_sdk.models.components import (
    httpmetadata as components_httpmetadata,
    preipocompany as components_preipocompany,
    status as components_status,
)
from ascend_sdk.types import BaseModel
from ascend_sdk.utils import FieldMetadata, PathParamMetadata
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class PreIpoCompaniesGetPreIpoCompanyRequestTypedDict(TypedDict):
    pre_ipo_company_id: str
    r"""The preIpoCompany id."""


class PreIpoCompaniesGetPreIpoCompanyRequest(BaseModel):
    pre_ipo_company_id: Annotated[
        str,
        pydantic.Field(alias="preIpoCompany_id"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The preIpoCompany id."""


class PreIpoCompaniesGetPreIpoCompanyResponseTypedDict(TypedDict):
    http_meta: components_httpmetadata.HTTPMetadataTypedDict
    pre_ipo_company: NotRequired[components_preipocompany.PreIpoCompanyTypedDict]
    r"""OK"""
    status: NotRequired[components_status.StatusTypedDict]
    r"""INVALID_ARGUMENT: The request has an invalid argument."""


class PreIpoCompaniesGetPreIpoCompanyResponse(BaseModel):
    http_meta: Annotated[
        Optional[components_httpmetadata.HTTPMetadata], pydantic.Field(exclude=True)
    ] = None

    pre_ipo_company: Optional[components_preipocompany.PreIpoCompany] = None
    r"""OK"""

    status: Optional[components_status.Status] = None
    r"""INVALID_ARGUMENT: The request has an invalid argument."""
