workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Ascend OpenAPI:
        inputs:
            - location: ../ascend_uat_python.sdk.yaml
targets:
    sdk:
        target: python
        source: Ascend OpenAPI
        testing:
            enabled: true
            mockServer:
                enabled: false
