"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from ascend_sdk import utils
from ascend_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from ascend_sdk.utils import validate_open_enum
from datetime import datetime
from enum import Enum
from pydantic import model_serializer
from pydantic.functional_validators import PlainValidator
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class AccreditationType(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""The specified account’s current accreditation type."""

    ACCREDITATION_TYPE_UNSPECIFIED = "ACCREDITATION_TYPE_UNSPECIFIED"
    NET_WORTH_GT_1_M = "NET_WORTH_GT_1M"
    INDIVIDUAL_INCOME_GT_200_K = "INDIVIDUAL_INCOME_GT_200K"
    JOINT_INCOME_GT_300_K = "JOINT_INCOME_GT_300K"
    PROFESSION_DESIGNATION = "PROFESSION_DESIGNATION"
    TRUST_GT_5_M = "TRUST_GT_5M"
    GRANTORS_ACCREDITED = "GRANTORS_ACCREDITED"
    EQUITY_OWNERS_ACCREDITED = "EQUITY_OWNERS_ACCREDITED"
    TOTAL_ASSETS_GT_5_M = "TOTAL_ASSETS_GT_5M"
    INVESTMENT_COMPANY = "INVESTMENT_COMPANY"
    SEC_OR_EXEMPT_ADVISOR = "SEC_OR_EXEMPT_ADVISOR"
    KNOWLEDGEABLE_EMPLOYEE = "KNOWLEDGEABLE_EMPLOYEE"
    KNOWLEDGEABLE_EXECUTIVE = "KNOWLEDGEABLE_EXECUTIVE"
    FAMILY_OFFICE_GT_5_M = "FAMILY_OFFICE_GT_5M"
    NOT_ACCREDITED = "NOT_ACCREDITED"


class AccountAccreditationTypedDict(TypedDict):
    r"""An account accreditation"""

    account_id: NotRequired[str]
    r"""The ID of the account specified in the request."""
    accreditation_type: NotRequired[AccreditationType]
    r"""The specified account’s current accreditation type."""
    name: NotRequired[str]
    r"""The resource name of the account accreditation. Note `{account}` will be the `account_id` value.

    Format: accounts/{account}/accreditation
    """
    update_time: NotRequired[Nullable[datetime]]
    r"""The date and time when the accreditation was last set or updated. Uses [ISO 8601 format](https://en.wikipedia.org/wiki/ISO_8601)."""


class AccountAccreditation(BaseModel):
    r"""An account accreditation"""

    account_id: Optional[str] = None
    r"""The ID of the account specified in the request."""

    accreditation_type: Annotated[
        Optional[AccreditationType], PlainValidator(validate_open_enum(False))
    ] = None
    r"""The specified account’s current accreditation type."""

    name: Optional[str] = None
    r"""The resource name of the account accreditation. Note `{account}` will be the `account_id` value.

    Format: accounts/{account}/accreditation
    """

    update_time: OptionalNullable[datetime] = UNSET
    r"""The date and time when the accreditation was last set or updated. Uses [ISO 8601 format](https://en.wikipedia.org/wiki/ISO_8601)."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["account_id", "accreditation_type", "name", "update_time"]
        nullable_fields = ["update_time"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
