"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from ascend_sdk import utils
from ascend_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from ascend_sdk.utils import validate_open_enum
from datetime import datetime
from enum import Enum
from pydantic import model_serializer
from pydantic.functional_validators import PlainValidator
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class AlternativeOrderCumulativeNotionalValueTypedDict(TypedDict):
    r"""The actual amount of the order, which is determined after the issuer accepts the order. May differ from the requested `notional_value`."""

    value: NotRequired[str]
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class AlternativeOrderCumulativeNotionalValue(BaseModel):
    r"""The actual amount of the order, which is determined after the issuer accepts the order. May differ from the requested `notional_value`."""

    value: Optional[str] = None
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class AlternativeOrderDistributionType(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""Identifies the distribution type for buy side orders (that is, when `side` value = `BUY`). - Orders will be rejected if the alternative investment asset does not allow the requested distribution type. - Not relevant for sell orders (that is, when `side` value = `SELL`). - Confirm the asset’s `cash_distribution_allowed` and `reinvestment_distribution_allowed` properties to know what it allows."""

    DISTRIBUTION_TYPE_UNSPECIFIED = "DISTRIBUTION_TYPE_UNSPECIFIED"
    CASH = "CASH"
    REINVESTMENT = "REINVESTMENT"


class AlternativeOrderFilledQuantityTypedDict(TypedDict):
    r"""The actual filled share quantity of the order, which is determined after the issuer accepts the order. May differ from the requested `quantity`."""

    value: NotRequired[str]
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class AlternativeOrderFilledQuantity(BaseModel):
    r"""The actual filled share quantity of the order, which is determined after the issuer accepts the order. May differ from the requested `quantity`."""

    value: Optional[str] = None
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class AlternativeOrderIdentifierType(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""Identifies which parameter value is used to identify the asset in the order. The value for that parameter is used in the `identifier` field."""

    IDENTIFIER_TYPE_UNSPECIFIED = "IDENTIFIER_TYPE_UNSPECIFIED"
    ASSET_ID = "ASSET_ID"


class AlternativeOrderNotionalValueTypedDict(TypedDict):
    r"""The requested notional value for the order. - Orders can specify only one of `full`, `notional_value`, or `quantity`. - The value must be positive. - Values are scaled to two decimal places. - Note that the issuer may allow only an order for less than the requested amount."""

    value: NotRequired[str]
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class AlternativeOrderNotionalValue(BaseModel):
    r"""The requested notional value for the order. - Orders can specify only one of `full`, `notional_value`, or `quantity`. - The value must be positive. - Values are scaled to two decimal places. - Note that the issuer may allow only an order for less than the requested amount."""

    value: Optional[str] = None
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class AlternativeOrderOrderStatus(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""The order’s status at the time of the response."""

    ORDER_STATUS_UNSPECIFIED = "ORDER_STATUS_UNSPECIFIED"
    RECEIVED = "RECEIVED"
    FILLED = "FILLED"
    REJECTED = "REJECTED"
    AWAITING_SIGNATURE = "AWAITING_SIGNATURE"
    PENDING_SETTLEMENT = "PENDING_SETTLEMENT"
    BOOKED = "BOOKED"


class AlternativeOrderQuantityTypedDict(TypedDict):
    r"""The requested quantity of shares for the order. - Orders can specify only one of `full`, `notional_value`, or `quantity`. - Only relevant to redemption orders. - The value must be positive. - Note that the issuer may allow only an order for less than the requested quantity."""

    value: NotRequired[str]
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class AlternativeOrderQuantity(BaseModel):
    r"""The requested quantity of shares for the order. - Orders can specify only one of `full`, `notional_value`, or `quantity`. - Only relevant to redemption orders. - The value must be positive. - Note that the issuer may allow only an order for less than the requested quantity."""

    value: Optional[str] = None
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class SettlementDateTypedDict(TypedDict):
    r"""The date the order will be/was settled. Value will be `null` until the issuer sets a settlement date."""

    day: NotRequired[int]
    r"""Day of a month. Must be from 1 to 31 and valid for the year and month, or 0 to specify a year by itself or a year and month where the day isn't significant."""
    month: NotRequired[int]
    r"""Month of a year. Must be from 1 to 12, or 0 to specify a year without a month and day."""
    year: NotRequired[int]
    r"""Year of the date. Must be from 1 to 9999, or 0 to specify a date without a year."""


class SettlementDate(BaseModel):
    r"""The date the order will be/was settled. Value will be `null` until the issuer sets a settlement date."""

    day: Optional[int] = None
    r"""Day of a month. Must be from 1 to 31 and valid for the year and month, or 0 to specify a year by itself or a year and month where the day isn't significant."""

    month: Optional[int] = None
    r"""Month of a year. Must be from 1 to 12, or 0 to specify a year without a month and day."""

    year: Optional[int] = None
    r"""Year of the date. Must be from 1 to 9999, or 0 to specify a date without a year."""


class AlternativeOrderSide(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""The side of the order."""

    SIDE_UNSPECIFIED = "SIDE_UNSPECIFIED"
    BUY = "BUY"
    SELL = "SELL"


class AlternativeOrderTypedDict(TypedDict):
    r"""An order for an alternative investment."""

    account_id: NotRequired[str]
    r"""The ID of the account."""
    alternative_order_id: NotRequired[str]
    r"""The ID of the alternative investment order."""
    client_order_id: NotRequired[str]
    r"""A client-supplied unique ID to enforce idempotency. Each ID must be unique within the account.

    If a create request includes a `client_order_id` that matches an existing order’s `client_order_id`, the service will respond with `ALREADY_EXISTS` and will not create a new order resource.
    """
    create_time: NotRequired[Nullable[datetime]]
    r"""The date and time the order was created. Uses [ISO 8601 format](https://en.wikipedia.org/wiki/ISO_8601)."""
    cumulative_notional_value: NotRequired[
        Nullable[AlternativeOrderCumulativeNotionalValueTypedDict]
    ]
    r"""The actual amount of the order, which is determined after the issuer accepts the order. May differ from the requested `notional_value`."""
    currency_code: NotRequired[str]
    r"""The currency code of the order. Supports only \"USD\" and will default to \"USD\" if unspecified in the request."""
    distribution_type: NotRequired[AlternativeOrderDistributionType]
    r"""Identifies the distribution type for buy side orders (that is, when `side` value = `BUY`). - Orders will be rejected if the alternative investment asset does not allow the requested distribution type. - Not relevant for sell orders (that is, when `side` value = `SELL`). - Confirm the asset’s `cash_distribution_allowed` and `reinvestment_distribution_allowed` properties to know what it allows."""
    filled_quantity: NotRequired[Nullable[AlternativeOrderFilledQuantityTypedDict]]
    r"""The actual filled share quantity of the order, which is determined after the issuer accepts the order. May differ from the requested `quantity`."""
    full: NotRequired[bool]
    r"""Indicates whether this order is for a full redemption (as in, all shares redeemed). - Orders can specify only one of `full`, `notional_value`, or `quantity`. - Note that the issuer may allow only partial redemption. - Not relevant to subscription orders."""
    identifier: NotRequired[str]
    r"""The asset identifier value, dependent on enum value set for `identifier_type`.

    For example, if `identifier_type` = `ASSET_ID`, then the value for `identifier` is the `asset_id` value.
    """
    identifier_type: NotRequired[AlternativeOrderIdentifierType]
    r"""Identifies which parameter value is used to identify the asset in the order. The value for that parameter is used in the `identifier` field."""
    name: NotRequired[str]
    r"""The system-generated resource name of the alternative investment order.

    Format: accounts/{account}/alternativeOrders/{alternative_order}

    Note that `{account}` will be the `account_id` value and `{alternative_order}` will be the `alternative_order_id` value.
    """
    notional_value: NotRequired[Nullable[AlternativeOrderNotionalValueTypedDict]]
    r"""The requested notional value for the order. - Orders can specify only one of `full`, `notional_value`, or `quantity`. - The value must be positive. - Values are scaled to two decimal places. - Note that the issuer may allow only an order for less than the requested amount."""
    order_status: NotRequired[AlternativeOrderOrderStatus]
    r"""The order’s status at the time of the response."""
    quantity: NotRequired[Nullable[AlternativeOrderQuantityTypedDict]]
    r"""The requested quantity of shares for the order. - Orders can specify only one of `full`, `notional_value`, or `quantity`. - Only relevant to redemption orders. - The value must be positive. - Note that the issuer may allow only an order for less than the requested quantity."""
    settlement_date: NotRequired[Nullable[SettlementDateTypedDict]]
    r"""The date the order will be/was settled. Value will be `null` until the issuer sets a settlement date."""
    side: NotRequired[AlternativeOrderSide]
    r"""The side of the order."""
    status_message: NotRequired[str]
    r"""A system-generated, user-friendly message about the order’s status."""
    update_time: NotRequired[Nullable[datetime]]
    r"""The date and time the order was last updated. Uses [ISO 8601 format](https://en.wikipedia.org/wiki/ISO_8601)."""


class AlternativeOrder(BaseModel):
    r"""An order for an alternative investment."""

    account_id: Optional[str] = None
    r"""The ID of the account."""

    alternative_order_id: Optional[str] = None
    r"""The ID of the alternative investment order."""

    client_order_id: Optional[str] = None
    r"""A client-supplied unique ID to enforce idempotency. Each ID must be unique within the account.

    If a create request includes a `client_order_id` that matches an existing order’s `client_order_id`, the service will respond with `ALREADY_EXISTS` and will not create a new order resource.
    """

    create_time: OptionalNullable[datetime] = UNSET
    r"""The date and time the order was created. Uses [ISO 8601 format](https://en.wikipedia.org/wiki/ISO_8601)."""

    cumulative_notional_value: OptionalNullable[
        AlternativeOrderCumulativeNotionalValue
    ] = UNSET
    r"""The actual amount of the order, which is determined after the issuer accepts the order. May differ from the requested `notional_value`."""

    currency_code: Optional[str] = None
    r"""The currency code of the order. Supports only \"USD\" and will default to \"USD\" if unspecified in the request."""

    distribution_type: Annotated[
        Optional[AlternativeOrderDistributionType],
        PlainValidator(validate_open_enum(False)),
    ] = None
    r"""Identifies the distribution type for buy side orders (that is, when `side` value = `BUY`). - Orders will be rejected if the alternative investment asset does not allow the requested distribution type. - Not relevant for sell orders (that is, when `side` value = `SELL`). - Confirm the asset’s `cash_distribution_allowed` and `reinvestment_distribution_allowed` properties to know what it allows."""

    filled_quantity: OptionalNullable[AlternativeOrderFilledQuantity] = UNSET
    r"""The actual filled share quantity of the order, which is determined after the issuer accepts the order. May differ from the requested `quantity`."""

    full: Optional[bool] = None
    r"""Indicates whether this order is for a full redemption (as in, all shares redeemed). - Orders can specify only one of `full`, `notional_value`, or `quantity`. - Note that the issuer may allow only partial redemption. - Not relevant to subscription orders."""

    identifier: Optional[str] = None
    r"""The asset identifier value, dependent on enum value set for `identifier_type`.

    For example, if `identifier_type` = `ASSET_ID`, then the value for `identifier` is the `asset_id` value.
    """

    identifier_type: Annotated[
        Optional[AlternativeOrderIdentifierType],
        PlainValidator(validate_open_enum(False)),
    ] = None
    r"""Identifies which parameter value is used to identify the asset in the order. The value for that parameter is used in the `identifier` field."""

    name: Optional[str] = None
    r"""The system-generated resource name of the alternative investment order.

    Format: accounts/{account}/alternativeOrders/{alternative_order}

    Note that `{account}` will be the `account_id` value and `{alternative_order}` will be the `alternative_order_id` value.
    """

    notional_value: OptionalNullable[AlternativeOrderNotionalValue] = UNSET
    r"""The requested notional value for the order. - Orders can specify only one of `full`, `notional_value`, or `quantity`. - The value must be positive. - Values are scaled to two decimal places. - Note that the issuer may allow only an order for less than the requested amount."""

    order_status: Annotated[
        Optional[AlternativeOrderOrderStatus], PlainValidator(validate_open_enum(False))
    ] = None
    r"""The order’s status at the time of the response."""

    quantity: OptionalNullable[AlternativeOrderQuantity] = UNSET
    r"""The requested quantity of shares for the order. - Orders can specify only one of `full`, `notional_value`, or `quantity`. - Only relevant to redemption orders. - The value must be positive. - Note that the issuer may allow only an order for less than the requested quantity."""

    settlement_date: OptionalNullable[SettlementDate] = UNSET
    r"""The date the order will be/was settled. Value will be `null` until the issuer sets a settlement date."""

    side: Annotated[
        Optional[AlternativeOrderSide], PlainValidator(validate_open_enum(False))
    ] = None
    r"""The side of the order."""

    status_message: Optional[str] = None
    r"""A system-generated, user-friendly message about the order’s status."""

    update_time: OptionalNullable[datetime] = UNSET
    r"""The date and time the order was last updated. Uses [ISO 8601 format](https://en.wikipedia.org/wiki/ISO_8601)."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = [
            "account_id",
            "alternative_order_id",
            "client_order_id",
            "create_time",
            "cumulative_notional_value",
            "currency_code",
            "distribution_type",
            "filled_quantity",
            "full",
            "identifier",
            "identifier_type",
            "name",
            "notional_value",
            "order_status",
            "quantity",
            "settlement_date",
            "side",
            "status_message",
            "update_time",
        ]
        nullable_fields = [
            "create_time",
            "cumulative_notional_value",
            "filled_quantity",
            "notional_value",
            "quantity",
            "settlement_date",
            "update_time",
        ]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
