"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .decimalcreate import DecimalCreate, DecimalCreateTypedDict
from ascend_sdk import utils
from ascend_sdk.types import BaseModel
from ascend_sdk.utils import validate_open_enum
from enum import Enum
from pydantic.functional_validators import PlainValidator
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class DistributionType(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""Identifies the distribution type for buy side orders (that is, when `side` value = `BUY`). - Orders will be rejected if the alternative investment asset does not allow the requested distribution type. - Not relevant for sell orders (that is, when `side` value = `SELL`). - Confirm the asset’s `cash_distribution_allowed` and `reinvestment_distribution_allowed` properties to know what it allows."""

    DISTRIBUTION_TYPE_UNSPECIFIED = "DISTRIBUTION_TYPE_UNSPECIFIED"
    CASH = "CASH"
    REINVESTMENT = "REINVESTMENT"


class AlternativeOrderCreateIdentifierType(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""Identifies which parameter value is used to identify the asset in the order. The value for that parameter is used in the `identifier` field."""

    IDENTIFIER_TYPE_UNSPECIFIED = "IDENTIFIER_TYPE_UNSPECIFIED"
    ASSET_ID = "ASSET_ID"


class AlternativeOrderCreateSide(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""The side of the order."""

    SIDE_UNSPECIFIED = "SIDE_UNSPECIFIED"
    BUY = "BUY"
    SELL = "SELL"


class AlternativeOrderCreateTypedDict(TypedDict):
    r"""An order for an alternative investment."""

    client_order_id: str
    r"""A client-supplied unique ID to enforce idempotency. Each ID must be unique within the account.

    If a create request includes a `client_order_id` that matches an existing order’s `client_order_id`, the service will respond with `ALREADY_EXISTS` and will not create a new order resource.
    """
    identifier: str
    r"""The asset identifier value, dependent on enum value set for `identifier_type`.

    For example, if `identifier_type` = `ASSET_ID`, then the value for `identifier` is the `asset_id` value.
    """
    identifier_type: AlternativeOrderCreateIdentifierType
    r"""Identifies which parameter value is used to identify the asset in the order. The value for that parameter is used in the `identifier` field."""
    side: AlternativeOrderCreateSide
    r"""The side of the order."""
    currency_code: NotRequired[str]
    r"""The currency code of the order. Supports only \"USD\" and will default to \"USD\" if unspecified in the request."""
    distribution_type: NotRequired[DistributionType]
    r"""Identifies the distribution type for buy side orders (that is, when `side` value = `BUY`). - Orders will be rejected if the alternative investment asset does not allow the requested distribution type. - Not relevant for sell orders (that is, when `side` value = `SELL`). - Confirm the asset’s `cash_distribution_allowed` and `reinvestment_distribution_allowed` properties to know what it allows."""
    full: NotRequired[bool]
    r"""Indicates whether this order is for a full redemption (as in, all shares redeemed). - Orders can specify only one of `full`, `notional_value`, or `quantity`. - Note that the issuer may allow only partial redemption. - Not relevant to subscription orders."""
    notional_value: NotRequired[DecimalCreateTypedDict]
    r"""A representation of a decimal value, such as 2.5. Clients may convert values into language-native decimal formats, such as Java's [BigDecimal][] or Python's [decimal.Decimal][].

    [BigDecimal]:
    https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/math/BigDecimal.html
    [decimal.Decimal]: https://docs.python.org/3/library/decimal.html
    """
    quantity: NotRequired[DecimalCreateTypedDict]
    r"""A representation of a decimal value, such as 2.5. Clients may convert values into language-native decimal formats, such as Java's [BigDecimal][] or Python's [decimal.Decimal][].

    [BigDecimal]:
    https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/math/BigDecimal.html
    [decimal.Decimal]: https://docs.python.org/3/library/decimal.html
    """


class AlternativeOrderCreate(BaseModel):
    r"""An order for an alternative investment."""

    client_order_id: str
    r"""A client-supplied unique ID to enforce idempotency. Each ID must be unique within the account.

    If a create request includes a `client_order_id` that matches an existing order’s `client_order_id`, the service will respond with `ALREADY_EXISTS` and will not create a new order resource.
    """

    identifier: str
    r"""The asset identifier value, dependent on enum value set for `identifier_type`.

    For example, if `identifier_type` = `ASSET_ID`, then the value for `identifier` is the `asset_id` value.
    """

    identifier_type: Annotated[
        AlternativeOrderCreateIdentifierType, PlainValidator(validate_open_enum(False))
    ]
    r"""Identifies which parameter value is used to identify the asset in the order. The value for that parameter is used in the `identifier` field."""

    side: Annotated[
        AlternativeOrderCreateSide, PlainValidator(validate_open_enum(False))
    ]
    r"""The side of the order."""

    currency_code: Optional[str] = None
    r"""The currency code of the order. Supports only \"USD\" and will default to \"USD\" if unspecified in the request."""

    distribution_type: Annotated[
        Optional[DistributionType], PlainValidator(validate_open_enum(False))
    ] = None
    r"""Identifies the distribution type for buy side orders (that is, when `side` value = `BUY`). - Orders will be rejected if the alternative investment asset does not allow the requested distribution type. - Not relevant for sell orders (that is, when `side` value = `SELL`). - Confirm the asset’s `cash_distribution_allowed` and `reinvestment_distribution_allowed` properties to know what it allows."""

    full: Optional[bool] = None
    r"""Indicates whether this order is for a full redemption (as in, all shares redeemed). - Orders can specify only one of `full`, `notional_value`, or `quantity`. - Note that the issuer may allow only partial redemption. - Not relevant to subscription orders."""

    notional_value: Optional[DecimalCreate] = None
    r"""A representation of a decimal value, such as 2.5. Clients may convert values into language-native decimal formats, such as Java's [BigDecimal][] or Python's [decimal.Decimal][].

    [BigDecimal]:
    https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/math/BigDecimal.html
    [decimal.Decimal]: https://docs.python.org/3/library/decimal.html
    """

    quantity: Optional[DecimalCreate] = None
    r"""A representation of a decimal value, such as 2.5. Clients may convert values into language-native decimal formats, such as Java's [BigDecimal][] or Python's [decimal.Decimal][].

    [BigDecimal]:
    https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/math/BigDecimal.html
    [decimal.Decimal]: https://docs.python.org/3/library/decimal.html
    """
