"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .phonenumber import PhoneNumber, PhoneNumberTypedDict
from ascend_sdk import utils
from ascend_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from ascend_sdk.utils import validate_open_enum
from enum import Enum
from pydantic import model_serializer
from pydantic.functional_validators import PlainValidator
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CurrentPriceTypedDict(TypedDict):
    r"""The current price of one unit of the asset in USD."""

    value: NotRequired[str]
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class CurrentPrice(BaseModel):
    r"""The current price of one unit of the asset in USD."""

    value: Optional[str] = None
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class AlternativeInvestmentMailingAddressTypedDict(TypedDict):
    r"""The issuer’s mailing address."""

    address_lines: NotRequired[List[str]]
    r"""Unstructured address lines describing the lower levels of an address.

    Because values in address_lines do not have type information and may sometimes contain multiple values in a single field (e.g. \"Austin, TX\"), it is important that the line order is clear. The order of address lines should be \"envelope order\" for the country/region of the address. In places where this can vary (e.g. Japan), address_language is used to make it explicit (e.g. \"ja\" for large-to-small ordering and \"ja-Latn\" or \"en\" for small-to-large). This way, the most specific line of an address can be selected based on the language.

    The minimum permitted structural representation of an address consists of a region_code with all remaining information placed in the address_lines. It would be possible to format such an address very approximately without geocoding, but no semantic reasoning could be made about any of the address components until it was at least partially resolved.

    Creating an address only containing a region_code and address_lines, and then geocoding is the recommended way to handle completely unstructured addresses (as opposed to guessing which parts of the address should be localities or administrative areas).
    """
    administrative_area: NotRequired[str]
    r"""Optional. Highest administrative subdivision which is used for postal addresses of a country or region. For example, this can be a state, a province, an oblast, or a prefecture. Specifically, for Spain this is the province and not the autonomous community (e.g. \"Barcelona\" and not \"Catalonia\"). Many countries don't use an administrative area in postal addresses. E.g. in Switzerland this should be left unpopulated."""
    language_code: NotRequired[str]
    r"""Optional. BCP-47 language code of the contents of this address (if known). This is often the UI language of the input form or is expected to match one of the languages used in the address' country/region, or their transliterated equivalents. This can affect formatting in certain countries, but is not critical to the correctness of the data and will never affect any validation or other non-formatting related operations.

    If this value is not known, it should be omitted (rather than specifying a possibly incorrect default).

    Examples: \"zh-Hant\", \"ja\", \"ja-Latn\", \"en\".
    """
    locality: NotRequired[str]
    r"""Optional. Generally refers to the city/town portion of the address. Examples: US city, IT comune, UK post town. In regions of the world where localities are not well defined or do not fit into this structure well, leave locality empty and use address_lines."""
    organization: NotRequired[str]
    r"""Optional. The name of the organization at the address."""
    postal_code: NotRequired[str]
    r"""Optional. Postal code of the address. Not all countries use or require postal codes to be present, but where they are used, they may trigger additional validation with other parts of the address (e.g. state/zip validation in the U.S.A.)."""
    recipients: NotRequired[List[str]]
    r"""Optional. The recipient at the address. This field may, under certain circumstances, contain multiline information. For example, it might contain \"care of\" information."""
    region_code: NotRequired[str]
    r"""Required. CLDR region code of the country/region of the address. This is never inferred and it is up to the user to ensure the value is correct. See http://cldr.unicode.org/ and http://www.unicode.org/cldr/charts/30/supplemental/territory_information.html for details. Example: \"CH\" for Switzerland."""
    revision: NotRequired[int]
    r"""The schema revision of the `PostalAddress`. This must be set to 0, which is the latest revision.

    All new revisions **must** be backward compatible with old revisions.
    """
    sorting_code: NotRequired[str]
    r"""Optional. Additional, country-specific, sorting code. This is not used in most regions. Where it is used, the value is either a string like \"CEDEX\", optionally followed by a number (e.g. \"CEDEX 7\"), or just a number alone, representing the \"sector code\" (Jamaica), \"delivery area indicator\" (Malawi) or \"post office indicator\" (e.g. Côte d'Ivoire)."""
    sublocality: NotRequired[str]
    r"""Optional. Sublocality of the address. For example, this can be neighborhoods, boroughs, districts."""


class AlternativeInvestmentMailingAddress(BaseModel):
    r"""The issuer’s mailing address."""

    address_lines: Optional[List[str]] = None
    r"""Unstructured address lines describing the lower levels of an address.

    Because values in address_lines do not have type information and may sometimes contain multiple values in a single field (e.g. \"Austin, TX\"), it is important that the line order is clear. The order of address lines should be \"envelope order\" for the country/region of the address. In places where this can vary (e.g. Japan), address_language is used to make it explicit (e.g. \"ja\" for large-to-small ordering and \"ja-Latn\" or \"en\" for small-to-large). This way, the most specific line of an address can be selected based on the language.

    The minimum permitted structural representation of an address consists of a region_code with all remaining information placed in the address_lines. It would be possible to format such an address very approximately without geocoding, but no semantic reasoning could be made about any of the address components until it was at least partially resolved.

    Creating an address only containing a region_code and address_lines, and then geocoding is the recommended way to handle completely unstructured addresses (as opposed to guessing which parts of the address should be localities or administrative areas).
    """

    administrative_area: Optional[str] = None
    r"""Optional. Highest administrative subdivision which is used for postal addresses of a country or region. For example, this can be a state, a province, an oblast, or a prefecture. Specifically, for Spain this is the province and not the autonomous community (e.g. \"Barcelona\" and not \"Catalonia\"). Many countries don't use an administrative area in postal addresses. E.g. in Switzerland this should be left unpopulated."""

    language_code: Optional[str] = None
    r"""Optional. BCP-47 language code of the contents of this address (if known). This is often the UI language of the input form or is expected to match one of the languages used in the address' country/region, or their transliterated equivalents. This can affect formatting in certain countries, but is not critical to the correctness of the data and will never affect any validation or other non-formatting related operations.

    If this value is not known, it should be omitted (rather than specifying a possibly incorrect default).

    Examples: \"zh-Hant\", \"ja\", \"ja-Latn\", \"en\".
    """

    locality: Optional[str] = None
    r"""Optional. Generally refers to the city/town portion of the address. Examples: US city, IT comune, UK post town. In regions of the world where localities are not well defined or do not fit into this structure well, leave locality empty and use address_lines."""

    organization: Optional[str] = None
    r"""Optional. The name of the organization at the address."""

    postal_code: Optional[str] = None
    r"""Optional. Postal code of the address. Not all countries use or require postal codes to be present, but where they are used, they may trigger additional validation with other parts of the address (e.g. state/zip validation in the U.S.A.)."""

    recipients: Optional[List[str]] = None
    r"""Optional. The recipient at the address. This field may, under certain circumstances, contain multiline information. For example, it might contain \"care of\" information."""

    region_code: Optional[str] = None
    r"""Required. CLDR region code of the country/region of the address. This is never inferred and it is up to the user to ensure the value is correct. See http://cldr.unicode.org/ and http://www.unicode.org/cldr/charts/30/supplemental/territory_information.html for details. Example: \"CH\" for Switzerland."""

    revision: Optional[int] = None
    r"""The schema revision of the `PostalAddress`. This must be set to 0, which is the latest revision.

    All new revisions **must** be backward compatible with old revisions.
    """

    sorting_code: Optional[str] = None
    r"""Optional. Additional, country-specific, sorting code. This is not used in most regions. Where it is used, the value is either a string like \"CEDEX\", optionally followed by a number (e.g. \"CEDEX 7\"), or just a number alone, representing the \"sector code\" (Jamaica), \"delivery area indicator\" (Malawi) or \"post office indicator\" (e.g. Côte d'Ivoire)."""

    sublocality: Optional[str] = None
    r"""Optional. Sublocality of the address. For example, this can be neighborhoods, boroughs, districts."""


class PhysicalAddressTypedDict(TypedDict):
    r"""The issuer’s physical address."""

    address_lines: NotRequired[List[str]]
    r"""Unstructured address lines describing the lower levels of an address.

    Because values in address_lines do not have type information and may sometimes contain multiple values in a single field (e.g. \"Austin, TX\"), it is important that the line order is clear. The order of address lines should be \"envelope order\" for the country/region of the address. In places where this can vary (e.g. Japan), address_language is used to make it explicit (e.g. \"ja\" for large-to-small ordering and \"ja-Latn\" or \"en\" for small-to-large). This way, the most specific line of an address can be selected based on the language.

    The minimum permitted structural representation of an address consists of a region_code with all remaining information placed in the address_lines. It would be possible to format such an address very approximately without geocoding, but no semantic reasoning could be made about any of the address components until it was at least partially resolved.

    Creating an address only containing a region_code and address_lines, and then geocoding is the recommended way to handle completely unstructured addresses (as opposed to guessing which parts of the address should be localities or administrative areas).
    """
    administrative_area: NotRequired[str]
    r"""Optional. Highest administrative subdivision which is used for postal addresses of a country or region. For example, this can be a state, a province, an oblast, or a prefecture. Specifically, for Spain this is the province and not the autonomous community (e.g. \"Barcelona\" and not \"Catalonia\"). Many countries don't use an administrative area in postal addresses. E.g. in Switzerland this should be left unpopulated."""
    language_code: NotRequired[str]
    r"""Optional. BCP-47 language code of the contents of this address (if known). This is often the UI language of the input form or is expected to match one of the languages used in the address' country/region, or their transliterated equivalents. This can affect formatting in certain countries, but is not critical to the correctness of the data and will never affect any validation or other non-formatting related operations.

    If this value is not known, it should be omitted (rather than specifying a possibly incorrect default).

    Examples: \"zh-Hant\", \"ja\", \"ja-Latn\", \"en\".
    """
    locality: NotRequired[str]
    r"""Optional. Generally refers to the city/town portion of the address. Examples: US city, IT comune, UK post town. In regions of the world where localities are not well defined or do not fit into this structure well, leave locality empty and use address_lines."""
    organization: NotRequired[str]
    r"""Optional. The name of the organization at the address."""
    postal_code: NotRequired[str]
    r"""Optional. Postal code of the address. Not all countries use or require postal codes to be present, but where they are used, they may trigger additional validation with other parts of the address (e.g. state/zip validation in the U.S.A.)."""
    recipients: NotRequired[List[str]]
    r"""Optional. The recipient at the address. This field may, under certain circumstances, contain multiline information. For example, it might contain \"care of\" information."""
    region_code: NotRequired[str]
    r"""Required. CLDR region code of the country/region of the address. This is never inferred and it is up to the user to ensure the value is correct. See http://cldr.unicode.org/ and http://www.unicode.org/cldr/charts/30/supplemental/territory_information.html for details. Example: \"CH\" for Switzerland."""
    revision: NotRequired[int]
    r"""The schema revision of the `PostalAddress`. This must be set to 0, which is the latest revision.

    All new revisions **must** be backward compatible with old revisions.
    """
    sorting_code: NotRequired[str]
    r"""Optional. Additional, country-specific, sorting code. This is not used in most regions. Where it is used, the value is either a string like \"CEDEX\", optionally followed by a number (e.g. \"CEDEX 7\"), or just a number alone, representing the \"sector code\" (Jamaica), \"delivery area indicator\" (Malawi) or \"post office indicator\" (e.g. Côte d'Ivoire)."""
    sublocality: NotRequired[str]
    r"""Optional. Sublocality of the address. For example, this can be neighborhoods, boroughs, districts."""


class PhysicalAddress(BaseModel):
    r"""The issuer’s physical address."""

    address_lines: Optional[List[str]] = None
    r"""Unstructured address lines describing the lower levels of an address.

    Because values in address_lines do not have type information and may sometimes contain multiple values in a single field (e.g. \"Austin, TX\"), it is important that the line order is clear. The order of address lines should be \"envelope order\" for the country/region of the address. In places where this can vary (e.g. Japan), address_language is used to make it explicit (e.g. \"ja\" for large-to-small ordering and \"ja-Latn\" or \"en\" for small-to-large). This way, the most specific line of an address can be selected based on the language.

    The minimum permitted structural representation of an address consists of a region_code with all remaining information placed in the address_lines. It would be possible to format such an address very approximately without geocoding, but no semantic reasoning could be made about any of the address components until it was at least partially resolved.

    Creating an address only containing a region_code and address_lines, and then geocoding is the recommended way to handle completely unstructured addresses (as opposed to guessing which parts of the address should be localities or administrative areas).
    """

    administrative_area: Optional[str] = None
    r"""Optional. Highest administrative subdivision which is used for postal addresses of a country or region. For example, this can be a state, a province, an oblast, or a prefecture. Specifically, for Spain this is the province and not the autonomous community (e.g. \"Barcelona\" and not \"Catalonia\"). Many countries don't use an administrative area in postal addresses. E.g. in Switzerland this should be left unpopulated."""

    language_code: Optional[str] = None
    r"""Optional. BCP-47 language code of the contents of this address (if known). This is often the UI language of the input form or is expected to match one of the languages used in the address' country/region, or their transliterated equivalents. This can affect formatting in certain countries, but is not critical to the correctness of the data and will never affect any validation or other non-formatting related operations.

    If this value is not known, it should be omitted (rather than specifying a possibly incorrect default).

    Examples: \"zh-Hant\", \"ja\", \"ja-Latn\", \"en\".
    """

    locality: Optional[str] = None
    r"""Optional. Generally refers to the city/town portion of the address. Examples: US city, IT comune, UK post town. In regions of the world where localities are not well defined or do not fit into this structure well, leave locality empty and use address_lines."""

    organization: Optional[str] = None
    r"""Optional. The name of the organization at the address."""

    postal_code: Optional[str] = None
    r"""Optional. Postal code of the address. Not all countries use or require postal codes to be present, but where they are used, they may trigger additional validation with other parts of the address (e.g. state/zip validation in the U.S.A.)."""

    recipients: Optional[List[str]] = None
    r"""Optional. The recipient at the address. This field may, under certain circumstances, contain multiline information. For example, it might contain \"care of\" information."""

    region_code: Optional[str] = None
    r"""Required. CLDR region code of the country/region of the address. This is never inferred and it is up to the user to ensure the value is correct. See http://cldr.unicode.org/ and http://www.unicode.org/cldr/charts/30/supplemental/territory_information.html for details. Example: \"CH\" for Switzerland."""

    revision: Optional[int] = None
    r"""The schema revision of the `PostalAddress`. This must be set to 0, which is the latest revision.

    All new revisions **must** be backward compatible with old revisions.
    """

    sorting_code: Optional[str] = None
    r"""Optional. Additional, country-specific, sorting code. This is not used in most regions. Where it is used, the value is either a string like \"CEDEX\", optionally followed by a number (e.g. \"CEDEX 7\"), or just a number alone, representing the \"sector code\" (Jamaica), \"delivery area indicator\" (Malawi) or \"post office indicator\" (e.g. Côte d'Ivoire)."""

    sublocality: Optional[str] = None
    r"""Optional. Sublocality of the address. For example, this can be neighborhoods, boroughs, districts."""


class AlternativeInvestmentRegistrationType(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""The issuer’s registration type."""

    REGISTRATION_TYPE_UNSPECIFIED = "REGISTRATION_TYPE_UNSPECIFIED"
    OTHER = "OTHER"
    BROKER_DEALER = "BROKER_DEALER"
    EXEMPT_REPORTING_ADVISOR = "EXEMPT_REPORTING_ADVISOR"
    RIA = "RIA"


class AlternativeInvestmentIssuerType(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""The issuer type."""

    TYPE_UNSPECIFIED = "TYPE_UNSPECIFIED"
    CORPORATION = "CORPORATION"
    LLC = "LLC"
    LIMITED_PARTNERSHIP = "LIMITED_PARTNERSHIP"
    GENERAL_PARTNERSHIP = "GENERAL_PARTNERSHIP"
    TRUST = "TRUST"
    LTD = "LTD"
    NO_LIEN_LETTER = "NO_LIEN_LETTER"
    ENTITY_FORMATION = "ENTITY_FORMATION"


class IssuerTypedDict(TypedDict):
    r"""The issuer entity of the alternative investment asset."""

    description: NotRequired[str]
    r"""A description of the issuer."""
    emails: NotRequired[List[str]]
    r"""The issuer’s email addresses."""
    incorporated_administrative_area: NotRequired[str]
    r"""The issuer’s administrative area of incorporation."""
    incorporated_region_code: NotRequired[str]
    r"""The issuer’s region of incorporation."""
    mailing_address: NotRequired[Nullable[AlternativeInvestmentMailingAddressTypedDict]]
    r"""The issuer’s mailing address."""
    manager_crds: NotRequired[List[str]]
    r"""The issuer’s Manager CRDs."""
    phone_numbers: NotRequired[List[PhoneNumberTypedDict]]
    r"""The issuer’s phone numbers."""
    physical_address: NotRequired[Nullable[PhysicalAddressTypedDict]]
    r"""The issuer’s physical address."""
    registration_type: NotRequired[AlternativeInvestmentRegistrationType]
    r"""The issuer’s registration type."""
    title: NotRequired[str]
    r"""The issuer’s title."""
    type: NotRequired[AlternativeInvestmentIssuerType]
    r"""The issuer type."""


class Issuer(BaseModel):
    r"""The issuer entity of the alternative investment asset."""

    description: Optional[str] = None
    r"""A description of the issuer."""

    emails: Optional[List[str]] = None
    r"""The issuer’s email addresses."""

    incorporated_administrative_area: Optional[str] = None
    r"""The issuer’s administrative area of incorporation."""

    incorporated_region_code: Optional[str] = None
    r"""The issuer’s region of incorporation."""

    mailing_address: OptionalNullable[AlternativeInvestmentMailingAddress] = UNSET
    r"""The issuer’s mailing address."""

    manager_crds: Optional[List[str]] = None
    r"""The issuer’s Manager CRDs."""

    phone_numbers: Optional[List[PhoneNumber]] = None
    r"""The issuer’s phone numbers."""

    physical_address: OptionalNullable[PhysicalAddress] = UNSET
    r"""The issuer’s physical address."""

    registration_type: Annotated[
        Optional[AlternativeInvestmentRegistrationType],
        PlainValidator(validate_open_enum(False)),
    ] = None
    r"""The issuer’s registration type."""

    title: Optional[str] = None
    r"""The issuer’s title."""

    type: Annotated[
        Optional[AlternativeInvestmentIssuerType],
        PlainValidator(validate_open_enum(False)),
    ] = None
    r"""The issuer type."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = [
            "description",
            "emails",
            "incorporated_administrative_area",
            "incorporated_region_code",
            "mailing_address",
            "manager_crds",
            "phone_numbers",
            "physical_address",
            "registration_type",
            "title",
            "type",
        ]
        nullable_fields = ["mailing_address", "physical_address"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m


class MinimumInitialSubscriptionAmountTypedDict(TypedDict):
    r"""The minimum purchase amount required for an initial order of this asset. Value is in USD."""

    value: NotRequired[str]
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class MinimumInitialSubscriptionAmount(BaseModel):
    r"""The minimum purchase amount required for an initial order of this asset. Value is in USD."""

    value: Optional[str] = None
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class MinimumSubsequentSubscriptionAmountTypedDict(TypedDict):
    r"""The minimum purchase amount required for subsequent orders of this asset. Value is in USD."""

    value: NotRequired[str]
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class MinimumSubsequentSubscriptionAmount(BaseModel):
    r"""The minimum purchase amount required for subsequent orders of this asset. Value is in USD."""

    value: Optional[str] = None
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class PerShareFeeAmountTypedDict(TypedDict):
    r"""The fee amount charged per share of the Alternative Investment in USD. This is included in current price."""

    value: NotRequired[str]
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class PerShareFeeAmount(BaseModel):
    r"""The fee amount charged per share of the Alternative Investment in USD. This is included in current price."""

    value: Optional[str] = None
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class RecordState(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""Indicates the current state of the asset record.  The record state identifies which record types the asset allows."""

    RECORD_STATE_UNSPECIFIED = "RECORD_STATE_UNSPECIFIED"
    ACTIVE = "ACTIVE"
    FROZEN = "FROZEN"
    INACTIVE = "INACTIVE"


class RedemptionFrequency(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""Indicates how frequently an account can redeem the asset."""

    FREQUENCY_UNSPECIFIED = "FREQUENCY_UNSPECIFIED"
    DAILY = "DAILY"
    WEEKLY = "WEEKLY"
    BI_WEEKLY = "BI_WEEKLY"
    MONTHLY = "MONTHLY"
    QUARTERLY = "QUARTERLY"
    BI_ANNUALLY = "BI_ANNUALLY"
    ANNUALLY = "ANNUALLY"


class AlternativeInvestmentState(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""The asset’s state in the Apex alternative investment platform."""

    STATE_UNSPECIFIED = "STATE_UNSPECIFIED"
    OPEN = "OPEN"
    CLOSED = "CLOSED"


class Strategy(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""The asset’s strategy as specified by the issuer."""

    STRATEGY_UNSPECIFIED = "STRATEGY_UNSPECIFIED"
    MERGER_ARBITRAGE = "MERGER_ARBITRAGE"
    ACTIVIST = "ACTIVIST"
    MACRO = "MACRO"
    GLOBAL_MACRO = "GLOBAL_MACRO"
    LONG_SHORT = "LONG_SHORT"
    MARKET_NEUTRAL = "MARKET_NEUTRAL"
    DEDICATED_SHORT = "DEDICATED_SHORT"
    FIXED_INCOME = "FIXED_INCOME"
    EQUITY_HEDGE = "EQUITY_HEDGE"
    RELATIVE_VALUE = "RELATIVE_VALUE"
    EVENT_DRIVEN = "EVENT_DRIVEN"
    VARIABLE_EQUITY = "VARIABLE_EQUITY"
    COMMODITY_TRADING = "COMMODITY_TRADING"
    CTA_MANAGED_FUTURES = "CTA_MANAGED_FUTURES"
    OTHER = "OTHER"


class SubscriptionFrequency(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""Indicates how frequently the asset will accept subscriptions (that is, how often an account is allowed to buy the asset)."""

    FREQUENCY_UNSPECIFIED = "FREQUENCY_UNSPECIFIED"
    DAILY = "DAILY"
    WEEKLY = "WEEKLY"
    BI_WEEKLY = "BI_WEEKLY"
    MONTHLY = "MONTHLY"
    QUARTERLY = "QUARTERLY"
    BI_ANNUALLY = "BI_ANNUALLY"
    ANNUALLY = "ANNUALLY"


class SubscriptionOrderProcess(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""The process used for subscriptions orders of this asset."""

    SUBSCRIPTION_ORDER_PROCESS_UNSPECIFIED = "SUBSCRIPTION_ORDER_PROCESS_UNSPECIFIED"
    SETTLEMENT_POST_NAV_CALCULATION = "SETTLEMENT_POST_NAV_CALCULATION"
    SETTLEMENT_PRE_NAV_CALCULATION = "SETTLEMENT_PRE_NAV_CALCULATION"
    ESCROW_TRADE = "ESCROW_TRADE"
    COMMITMENT_DRAW_DOWN = "COMMITMENT_DRAW_DOWN"


class TaxReportingStructure(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""The asset’s tax reporting structure."""

    TAX_REPORTING_STRUCTURE_UNSPECIFIED = "TAX_REPORTING_STRUCTURE_UNSPECIFIED"
    TAX_REPORTING_STRUCTURE_1099 = "TAX_REPORTING_STRUCTURE_1099"
    TAX_REPORTING_STRUCTURE_K1 = "TAX_REPORTING_STRUCTURE_K1"
    TAX_REPORTING_STRUCTURE_OTHER = "TAX_REPORTING_STRUCTURE_OTHER"


class AlternativeInvestmentType(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""The type of alternative investment asset."""

    TYPE_UNSPECIFIED = "TYPE_UNSPECIFIED"
    HEDGE_FUND = "HEDGE_FUND"
    FUND_OF_FUNDS = "FUND_OF_FUNDS"
    PRIVATE_EQUITY_FUND = "PRIVATE_EQUITY_FUND"
    MANAGED_DEBT_FUND = "MANAGED_DEBT_FUND"
    PRIVATE_DEBT_FUND = "PRIVATE_DEBT_FUND"
    MANAGED_CURRENCY_FUND = "MANAGED_CURRENCY_FUND"
    COMMODITY_POOL_FUND = "COMMODITY_POOL_FUND"
    REIT = "REIT"
    MANAGED_FUTURE_FUND = "MANAGED_FUTURE_FUND"
    OTHER_TYPE = "OTHER_TYPE"
    BUSINESS_DEVELOPMENT_CORPORATION = "BUSINESS_DEVELOPMENT_CORPORATION"
    REGISTERED_HEDGE_FUND = "REGISTERED_HEDGE_FUND"
    OIL_AND_GAS_PUBLIC = "OIL_AND_GAS_PUBLIC"
    OIL_AND_GAS_PRIVATE = "OIL_AND_GAS_PRIVATE"
    EQUIPMENT_LEASING_PUBLIC = "EQUIPMENT_LEASING_PUBLIC"
    EQUIPMENT_LEASING_PRIVATE = "EQUIPMENT_LEASING_PRIVATE"
    FUTURES_PUBLIC = "FUTURES_PUBLIC"
    FUTURES_PRIVATE = "FUTURES_PRIVATE"
    NOTES_PUBLIC = "NOTES_PUBLIC"
    NOTES_PRIVATE = "NOTES_PRIVATE"
    REAL_ESTATE_PUBLIC = "REAL_ESTATE_PUBLIC"
    REAL_ESTATE_PRIVATE = "REAL_ESTATE_PRIVATE"
    CLOSED_END_MANAGEMENT_INVESTMENT_COMPANY = (
        "CLOSED_END_MANAGEMENT_INVESTMENT_COMPANY"
    )


class AlternativeInvestmentTypedDict(TypedDict):
    r"""An alternative investment is a financial asset that does not fall into one of the conventional investment categories."""

    asset_id: NotRequired[str]
    r"""The ID of the alternative asset specified in the request."""
    cash_distribution_allowed: NotRequired[bool]
    r"""Indicates whether the asset allows cash distributions.   If `TRUE` the alternative order request can specify `CASH` as the `distribution type`."""
    current_price: NotRequired[Nullable[CurrentPriceTypedDict]]
    r"""The current price of one unit of the asset in USD."""
    cusip: NotRequired[str]
    r"""The CUSIP of the asset. It is a nine-character alphanumeric identifier used to uniquely identify securities, particularly in the United States and Canada.

    A true CUSIP consists of:  - A six-character identifier for the issuer (company, municipality, etc.). - A two-character identifier for the type of security (equity, debt, etc.) and the specific issue within the issuer.  - A single check digit.

    Many alternative investments assets do not have a true CUSIP.  In such cases, the system generates a synthetic CUSIP when the asset is created.
    """
    description: NotRequired[str]
    r"""A plain-text description of the asset, specified by the issuer."""
    dividend_enabled: NotRequired[bool]
    r"""Indicates whether the asset distributes a dividend."""
    initial_subscription_allowed: NotRequired[bool]
    r"""Indicates whether the asset allows initial subscriptions to new investors."""
    isin: NotRequired[str]
    r"""The ISIN of the asset. It is a twelve-character alphanumeric code used to uniquely identify a security globally, as well as facilitate clearing, reporting, and settlement of trades defined by [ISO 6166](https://en.wikipedia.org/wiki/International_Securities_Identification_Number).

    An ISIN consists of:  - A two-letter country code.  - A nine-character alphanumeric security identifier (National Securities Identifying Number or NSIN). - A single check digit.

    Not all alternative investment assets have an ISIN.
    """
    issuer: NotRequired[Nullable[IssuerTypedDict]]
    r"""The issuer entity of the alternative investment asset."""
    issuing_region_code: NotRequired[str]
    r"""The Unicode CLDR region code of the issuing region (ex: US)."""
    maximum_subscription_quantity: NotRequired[int]
    r"""The maximum number of shares allowed to purchase in a single order for this asset."""
    minimum_initial_subscription_amount: NotRequired[
        Nullable[MinimumInitialSubscriptionAmountTypedDict]
    ]
    r"""The minimum purchase amount required for an initial order of this asset. Value is in USD."""
    minimum_subscription_quantity: NotRequired[int]
    r"""The minimum number of shares allowed to purchase in a single order for this asset."""
    minimum_subsequent_subscription_amount: NotRequired[
        Nullable[MinimumSubsequentSubscriptionAmountTypedDict]
    ]
    r"""The minimum purchase amount required for subsequent orders of this asset. Value is in USD."""
    name: NotRequired[str]
    r"""The system-generated resource name of the alternative investment asset.  Format: assets/{asset}/alternativeInvestment   Note that `{asset}` will be the `asset_id` value."""
    non_retirement_eligible: NotRequired[bool]
    r"""Indicates whether non-retirement accounts (ex: individual) are eligible to hold the alternative investment asset. - If `TRUE` then non-retirement accounts are eligible to hold the asset. - If `FALSE` then non-retirement accounts are not eligible to hold the asset."""
    per_share_fee_amount: NotRequired[Nullable[PerShareFeeAmountTypedDict]]
    r"""The fee amount charged per share of the Alternative Investment in USD. This is included in current price."""
    pre_ipo_company_id: NotRequired[str]
    r"""The ID of the Pre IPO Company associated with the Alternative Investment. Not all Alternative Investments are associated with a Pre IPO Company."""
    record_state: NotRequired[RecordState]
    r"""Indicates the current state of the asset record.  The record state identifies which record types the asset allows."""
    redeemable: NotRequired[bool]
    r"""Indicates whether the asset is allowed to be redeemed."""
    redemption_frequency: NotRequired[RedemptionFrequency]
    r"""Indicates how frequently an account can redeem the asset."""
    reinvestment_distribution_allowed: NotRequired[bool]
    r"""Indicates whether the asset allows reinvestment distributions.

    If `TRUE` the alternative order request can specify `REINVESTMENT` as the `distribution type`.
    """
    retirement_eligible: NotRequired[bool]
    r"""Indicates whether retirement accounts (ex: IRA) are eligible to hold the asset. - If `TRUE` then retirement accounts are eligible to hold the asset.  - If `FALSE` then retirement accounts are not eligible to hold the asset."""
    share_class: NotRequired[str]
    r"""The asset’s designated share class."""
    state: NotRequired[AlternativeInvestmentState]
    r"""The asset’s state in the Apex alternative investment platform."""
    strategy: NotRequired[Strategy]
    r"""The asset’s strategy as specified by the issuer."""
    subscription_frequency: NotRequired[SubscriptionFrequency]
    r"""Indicates how frequently the asset will accept subscriptions (that is, how often an account is allowed to buy the asset)."""
    subscription_order_process: NotRequired[SubscriptionOrderProcess]
    r"""The process used for subscriptions orders of this asset."""
    subsequent_subscription_allowed: NotRequired[bool]
    r"""Indicates whether the asset allows subsequent purchase orders for existing investors."""
    tax_reporting_structure: NotRequired[TaxReportingStructure]
    r"""The asset’s tax reporting structure."""
    title: NotRequired[str]
    r"""The name of the asset, in plain text, as specified by the issuer."""
    type: NotRequired[AlternativeInvestmentType]
    r"""The type of alternative investment asset."""


class AlternativeInvestment(BaseModel):
    r"""An alternative investment is a financial asset that does not fall into one of the conventional investment categories."""

    asset_id: Optional[str] = None
    r"""The ID of the alternative asset specified in the request."""

    cash_distribution_allowed: Optional[bool] = None
    r"""Indicates whether the asset allows cash distributions.   If `TRUE` the alternative order request can specify `CASH` as the `distribution type`."""

    current_price: OptionalNullable[CurrentPrice] = UNSET
    r"""The current price of one unit of the asset in USD."""

    cusip: Optional[str] = None
    r"""The CUSIP of the asset. It is a nine-character alphanumeric identifier used to uniquely identify securities, particularly in the United States and Canada.

    A true CUSIP consists of:  - A six-character identifier for the issuer (company, municipality, etc.). - A two-character identifier for the type of security (equity, debt, etc.) and the specific issue within the issuer.  - A single check digit.

    Many alternative investments assets do not have a true CUSIP.  In such cases, the system generates a synthetic CUSIP when the asset is created.
    """

    description: Optional[str] = None
    r"""A plain-text description of the asset, specified by the issuer."""

    dividend_enabled: Optional[bool] = None
    r"""Indicates whether the asset distributes a dividend."""

    initial_subscription_allowed: Optional[bool] = None
    r"""Indicates whether the asset allows initial subscriptions to new investors."""

    isin: Optional[str] = None
    r"""The ISIN of the asset. It is a twelve-character alphanumeric code used to uniquely identify a security globally, as well as facilitate clearing, reporting, and settlement of trades defined by [ISO 6166](https://en.wikipedia.org/wiki/International_Securities_Identification_Number).

    An ISIN consists of:  - A two-letter country code.  - A nine-character alphanumeric security identifier (National Securities Identifying Number or NSIN). - A single check digit.

    Not all alternative investment assets have an ISIN.
    """

    issuer: OptionalNullable[Issuer] = UNSET
    r"""The issuer entity of the alternative investment asset."""

    issuing_region_code: Optional[str] = None
    r"""The Unicode CLDR region code of the issuing region (ex: US)."""

    maximum_subscription_quantity: Optional[int] = None
    r"""The maximum number of shares allowed to purchase in a single order for this asset."""

    minimum_initial_subscription_amount: OptionalNullable[
        MinimumInitialSubscriptionAmount
    ] = UNSET
    r"""The minimum purchase amount required for an initial order of this asset. Value is in USD."""

    minimum_subscription_quantity: Optional[int] = None
    r"""The minimum number of shares allowed to purchase in a single order for this asset."""

    minimum_subsequent_subscription_amount: OptionalNullable[
        MinimumSubsequentSubscriptionAmount
    ] = UNSET
    r"""The minimum purchase amount required for subsequent orders of this asset. Value is in USD."""

    name: Optional[str] = None
    r"""The system-generated resource name of the alternative investment asset.  Format: assets/{asset}/alternativeInvestment   Note that `{asset}` will be the `asset_id` value."""

    non_retirement_eligible: Optional[bool] = None
    r"""Indicates whether non-retirement accounts (ex: individual) are eligible to hold the alternative investment asset. - If `TRUE` then non-retirement accounts are eligible to hold the asset. - If `FALSE` then non-retirement accounts are not eligible to hold the asset."""

    per_share_fee_amount: OptionalNullable[PerShareFeeAmount] = UNSET
    r"""The fee amount charged per share of the Alternative Investment in USD. This is included in current price."""

    pre_ipo_company_id: Optional[str] = None
    r"""The ID of the Pre IPO Company associated with the Alternative Investment. Not all Alternative Investments are associated with a Pre IPO Company."""

    record_state: Annotated[
        Optional[RecordState], PlainValidator(validate_open_enum(False))
    ] = None
    r"""Indicates the current state of the asset record.  The record state identifies which record types the asset allows."""

    redeemable: Optional[bool] = None
    r"""Indicates whether the asset is allowed to be redeemed."""

    redemption_frequency: Annotated[
        Optional[RedemptionFrequency], PlainValidator(validate_open_enum(False))
    ] = None
    r"""Indicates how frequently an account can redeem the asset."""

    reinvestment_distribution_allowed: Optional[bool] = None
    r"""Indicates whether the asset allows reinvestment distributions.

    If `TRUE` the alternative order request can specify `REINVESTMENT` as the `distribution type`.
    """

    retirement_eligible: Optional[bool] = None
    r"""Indicates whether retirement accounts (ex: IRA) are eligible to hold the asset. - If `TRUE` then retirement accounts are eligible to hold the asset.  - If `FALSE` then retirement accounts are not eligible to hold the asset."""

    share_class: Optional[str] = None
    r"""The asset’s designated share class."""

    state: Annotated[
        Optional[AlternativeInvestmentState], PlainValidator(validate_open_enum(False))
    ] = None
    r"""The asset’s state in the Apex alternative investment platform."""

    strategy: Annotated[
        Optional[Strategy], PlainValidator(validate_open_enum(False))
    ] = None
    r"""The asset’s strategy as specified by the issuer."""

    subscription_frequency: Annotated[
        Optional[SubscriptionFrequency], PlainValidator(validate_open_enum(False))
    ] = None
    r"""Indicates how frequently the asset will accept subscriptions (that is, how often an account is allowed to buy the asset)."""

    subscription_order_process: Annotated[
        Optional[SubscriptionOrderProcess], PlainValidator(validate_open_enum(False))
    ] = None
    r"""The process used for subscriptions orders of this asset."""

    subsequent_subscription_allowed: Optional[bool] = None
    r"""Indicates whether the asset allows subsequent purchase orders for existing investors."""

    tax_reporting_structure: Annotated[
        Optional[TaxReportingStructure], PlainValidator(validate_open_enum(False))
    ] = None
    r"""The asset’s tax reporting structure."""

    title: Optional[str] = None
    r"""The name of the asset, in plain text, as specified by the issuer."""

    type: Annotated[
        Optional[AlternativeInvestmentType], PlainValidator(validate_open_enum(False))
    ] = None
    r"""The type of alternative investment asset."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = [
            "asset_id",
            "cash_distribution_allowed",
            "current_price",
            "cusip",
            "description",
            "dividend_enabled",
            "initial_subscription_allowed",
            "isin",
            "issuer",
            "issuing_region_code",
            "maximum_subscription_quantity",
            "minimum_initial_subscription_amount",
            "minimum_subscription_quantity",
            "minimum_subsequent_subscription_amount",
            "name",
            "non_retirement_eligible",
            "per_share_fee_amount",
            "pre_ipo_company_id",
            "record_state",
            "redeemable",
            "redemption_frequency",
            "reinvestment_distribution_allowed",
            "retirement_eligible",
            "share_class",
            "state",
            "strategy",
            "subscription_frequency",
            "subscription_order_process",
            "subsequent_subscription_allowed",
            "tax_reporting_structure",
            "title",
            "type",
        ]
        nullable_fields = [
            "current_price",
            "issuer",
            "minimum_initial_subscription_amount",
            "minimum_subsequent_subscription_amount",
            "per_share_fee_amount",
        ]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
