"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from ascend_sdk import utils
from ascend_sdk.types import BaseModel
from ascend_sdk.utils import validate_open_enum
from enum import Enum
from pydantic.functional_validators import PlainValidator
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class AlternativeInvestmentDocumentType(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""The investment document’s type."""

    TYPE_UNSPECIFIED = "TYPE_UNSPECIFIED"
    OFFERING_DOCUMENT = "OFFERING_DOCUMENT"
    SUBSCRIPTION_AGREEMENT = "SUBSCRIPTION_AGREEMENT"
    K1 = "K1"
    RISK_FACTORS = "RISK_FACTORS"
    KEY_TERMS = "KEY_TERMS"


class AlternativeInvestmentDocumentTypedDict(TypedDict):
    r"""An alternative investment asset document."""

    asset_id: NotRequired[str]
    r"""The ID of the parent asset."""
    document_id: NotRequired[str]
    r"""The ID of the investment document."""
    name: NotRequired[str]
    r"""The resource name of the document.  Format: assets/{asset}/alternativeInvestmentDocuments/{alternative_investment_document}  Note that `{asset}` will be the parent `asset_id` value and `{alternative_investment_document}` will be the `alternativeInvestmentDocument_id` value."""
    title: NotRequired[str]
    r"""The investment document’s title."""
    type: NotRequired[AlternativeInvestmentDocumentType]
    r"""The investment document’s type."""


class AlternativeInvestmentDocument(BaseModel):
    r"""An alternative investment asset document."""

    asset_id: Optional[str] = None
    r"""The ID of the parent asset."""

    document_id: Optional[str] = None
    r"""The ID of the investment document."""

    name: Optional[str] = None
    r"""The resource name of the document.  Format: assets/{asset}/alternativeInvestmentDocuments/{alternative_investment_document}  Note that `{asset}` will be the parent `asset_id` value and `{alternative_investment_document}` will be the `alternativeInvestmentDocument_id` value."""

    title: Optional[str] = None
    r"""The investment document’s title."""

    type: Annotated[
        Optional[AlternativeInvestmentDocumentType],
        PlainValidator(validate_open_enum(False)),
    ] = None
    r"""The investment document’s type."""
