"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .extrareportingdatacreate import (
    ExtraReportingDataCreate,
    ExtraReportingDataCreateTypedDict,
)
from ascend_sdk.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class BasketTradingSetExtraReportingDataRequestCreateTypedDict(TypedDict):
    r"""The message to set extra reporting data onto a basket order"""

    client_order_id: str
    r"""The client-provided order id for the order to update"""
    name: str
    r"""Format: correspondents/{correspondent}/baskets/{basket}"""
    extra_reporting_data: NotRequired[ExtraReportingDataCreateTypedDict]
    r"""Any extra reporting data provided by the client for an order"""


class BasketTradingSetExtraReportingDataRequestCreate(BaseModel):
    r"""The message to set extra reporting data onto a basket order"""

    client_order_id: str
    r"""The client-provided order id for the order to update"""

    name: str
    r"""Format: correspondents/{correspondent}/baskets/{basket}"""

    extra_reporting_data: Optional[ExtraReportingDataCreate] = None
    r"""Any extra reporting data provided by the client for an order"""
