"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from ascend_sdk import utils
from ascend_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from ascend_sdk.utils import validate_open_enum
from datetime import datetime
from enum import Enum
from pydantic import model_serializer
from pydantic.functional_validators import PlainValidator
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CancelOptionOrderRequestCreateCancelInitiator(
    str, Enum, metaclass=utils.OpenEnumMeta
):
    r"""Identifies whether the cancel was initiated by the correspondent firm (FIRM) or the customer (CLIENT). Defaults to CLIENT if not provided. Required for correspondents using Apex CAT reporting services."""

    INITIATOR_UNSPECIFIED = "INITIATOR_UNSPECIFIED"
    FIRM = "FIRM"
    CLIENT = "CLIENT"


class CancelOptionOrderRequestCreateTypedDict(TypedDict):
    r"""The message to request cancellation of an existing option order"""

    name: str
    r"""Format: accounts/{account_id}/optionOrders/{option_order_id}"""
    cancel_initiator: NotRequired[CancelOptionOrderRequestCreateCancelInitiator]
    r"""Identifies whether the cancel was initiated by the correspondent firm (FIRM) or the customer (CLIENT). Defaults to CLIENT if not provided. Required for correspondents using Apex CAT reporting services."""
    client_cancel_received_time: NotRequired[Nullable[datetime]]
    r"""The time the correspondent received the cancel instruction from the customer. Required for correspondents using Apex CAT reporting services."""
    client_cancel_sent_time: NotRequired[Nullable[datetime]]
    r"""The time the correspondent sent this cancel request, before Apex received it. Required for correspondents using Apex CAT reporting services."""


class CancelOptionOrderRequestCreate(BaseModel):
    r"""The message to request cancellation of an existing option order"""

    name: str
    r"""Format: accounts/{account_id}/optionOrders/{option_order_id}"""

    cancel_initiator: Annotated[
        Optional[CancelOptionOrderRequestCreateCancelInitiator],
        PlainValidator(validate_open_enum(False)),
    ] = None
    r"""Identifies whether the cancel was initiated by the correspondent firm (FIRM) or the customer (CLIENT). Defaults to CLIENT if not provided. Required for correspondents using Apex CAT reporting services."""

    client_cancel_received_time: OptionalNullable[datetime] = UNSET
    r"""The time the correspondent received the cancel instruction from the customer. Required for correspondents using Apex CAT reporting services."""

    client_cancel_sent_time: OptionalNullable[datetime] = UNSET
    r"""The time the correspondent sent this cancel request, before Apex received it. Required for correspondents using Apex CAT reporting services."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = [
            "cancel_initiator",
            "client_cancel_received_time",
            "client_cancel_sent_time",
        ]
        nullable_fields = ["client_cancel_received_time", "client_cancel_sent_time"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
