"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from ascend_sdk.types import BaseModel
from typing_extensions import TypedDict


class CancelOptionOrderRequestCreateTypedDict(TypedDict):
    r"""The message to request cancellation of an existing option order"""

    name: str
    r"""Format: accounts/{account_id}/optionOrders/{option_order_id}"""


class CancelOptionOrderRequestCreate(BaseModel):
    r"""The message to request cancellation of an existing option order"""

    name: str
    r"""Format: accounts/{account_id}/optionOrders/{option_order_id}"""
