"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .withdrawalscheduledetailsupdate import (
    WithdrawalScheduleDetailsUpdate,
    WithdrawalScheduleDetailsUpdateTypedDict,
)
from ascend_sdk.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class CashJournalScheduleUpdateTypedDict(TypedDict):
    r"""A Cash Journal transfer schedule"""

    schedule_details: NotRequired[WithdrawalScheduleDetailsUpdateTypedDict]
    r"""Details of withdrawal schedule transfers"""


class CashJournalScheduleUpdate(BaseModel):
    r"""A Cash Journal transfer schedule"""

    schedule_details: Optional[WithdrawalScheduleDetailsUpdate] = None
    r"""Details of withdrawal schedule transfers"""
