"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from ascend_sdk import utils
from ascend_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from ascend_sdk.utils import validate_open_enum
from enum import Enum
from pydantic import model_serializer
from pydantic.functional_validators import PlainValidator
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class AcquisitionAdjustedNetAmountTypedDict(TypedDict):
    r"""Acquisition cost for longs, proceeds for shorts, net of commissions and fees, adjusted for corporate actions, return of capital, liquidations, option premium paid or received, and wash sales. Closed lots are also adjusted for OID, amortized premium, accreted discount, and principal payments, where applicable."""

    value: NotRequired[str]
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class AcquisitionAdjustedNetAmount(BaseModel):
    r"""Acquisition cost for longs, proceeds for shorts, net of commissions and fees, adjusted for corporate actions, return of capital, liquidations, option premium paid or received, and wash sales. Closed lots are also adjusted for OID, amortized premium, accreted discount, and principal payments, where applicable."""

    value: Optional[str] = None
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class AcquisitionAdjustedNetPerShareAmountTypedDict(TypedDict):
    r"""Acquisition unit cost for longs, unit proceeds for shorts, expressed as a price using security multiplier."""

    value: NotRequired[str]
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class AcquisitionAdjustedNetPerShareAmount(BaseModel):
    r"""Acquisition unit cost for longs, unit proceeds for shorts, expressed as a price using security multiplier."""

    value: Optional[str] = None
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class AcquisitionCommissionFeeAmountTypedDict(TypedDict):
    r"""Commission and fee of original acquisition, when known, prorated for lot quantity, adjusted for corporate actions, return of capital, and liquidations."""

    value: NotRequired[str]
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class AcquisitionCommissionFeeAmount(BaseModel):
    r"""Commission and fee of original acquisition, when known, prorated for lot quantity, adjusted for corporate actions, return of capital, and liquidations."""

    value: Optional[str] = None
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class AcquisitionExecutionPriceAmountTypedDict(TypedDict):
    r"""Execution price of original acquisition (buy-to-open or sell-to-open), when known, adjusted for corporate actions, return of capital, and liquidations."""

    value: NotRequired[str]
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class AcquisitionExecutionPriceAmount(BaseModel):
    r"""Execution price of original acquisition (buy-to-open or sell-to-open), when known, adjusted for corporate actions, return of capital, and liquidations."""

    value: Optional[str] = None
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class AcquisitionFxRateAmountTypedDict(TypedDict):
    r"""Acquisition exchange rate, expressed as USD price of local currency (1 for USD lots)."""

    value: NotRequired[str]
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class AcquisitionFxRateAmount(BaseModel):
    r"""Acquisition exchange rate, expressed as USD price of local currency (1 for USD lots)."""

    value: Optional[str] = None
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class AcquisitionOriginalNetAmountTypedDict(TypedDict):
    r"""Original acquisition cost for longs, proceeds for shorts, net of commissions and fees."""

    value: NotRequired[str]
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class AcquisitionOriginalNetAmount(BaseModel):
    r"""Original acquisition cost for longs, proceeds for shorts, net of commissions and fees."""

    value: Optional[str] = None
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class AcquisitionOriginalTradeDateTypedDict(TypedDict):
    r"""Trade date of original buy-to-open or sell-to-open transaction."""

    day: NotRequired[int]
    r"""Day of a month. Must be from 1 to 31 and valid for the year and month, or 0 to specify a year by itself or a year and month where the day isn't significant."""
    month: NotRequired[int]
    r"""Month of a year. Must be from 1 to 12, or 0 to specify a year without a month and day."""
    year: NotRequired[int]
    r"""Year of the date. Must be from 1 to 9999, or 0 to specify a date without a year."""


class AcquisitionOriginalTradeDate(BaseModel):
    r"""Trade date of original buy-to-open or sell-to-open transaction."""

    day: Optional[int] = None
    r"""Day of a month. Must be from 1 to 31 and valid for the year and month, or 0 to specify a year by itself or a year and month where the day isn't significant."""

    month: Optional[int] = None
    r"""Month of a year. Must be from 1 to 12, or 0 to specify a year without a month and day."""

    year: Optional[int] = None
    r"""Year of the date. Must be from 1 to 9999, or 0 to specify a date without a year."""


class AcquisitionTrueZeroIndicator(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""Indicates whether the acquisition was a true-zero acquisition."""

    ACQUISITION_TRUE_ZERO_INDICATOR_UNSPECIFIED = (
        "ACQUISITION_TRUE_ZERO_INDICATOR_UNSPECIFIED"
    )
    ZERO_ACQUISITION = "ZERO_ACQUISITION"


class AverageBasisIndicator(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""Indicates average basis acquisition."""

    AVERAGE_BASIS_INDICATOR_UNSPECIFIED = "AVERAGE_BASIS_INDICATOR_UNSPECIFIED"
    AVERAGE = "AVERAGE"
    COST = "COST"


class CoveredLotIndicator(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""Indicates covered/non-covered status of lot."""

    COVERED_LOT_INDICATOR_UNSPECIFIED = "COVERED_LOT_INDICATOR_UNSPECIFIED"
    COVERED = "COVERED"
    NON_COVERED = "NON_COVERED"


class DisallowedLossAmountTypedDict(TypedDict):
    r"""Amount of loss disallowed due to wash sales, in USD."""

    value: NotRequired[str]
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class DisallowedLossAmount(BaseModel):
    r"""Amount of loss disallowed due to wash sales, in USD."""

    value: Optional[str] = None
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class DisposalAdjustedNetAmountTypedDict(TypedDict):
    r"""Disposal proceeds for longs, cost for shorts, net of commissions and fees, adjusted for option premium paid or received."""

    value: NotRequired[str]
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class DisposalAdjustedNetAmount(BaseModel):
    r"""Disposal proceeds for longs, cost for shorts, net of commissions and fees, adjusted for option premium paid or received."""

    value: Optional[str] = None
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class DisposalAdjustedNetPerShareAmountTypedDict(TypedDict):
    r"""Disposal unit proceeds for longs, unit cost for shorts, expressed as a price using security multiplier."""

    value: NotRequired[str]
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class DisposalAdjustedNetPerShareAmount(BaseModel):
    r"""Disposal unit proceeds for longs, unit cost for shorts, expressed as a price using security multiplier."""

    value: Optional[str] = None
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class DisposalCommissionFeeAmountTypedDict(TypedDict):
    r"""Commission and fee of disposal, prorated for lot quantity."""

    value: NotRequired[str]
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class DisposalCommissionFeeAmount(BaseModel):
    r"""Commission and fee of disposal, prorated for lot quantity."""

    value: Optional[str] = None
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class DisposalExecutionPriceAmountTypedDict(TypedDict):
    r"""Execution price of disposal."""

    value: NotRequired[str]
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class DisposalExecutionPriceAmount(BaseModel):
    r"""Execution price of disposal."""

    value: Optional[str] = None
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class DisposalFxRateAmountTypedDict(TypedDict):
    r"""Disposal exchange rate, expressed as USD price of local currency (1 for USD lots)."""

    value: NotRequired[str]
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class DisposalFxRateAmount(BaseModel):
    r"""Disposal exchange rate, expressed as USD price of local currency (1 for USD lots)."""

    value: Optional[str] = None
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class DisposalMethod(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""Disposal method applied."""

    DISPOSAL_METHOD_UNSPECIFIED = "DISPOSAL_METHOD_UNSPECIFIED"
    FIFO = "FIFO"
    LIFO = "LIFO"
    HIGH_COST = "HIGH_COST"
    LOW_COST = "LOW_COST"
    MIN_TAX_TERM = "MIN_TAX_TERM"
    SPECIFIC_LOT = "SPECIFIC_LOT"


class DisposalOriginalNetAmountTypedDict(TypedDict):
    r"""Original disposal proceeds for longs, cost for shorts, net of commissions and fees, not adjusted for option premium paid or received."""

    value: NotRequired[str]
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class DisposalOriginalNetAmount(BaseModel):
    r"""Original disposal proceeds for longs, cost for shorts, net of commissions and fees, not adjusted for option premium paid or received."""

    value: Optional[str] = None
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class DisposalSettleDateTypedDict(TypedDict):
    r"""Settlement date of disposal."""

    day: NotRequired[int]
    r"""Day of a month. Must be from 1 to 31 and valid for the year and month, or 0 to specify a year by itself or a year and month where the day isn't significant."""
    month: NotRequired[int]
    r"""Month of a year. Must be from 1 to 12, or 0 to specify a year without a month and day."""
    year: NotRequired[int]
    r"""Year of the date. Must be from 1 to 9999, or 0 to specify a date without a year."""


class DisposalSettleDate(BaseModel):
    r"""Settlement date of disposal."""

    day: Optional[int] = None
    r"""Day of a month. Must be from 1 to 31 and valid for the year and month, or 0 to specify a year by itself or a year and month where the day isn't significant."""

    month: Optional[int] = None
    r"""Month of a year. Must be from 1 to 12, or 0 to specify a year without a month and day."""

    year: Optional[int] = None
    r"""Year of the date. Must be from 1 to 9999, or 0 to specify a date without a year."""


class DisposalTradeDateTypedDict(TypedDict):
    r"""Trade date of disposal."""

    day: NotRequired[int]
    r"""Day of a month. Must be from 1 to 31 and valid for the year and month, or 0 to specify a year by itself or a year and month where the day isn't significant."""
    month: NotRequired[int]
    r"""Month of a year. Must be from 1 to 12, or 0 to specify a year without a month and day."""
    year: NotRequired[int]
    r"""Year of the date. Must be from 1 to 9999, or 0 to specify a date without a year."""


class DisposalTradeDate(BaseModel):
    r"""Trade date of disposal."""

    day: Optional[int] = None
    r"""Day of a month. Must be from 1 to 31 and valid for the year and month, or 0 to specify a year by itself or a year and month where the day isn't significant."""

    month: Optional[int] = None
    r"""Month of a year. Must be from 1 to 12, or 0 to specify a year without a month and day."""

    year: Optional[int] = None
    r"""Year of the date. Must be from 1 to 9999, or 0 to specify a date without a year."""


class DripIndicator(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""Indicates acquisition through a dividend reinvestment plan."""

    DRIP_INDICATOR_UNSPECIFIED = "DRIP_INDICATOR_UNSPECIFIED"
    DRIP = "DRIP"


class GainLossAmountTypedDict(TypedDict):
    r"""Realized gain or loss (adjusted proceeds less adjusted cost), in USD."""

    value: NotRequired[str]
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class GainLossAmount(BaseModel):
    r"""Realized gain or loss (adjusted proceeds less adjusted cost), in USD."""

    value: Optional[str] = None
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class GiftIndicator(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""Indicates gifted shares."""

    GIFT_INDICATOR_UNSPECIFIED = "GIFT_INDICATOR_UNSPECIFIED"
    GIFTED = "GIFTED"


class HoldingStartDateTypedDict(TypedDict):
    r"""Holding period start date, adjusted for wash sales."""

    day: NotRequired[int]
    r"""Day of a month. Must be from 1 to 31 and valid for the year and month, or 0 to specify a year by itself or a year and month where the day isn't significant."""
    month: NotRequired[int]
    r"""Month of a year. Must be from 1 to 12, or 0 to specify a year without a month and day."""
    year: NotRequired[int]
    r"""Year of the date. Must be from 1 to 9999, or 0 to specify a date without a year."""


class HoldingStartDate(BaseModel):
    r"""Holding period start date, adjusted for wash sales."""

    day: Optional[int] = None
    r"""Day of a month. Must be from 1 to 31 and valid for the year and month, or 0 to specify a year by itself or a year and month where the day isn't significant."""

    month: Optional[int] = None
    r"""Month of a year. Must be from 1 to 12, or 0 to specify a year without a month and day."""

    year: Optional[int] = None
    r"""Year of the date. Must be from 1 to 9999, or 0 to specify a date without a year."""


class InheritedIndicator(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""Indicates inherited shares."""

    INHERITED_INDICATOR_UNSPECIFIED = "INHERITED_INDICATOR_UNSPECIFIED"
    INHERITED = "INHERITED"


class LongShortIndicator(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""Indicates whether the lot is long or short."""

    LONG_SHORT_INDICATOR_UNSPECIFIED = "LONG_SHORT_INDICATOR_UNSPECIFIED"
    LONG = "LONG"
    SHORT = "SHORT"


class MultiplierTypedDict(TypedDict):
    r"""Pricing multiplier for the asset"""

    value: NotRequired[str]
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class Multiplier(BaseModel):
    r"""Pricing multiplier for the asset"""

    value: Optional[str] = None
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class ClosedLotQuantityTypedDict(TypedDict):
    r"""lot quantity."""

    value: NotRequired[str]
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class ClosedLotQuantity(BaseModel):
    r"""lot quantity."""

    value: Optional[str] = None
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class ReplacementShareIndicator(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""Indicates if lot represents wash sale replacement shares."""

    REPLACEMENT_SHARE_INDICATOR_UNSPECIFIED = "REPLACEMENT_SHARE_INDICATOR_UNSPECIFIED"
    REPLACEMENT = "REPLACEMENT"


class Term(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""Capital gains term, adjusted for wash sales."""

    TERM_UNSPECIFIED = "TERM_UNSPECIFIED"
    LONG_TERM = "LONG_TERM"
    SHORT_TERM = "SHORT_TERM"
    SIXTY_FORTY = "SIXTY_FORTY"


class WashSaleAdjustmentAmountTypedDict(TypedDict):
    r"""Adjustment due to wash sales, in USD."""

    value: NotRequired[str]
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class WashSaleAdjustmentAmount(BaseModel):
    r"""Adjustment due to wash sales, in USD."""

    value: Optional[str] = None
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class ClosedLotTypedDict(TypedDict):
    r"""ClosedLot represents a cost basis closed lot, fully adjusted for corporate actions, return of capital, wash sales, option premium, and so on."""

    account_id: NotRequired[str]
    r"""The account ID associated with the lot."""
    acquisition_adjusted_net_amount: NotRequired[
        Nullable[AcquisitionAdjustedNetAmountTypedDict]
    ]
    r"""Acquisition cost for longs, proceeds for shorts, net of commissions and fees, adjusted for corporate actions, return of capital, liquidations, option premium paid or received, and wash sales. Closed lots are also adjusted for OID, amortized premium, accreted discount, and principal payments, where applicable."""
    acquisition_adjusted_net_per_share_amount: NotRequired[
        Nullable[AcquisitionAdjustedNetPerShareAmountTypedDict]
    ]
    r"""Acquisition unit cost for longs, unit proceeds for shorts, expressed as a price using security multiplier."""
    acquisition_commission_fee_amount: NotRequired[
        Nullable[AcquisitionCommissionFeeAmountTypedDict]
    ]
    r"""Commission and fee of original acquisition, when known, prorated for lot quantity, adjusted for corporate actions, return of capital, and liquidations."""
    acquisition_event_type: NotRequired[str]
    r"""Opening event type."""
    acquisition_execution_price_amount: NotRequired[
        Nullable[AcquisitionExecutionPriceAmountTypedDict]
    ]
    r"""Execution price of original acquisition (buy-to-open or sell-to-open), when known, adjusted for corporate actions, return of capital, and liquidations."""
    acquisition_fx_rate_amount: NotRequired[Nullable[AcquisitionFxRateAmountTypedDict]]
    r"""Acquisition exchange rate, expressed as USD price of local currency (1 for USD lots)."""
    acquisition_original_net_amount: NotRequired[
        Nullable[AcquisitionOriginalNetAmountTypedDict]
    ]
    r"""Original acquisition cost for longs, proceeds for shorts, net of commissions and fees."""
    acquisition_original_trade_date: NotRequired[
        Nullable[AcquisitionOriginalTradeDateTypedDict]
    ]
    r"""Trade date of original buy-to-open or sell-to-open transaction."""
    acquisition_transaction_id: NotRequired[str]
    r"""Opening transaction identifier."""
    acquisition_true_zero_indicator: NotRequired[AcquisitionTrueZeroIndicator]
    r"""Indicates whether the acquisition was a true-zero acquisition."""
    asset_id: NotRequired[str]
    r"""security identifier for the asset"""
    average_basis_indicator: NotRequired[AverageBasisIndicator]
    r"""Indicates average basis acquisition."""
    closed_lot_id: NotRequired[str]
    r"""Globally unique closed lot identifier"""
    covered_lot_indicator: NotRequired[CoveredLotIndicator]
    r"""Indicates covered/non-covered status of lot."""
    currency_code: NotRequired[str]
    r"""currency code for the cost basis lot"""
    cusip: NotRequired[str]
    r"""security cusip for the asset"""
    disallowed_loss_amount: NotRequired[Nullable[DisallowedLossAmountTypedDict]]
    r"""Amount of loss disallowed due to wash sales, in USD."""
    disposal_adjusted_net_amount: NotRequired[
        Nullable[DisposalAdjustedNetAmountTypedDict]
    ]
    r"""Disposal proceeds for longs, cost for shorts, net of commissions and fees, adjusted for option premium paid or received."""
    disposal_adjusted_net_per_share_amount: NotRequired[
        Nullable[DisposalAdjustedNetPerShareAmountTypedDict]
    ]
    r"""Disposal unit proceeds for longs, unit cost for shorts, expressed as a price using security multiplier."""
    disposal_commission_fee_amount: NotRequired[
        Nullable[DisposalCommissionFeeAmountTypedDict]
    ]
    r"""Commission and fee of disposal, prorated for lot quantity."""
    disposal_event_type: NotRequired[str]
    r"""Closing event type"""
    disposal_execution_price_amount: NotRequired[
        Nullable[DisposalExecutionPriceAmountTypedDict]
    ]
    r"""Execution price of disposal."""
    disposal_fx_rate_amount: NotRequired[Nullable[DisposalFxRateAmountTypedDict]]
    r"""Disposal exchange rate, expressed as USD price of local currency (1 for USD lots)."""
    disposal_method: NotRequired[DisposalMethod]
    r"""Disposal method applied."""
    disposal_original_net_amount: NotRequired[
        Nullable[DisposalOriginalNetAmountTypedDict]
    ]
    r"""Original disposal proceeds for longs, cost for shorts, net of commissions and fees, not adjusted for option premium paid or received."""
    disposal_settle_date: NotRequired[Nullable[DisposalSettleDateTypedDict]]
    r"""Settlement date of disposal."""
    disposal_trade_date: NotRequired[Nullable[DisposalTradeDateTypedDict]]
    r"""Trade date of disposal."""
    disposal_transaction_id: NotRequired[str]
    r"""Closing transaction identifier"""
    drip_indicator: NotRequired[DripIndicator]
    r"""Indicates acquisition through a dividend reinvestment plan."""
    gain_loss_amount: NotRequired[Nullable[GainLossAmountTypedDict]]
    r"""Realized gain or loss (adjusted proceeds less adjusted cost), in USD."""
    gift_indicator: NotRequired[GiftIndicator]
    r"""Indicates gifted shares."""
    holding_start_date: NotRequired[Nullable[HoldingStartDateTypedDict]]
    r"""Holding period start date, adjusted for wash sales."""
    inherited_indicator: NotRequired[InheritedIndicator]
    r"""Indicates inherited shares."""
    long_short_indicator: NotRequired[LongShortIndicator]
    r"""Indicates whether the lot is long or short."""
    multiplier: NotRequired[Nullable[MultiplierTypedDict]]
    r"""Pricing multiplier for the asset"""
    name: NotRequired[str]
    r"""The name field Format: accounts/{account}/closedLots/{closed_lot}"""
    open_lot_id: NotRequired[str]
    r"""Globally unique open lot identifier."""
    quantity: NotRequired[Nullable[ClosedLotQuantityTypedDict]]
    r"""lot quantity."""
    replacement_share_indicator: NotRequired[ReplacementShareIndicator]
    r"""Indicates if lot represents wash sale replacement shares."""
    symbol: NotRequired[str]
    r"""security symbol for the asset"""
    term: NotRequired[Term]
    r"""Capital gains term, adjusted for wash sales."""
    wash_sale_adjustment_amount: NotRequired[
        Nullable[WashSaleAdjustmentAmountTypedDict]
    ]
    r"""Adjustment due to wash sales, in USD."""


class ClosedLot(BaseModel):
    r"""ClosedLot represents a cost basis closed lot, fully adjusted for corporate actions, return of capital, wash sales, option premium, and so on."""

    account_id: Optional[str] = None
    r"""The account ID associated with the lot."""

    acquisition_adjusted_net_amount: OptionalNullable[AcquisitionAdjustedNetAmount] = (
        UNSET
    )
    r"""Acquisition cost for longs, proceeds for shorts, net of commissions and fees, adjusted for corporate actions, return of capital, liquidations, option premium paid or received, and wash sales. Closed lots are also adjusted for OID, amortized premium, accreted discount, and principal payments, where applicable."""

    acquisition_adjusted_net_per_share_amount: OptionalNullable[
        AcquisitionAdjustedNetPerShareAmount
    ] = UNSET
    r"""Acquisition unit cost for longs, unit proceeds for shorts, expressed as a price using security multiplier."""

    acquisition_commission_fee_amount: OptionalNullable[
        AcquisitionCommissionFeeAmount
    ] = UNSET
    r"""Commission and fee of original acquisition, when known, prorated for lot quantity, adjusted for corporate actions, return of capital, and liquidations."""

    acquisition_event_type: Optional[str] = None
    r"""Opening event type."""

    acquisition_execution_price_amount: OptionalNullable[
        AcquisitionExecutionPriceAmount
    ] = UNSET
    r"""Execution price of original acquisition (buy-to-open or sell-to-open), when known, adjusted for corporate actions, return of capital, and liquidations."""

    acquisition_fx_rate_amount: OptionalNullable[AcquisitionFxRateAmount] = UNSET
    r"""Acquisition exchange rate, expressed as USD price of local currency (1 for USD lots)."""

    acquisition_original_net_amount: OptionalNullable[AcquisitionOriginalNetAmount] = (
        UNSET
    )
    r"""Original acquisition cost for longs, proceeds for shorts, net of commissions and fees."""

    acquisition_original_trade_date: OptionalNullable[AcquisitionOriginalTradeDate] = (
        UNSET
    )
    r"""Trade date of original buy-to-open or sell-to-open transaction."""

    acquisition_transaction_id: Optional[str] = None
    r"""Opening transaction identifier."""

    acquisition_true_zero_indicator: Annotated[
        Optional[AcquisitionTrueZeroIndicator],
        PlainValidator(validate_open_enum(False)),
    ] = None
    r"""Indicates whether the acquisition was a true-zero acquisition."""

    asset_id: Optional[str] = None
    r"""security identifier for the asset"""

    average_basis_indicator: Annotated[
        Optional[AverageBasisIndicator], PlainValidator(validate_open_enum(False))
    ] = None
    r"""Indicates average basis acquisition."""

    closed_lot_id: Optional[str] = None
    r"""Globally unique closed lot identifier"""

    covered_lot_indicator: Annotated[
        Optional[CoveredLotIndicator], PlainValidator(validate_open_enum(False))
    ] = None
    r"""Indicates covered/non-covered status of lot."""

    currency_code: Optional[str] = None
    r"""currency code for the cost basis lot"""

    cusip: Optional[str] = None
    r"""security cusip for the asset"""

    disallowed_loss_amount: OptionalNullable[DisallowedLossAmount] = UNSET
    r"""Amount of loss disallowed due to wash sales, in USD."""

    disposal_adjusted_net_amount: OptionalNullable[DisposalAdjustedNetAmount] = UNSET
    r"""Disposal proceeds for longs, cost for shorts, net of commissions and fees, adjusted for option premium paid or received."""

    disposal_adjusted_net_per_share_amount: OptionalNullable[
        DisposalAdjustedNetPerShareAmount
    ] = UNSET
    r"""Disposal unit proceeds for longs, unit cost for shorts, expressed as a price using security multiplier."""

    disposal_commission_fee_amount: OptionalNullable[DisposalCommissionFeeAmount] = (
        UNSET
    )
    r"""Commission and fee of disposal, prorated for lot quantity."""

    disposal_event_type: Optional[str] = None
    r"""Closing event type"""

    disposal_execution_price_amount: OptionalNullable[DisposalExecutionPriceAmount] = (
        UNSET
    )
    r"""Execution price of disposal."""

    disposal_fx_rate_amount: OptionalNullable[DisposalFxRateAmount] = UNSET
    r"""Disposal exchange rate, expressed as USD price of local currency (1 for USD lots)."""

    disposal_method: Annotated[
        Optional[DisposalMethod], PlainValidator(validate_open_enum(False))
    ] = None
    r"""Disposal method applied."""

    disposal_original_net_amount: OptionalNullable[DisposalOriginalNetAmount] = UNSET
    r"""Original disposal proceeds for longs, cost for shorts, net of commissions and fees, not adjusted for option premium paid or received."""

    disposal_settle_date: OptionalNullable[DisposalSettleDate] = UNSET
    r"""Settlement date of disposal."""

    disposal_trade_date: OptionalNullable[DisposalTradeDate] = UNSET
    r"""Trade date of disposal."""

    disposal_transaction_id: Optional[str] = None
    r"""Closing transaction identifier"""

    drip_indicator: Annotated[
        Optional[DripIndicator], PlainValidator(validate_open_enum(False))
    ] = None
    r"""Indicates acquisition through a dividend reinvestment plan."""

    gain_loss_amount: OptionalNullable[GainLossAmount] = UNSET
    r"""Realized gain or loss (adjusted proceeds less adjusted cost), in USD."""

    gift_indicator: Annotated[
        Optional[GiftIndicator], PlainValidator(validate_open_enum(False))
    ] = None
    r"""Indicates gifted shares."""

    holding_start_date: OptionalNullable[HoldingStartDate] = UNSET
    r"""Holding period start date, adjusted for wash sales."""

    inherited_indicator: Annotated[
        Optional[InheritedIndicator], PlainValidator(validate_open_enum(False))
    ] = None
    r"""Indicates inherited shares."""

    long_short_indicator: Annotated[
        Optional[LongShortIndicator], PlainValidator(validate_open_enum(False))
    ] = None
    r"""Indicates whether the lot is long or short."""

    multiplier: OptionalNullable[Multiplier] = UNSET
    r"""Pricing multiplier for the asset"""

    name: Optional[str] = None
    r"""The name field Format: accounts/{account}/closedLots/{closed_lot}"""

    open_lot_id: Optional[str] = None
    r"""Globally unique open lot identifier."""

    quantity: OptionalNullable[ClosedLotQuantity] = UNSET
    r"""lot quantity."""

    replacement_share_indicator: Annotated[
        Optional[ReplacementShareIndicator], PlainValidator(validate_open_enum(False))
    ] = None
    r"""Indicates if lot represents wash sale replacement shares."""

    symbol: Optional[str] = None
    r"""security symbol for the asset"""

    term: Annotated[Optional[Term], PlainValidator(validate_open_enum(False))] = None
    r"""Capital gains term, adjusted for wash sales."""

    wash_sale_adjustment_amount: OptionalNullable[WashSaleAdjustmentAmount] = UNSET
    r"""Adjustment due to wash sales, in USD."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = [
            "account_id",
            "acquisition_adjusted_net_amount",
            "acquisition_adjusted_net_per_share_amount",
            "acquisition_commission_fee_amount",
            "acquisition_event_type",
            "acquisition_execution_price_amount",
            "acquisition_fx_rate_amount",
            "acquisition_original_net_amount",
            "acquisition_original_trade_date",
            "acquisition_transaction_id",
            "acquisition_true_zero_indicator",
            "asset_id",
            "average_basis_indicator",
            "closed_lot_id",
            "covered_lot_indicator",
            "currency_code",
            "cusip",
            "disallowed_loss_amount",
            "disposal_adjusted_net_amount",
            "disposal_adjusted_net_per_share_amount",
            "disposal_commission_fee_amount",
            "disposal_event_type",
            "disposal_execution_price_amount",
            "disposal_fx_rate_amount",
            "disposal_method",
            "disposal_original_net_amount",
            "disposal_settle_date",
            "disposal_trade_date",
            "disposal_transaction_id",
            "drip_indicator",
            "gain_loss_amount",
            "gift_indicator",
            "holding_start_date",
            "inherited_indicator",
            "long_short_indicator",
            "multiplier",
            "name",
            "open_lot_id",
            "quantity",
            "replacement_share_indicator",
            "symbol",
            "term",
            "wash_sale_adjustment_amount",
        ]
        nullable_fields = [
            "acquisition_adjusted_net_amount",
            "acquisition_adjusted_net_per_share_amount",
            "acquisition_commission_fee_amount",
            "acquisition_execution_price_amount",
            "acquisition_fx_rate_amount",
            "acquisition_original_net_amount",
            "acquisition_original_trade_date",
            "disallowed_loss_amount",
            "disposal_adjusted_net_amount",
            "disposal_adjusted_net_per_share_amount",
            "disposal_commission_fee_amount",
            "disposal_execution_price_amount",
            "disposal_fx_rate_amount",
            "disposal_original_net_amount",
            "disposal_settle_date",
            "disposal_trade_date",
            "gain_loss_amount",
            "holding_start_date",
            "multiplier",
            "quantity",
            "wash_sale_adjustment_amount",
        ]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
