"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .alternativeorder import AlternativeOrder, AlternativeOrderTypedDict
from ascend_sdk.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class ListAlternativeOrdersResponseTypedDict(TypedDict):
    r"""Response to list Alternative Orders."""

    alternative_orders: NotRequired[List[AlternativeOrderTypedDict]]
    r"""The alternative investment orders associated with the specified account."""
    next_page_token: NotRequired[str]
    r"""A token that can be sent as the `page_token` query param value to retrieve the next page, when pagination is needed. If this field is omitted, there are no subsequent pages."""


class ListAlternativeOrdersResponse(BaseModel):
    r"""Response to list Alternative Orders."""

    alternative_orders: Optional[List[AlternativeOrder]] = None
    r"""The alternative investment orders associated with the specified account."""

    next_page_token: Optional[str] = None
    r"""A token that can be sent as the `page_token` query param value to retrieve the next page, when pagination is needed. If this field is omitted, there are no subsequent pages."""
