"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .preipocompanyfundinground import (
    PreIpoCompanyFundingRound,
    PreIpoCompanyFundingRoundTypedDict,
)
from ascend_sdk.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class ListPreIpoCompanyFundingRoundsResponseTypedDict(TypedDict):
    r"""Response for listing Pre IPO Company Funding Rounds."""

    next_page_token: NotRequired[str]
    r"""A token to retrieve the next page of results. Pass this value in the `page_token` field of a subsequent `ListPreIpoCompanyFundingRoundsRequest` to retrieve the next page of results. If this field is omitted, there are no subsequent pages."""
    pre_ipo_company_funding_rounds: NotRequired[
        List[PreIpoCompanyFundingRoundTypedDict]
    ]
    r"""The Pre IPO Company Funding Rounds."""


class ListPreIpoCompanyFundingRoundsResponse(BaseModel):
    r"""Response for listing Pre IPO Company Funding Rounds."""

    next_page_token: Optional[str] = None
    r"""A token to retrieve the next page of results. Pass this value in the `page_token` field of a subsequent `ListPreIpoCompanyFundingRoundsRequest` to retrieve the next page of results. If this field is omitted, there are no subsequent pages."""

    pre_ipo_company_funding_rounds: Optional[List[PreIpoCompanyFundingRound]] = None
    r"""The Pre IPO Company Funding Rounds."""
