"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .preipocompanynewsevent import (
    PreIpoCompanyNewsEvent,
    PreIpoCompanyNewsEventTypedDict,
)
from ascend_sdk.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class ListPreIpoCompanyNewsEventsResponseTypedDict(TypedDict):
    r"""Response for listing Pre IPO Company News Events."""

    next_page_token: NotRequired[str]
    r"""A token to retrieve the next page of results. Pass this value in the `page_token` field of a subsequent `ListPreIpoCompanyNewsEventsRequest` to retrieve the next page of results. If this field is omitted, there are no subsequent pages."""
    pre_ipo_company_news_events: NotRequired[List[PreIpoCompanyNewsEventTypedDict]]
    r"""The Pre IPO Company News Events."""


class ListPreIpoCompanyNewsEventsResponse(BaseModel):
    r"""Response for listing Pre IPO Company News Events."""

    next_page_token: Optional[str] = None
    r"""A token to retrieve the next page of results. Pass this value in the `page_token` field of a subsequent `ListPreIpoCompanyNewsEventsRequest` to retrieve the next page of results. If this field is omitted, there are no subsequent pages."""

    pre_ipo_company_news_events: Optional[List[PreIpoCompanyNewsEvent]] = None
    r"""The Pre IPO Company News Events."""
