"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .alternativeinvestmentdocument import (
    AlternativeInvestmentDocument,
    AlternativeInvestmentDocumentTypedDict,
)
from ascend_sdk.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class ListAlternativeInvestmentDocumentsResponseTypedDict(TypedDict):
    r"""Response to list alternative investment documents."""

    alternative_investment_documents: NotRequired[
        List[AlternativeInvestmentDocumentTypedDict]
    ]
    r"""The array of investment documents for the asset."""
    next_page_token: NotRequired[str]
    r"""A token that can be sent as the `page_token` query param value to retrieve the next page, when pagination is needed.  If this field is omitted, there are no subsequent pages."""


class ListAlternativeInvestmentDocumentsResponse(BaseModel):
    r"""Response to list alternative investment documents."""

    alternative_investment_documents: Optional[List[AlternativeInvestmentDocument]] = (
        None
    )
    r"""The array of investment documents for the asset."""

    next_page_token: Optional[str] = None
    r"""A token that can be sent as the `page_token` query param value to retrieve the next page, when pagination is needed.  If this field is omitted, there are no subsequent pages."""
