"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .note import Note, NoteTypedDict
from ascend_sdk.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class ListNotesResponseTypedDict(TypedDict):
    r"""The response for listing Notes."""

    next_page_token: NotRequired[str]
    r"""A token to retrieve the next page of results. Pass this value in the `page_token` field in the subsequent call to `ListNotes`."""
    notes: NotRequired[List[NoteTypedDict]]
    r"""The notes for the specified parent."""


class ListNotesResponse(BaseModel):
    r"""The response for listing Notes."""

    next_page_token: Optional[str] = None
    r"""A token to retrieve the next page of results. Pass this value in the `page_token` field in the subsequent call to `ListNotes`."""

    notes: Optional[List[Note]] = None
    r"""The notes for the specified parent."""
