"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .preipocompanyresearchdocument import (
    PreIpoCompanyResearchDocument,
    PreIpoCompanyResearchDocumentTypedDict,
)
from ascend_sdk.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class ListPreIpoCompanyResearchDocumentsResponseTypedDict(TypedDict):
    r"""Response for listing Pre IPO Company Research Documents."""

    next_page_token: NotRequired[str]
    r"""A token to retrieve the next page of results. Pass this value in the `page_token` field of a subsequent `ListPreIpoCompanyResearchDocumentsRequest` to retrieve the next page of results. If this field is omitted, there are no subsequent pages."""
    pre_ipo_company_research_documents: NotRequired[
        List[PreIpoCompanyResearchDocumentTypedDict]
    ]
    r"""The Pre IPO Company Research Documents."""


class ListPreIpoCompanyResearchDocumentsResponse(BaseModel):
    r"""Response for listing Pre IPO Company Research Documents."""

    next_page_token: Optional[str] = None
    r"""A token to retrieve the next page of results. Pass this value in the `page_token` field of a subsequent `ListPreIpoCompanyResearchDocumentsRequest` to retrieve the next page of results. If this field is omitted, there are no subsequent pages."""

    pre_ipo_company_research_documents: Optional[
        List[PreIpoCompanyResearchDocument]
    ] = None
    r"""The Pre IPO Company Research Documents."""
