"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from ascend_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from datetime import datetime
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class NoteTypedDict(TypedDict):
    r"""A note attached to an account."""

    content: NotRequired[str]
    r"""The content of the note."""
    create_time: NotRequired[Nullable[datetime]]
    r"""The time the note was created."""
    creator: NotRequired[str]
    r"""The ID of the user who created the note."""
    name: NotRequired[str]
    r"""The resource name of the note. Format: accounts/{account}/notes/{note}"""
    note_id: NotRequired[str]
    r"""A system-generated unique identifier for the note."""


class Note(BaseModel):
    r"""A note attached to an account."""

    content: Optional[str] = None
    r"""The content of the note."""

    create_time: OptionalNullable[datetime] = UNSET
    r"""The time the note was created."""

    creator: Optional[str] = None
    r"""The ID of the user who created the note."""

    name: Optional[str] = None
    r"""The resource name of the note. Format: accounts/{account}/notes/{note}"""

    note_id: Optional[str] = None
    r"""A system-generated unique identifier for the note."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["content", "create_time", "creator", "name", "note_id"]
        nullable_fields = ["create_time"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
