"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from ascend_sdk import utils
from ascend_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from ascend_sdk.utils import validate_open_enum
from enum import Enum
from pydantic import model_serializer
from pydantic.functional_validators import PlainValidator
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class OpenLotAcquisitionAdjustedNetAmountTypedDict(TypedDict):
    r"""Acquisition cost for longs, proceeds for shorts, net of commissions and fees, adjusted for corporate actions, return of capital, liquidations, option premium paid or received, and wash sales."""

    value: NotRequired[str]
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class OpenLotAcquisitionAdjustedNetAmount(BaseModel):
    r"""Acquisition cost for longs, proceeds for shorts, net of commissions and fees, adjusted for corporate actions, return of capital, liquidations, option premium paid or received, and wash sales."""

    value: Optional[str] = None
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class OpenLotAcquisitionAdjustedNetPerShareAmountTypedDict(TypedDict):
    r"""Acquisition unit cost for longs, unit proceeds for shorts, expressed as a price using security multiplier."""

    value: NotRequired[str]
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class OpenLotAcquisitionAdjustedNetPerShareAmount(BaseModel):
    r"""Acquisition unit cost for longs, unit proceeds for shorts, expressed as a price using security multiplier."""

    value: Optional[str] = None
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class OpenLotAcquisitionCommissionFeeAmountTypedDict(TypedDict):
    r"""Commission and fee of original acquisition, when known, prorated for lot quantity, adjusted for corporate actions, return of capital, and liquidations."""

    value: NotRequired[str]
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class OpenLotAcquisitionCommissionFeeAmount(BaseModel):
    r"""Commission and fee of original acquisition, when known, prorated for lot quantity, adjusted for corporate actions, return of capital, and liquidations."""

    value: Optional[str] = None
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class OpenLotAcquisitionExecutionPriceAmountTypedDict(TypedDict):
    r"""Execution price of original acquisition (buy-to-open or sell-to-open), when known, adjusted for corporate actions, return of capital, and liquidations."""

    value: NotRequired[str]
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class OpenLotAcquisitionExecutionPriceAmount(BaseModel):
    r"""Execution price of original acquisition (buy-to-open or sell-to-open), when known, adjusted for corporate actions, return of capital, and liquidations."""

    value: Optional[str] = None
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class OpenLotAcquisitionFxRateAmountTypedDict(TypedDict):
    r"""Acquisition exchange rate, expressed as USD price of local currency (1 for USD lots)."""

    value: NotRequired[str]
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class OpenLotAcquisitionFxRateAmount(BaseModel):
    r"""Acquisition exchange rate, expressed as USD price of local currency (1 for USD lots)."""

    value: Optional[str] = None
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class OpenLotAcquisitionOriginalNetAmountTypedDict(TypedDict):
    r"""Original acquisition cost for longs, proceeds for shorts, net of commissions and fees."""

    value: NotRequired[str]
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class OpenLotAcquisitionOriginalNetAmount(BaseModel):
    r"""Original acquisition cost for longs, proceeds for shorts, net of commissions and fees."""

    value: Optional[str] = None
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class OpenLotAcquisitionOriginalTradeDateTypedDict(TypedDict):
    r"""Trade date of original buy-to-open or sell-to-open transaction."""

    day: NotRequired[int]
    r"""Day of a month. Must be from 1 to 31 and valid for the year and month, or 0 to specify a year by itself or a year and month where the day isn't significant."""
    month: NotRequired[int]
    r"""Month of a year. Must be from 1 to 12, or 0 to specify a year without a month and day."""
    year: NotRequired[int]
    r"""Year of the date. Must be from 1 to 9999, or 0 to specify a date without a year."""


class OpenLotAcquisitionOriginalTradeDate(BaseModel):
    r"""Trade date of original buy-to-open or sell-to-open transaction."""

    day: Optional[int] = None
    r"""Day of a month. Must be from 1 to 31 and valid for the year and month, or 0 to specify a year by itself or a year and month where the day isn't significant."""

    month: Optional[int] = None
    r"""Month of a year. Must be from 1 to 12, or 0 to specify a year without a month and day."""

    year: Optional[int] = None
    r"""Year of the date. Must be from 1 to 9999, or 0 to specify a date without a year."""


class OpenLotAcquisitionTrueZeroIndicator(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""Indicates whether the acquisition was a true-zero acquisition."""

    ACQUISITION_TRUE_ZERO_INDICATOR_UNSPECIFIED = (
        "ACQUISITION_TRUE_ZERO_INDICATOR_UNSPECIFIED"
    )
    ZERO_ACQUISITION = "ZERO_ACQUISITION"


class OpenLotAverageBasisIndicator(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""Indicates average basis acquisition."""

    AVERAGE_BASIS_INDICATOR_UNSPECIFIED = "AVERAGE_BASIS_INDICATOR_UNSPECIFIED"
    AVERAGE = "AVERAGE"
    COST = "COST"


class OpenLotCoveredLotIndicator(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""Indicates covered/non-covered status of lot."""

    COVERED_LOT_INDICATOR_UNSPECIFIED = "COVERED_LOT_INDICATOR_UNSPECIFIED"
    COVERED = "COVERED"
    NON_COVERED = "NON_COVERED"


class OpenLotDripIndicator(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""Indicates acquisition through a dividend reinvestment plan."""

    DRIP_INDICATOR_UNSPECIFIED = "DRIP_INDICATOR_UNSPECIFIED"
    DRIP = "DRIP"


class OpenLotGiftIndicator(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""Indicates gifted shares."""

    GIFT_INDICATOR_UNSPECIFIED = "GIFT_INDICATOR_UNSPECIFIED"
    GIFTED = "GIFTED"


class OpenLotHoldingStartDateTypedDict(TypedDict):
    r"""Holding period start date, adjusted for wash sales."""

    day: NotRequired[int]
    r"""Day of a month. Must be from 1 to 31 and valid for the year and month, or 0 to specify a year by itself or a year and month where the day isn't significant."""
    month: NotRequired[int]
    r"""Month of a year. Must be from 1 to 12, or 0 to specify a year without a month and day."""
    year: NotRequired[int]
    r"""Year of the date. Must be from 1 to 9999, or 0 to specify a date without a year."""


class OpenLotHoldingStartDate(BaseModel):
    r"""Holding period start date, adjusted for wash sales."""

    day: Optional[int] = None
    r"""Day of a month. Must be from 1 to 31 and valid for the year and month, or 0 to specify a year by itself or a year and month where the day isn't significant."""

    month: Optional[int] = None
    r"""Month of a year. Must be from 1 to 12, or 0 to specify a year without a month and day."""

    year: Optional[int] = None
    r"""Year of the date. Must be from 1 to 9999, or 0 to specify a date without a year."""


class OpenLotInheritedIndicator(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""Indicates inherited shares."""

    INHERITED_INDICATOR_UNSPECIFIED = "INHERITED_INDICATOR_UNSPECIFIED"
    INHERITED = "INHERITED"


class OpenLotLongShortIndicator(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""Indicates whether the lot is long or short."""

    LONG_SHORT_INDICATOR_UNSPECIFIED = "LONG_SHORT_INDICATOR_UNSPECIFIED"
    LONG = "LONG"
    SHORT = "SHORT"


class OpenLotMultiplierTypedDict(TypedDict):
    r"""Pricing multiplier for the asset"""

    value: NotRequired[str]
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class OpenLotMultiplier(BaseModel):
    r"""Pricing multiplier for the asset"""

    value: Optional[str] = None
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class OpenLotQuantityTypedDict(TypedDict):
    r"""lot quantity."""

    value: NotRequired[str]
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class OpenLotQuantity(BaseModel):
    r"""lot quantity."""

    value: Optional[str] = None
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class OpenLotReplacementShareIndicator(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""Indicates if lot represents wash sale replacement shares."""

    REPLACEMENT_SHARE_INDICATOR_UNSPECIFIED = "REPLACEMENT_SHARE_INDICATOR_UNSPECIFIED"
    REPLACEMENT = "REPLACEMENT"


class OpenLotTerm(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""Capital gains term, adjusted for wash sales."""

    TERM_UNSPECIFIED = "TERM_UNSPECIFIED"
    LONG_TERM = "LONG_TERM"
    SHORT_TERM = "SHORT_TERM"
    SIXTY_FORTY = "SIXTY_FORTY"


class OpenLotWashSaleAdjustmentAmountTypedDict(TypedDict):
    r"""Adjustment due to wash sales, in USD. Note: For open short lots, wash sale adjustment is presented as a negative value, reducing proceeds for correct unrealized gain loss calculation -- once closed, this will appear as a positive value, indicating addition to cost."""

    value: NotRequired[str]
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class OpenLotWashSaleAdjustmentAmount(BaseModel):
    r"""Adjustment due to wash sales, in USD. Note: For open short lots, wash sale adjustment is presented as a negative value, reducing proceeds for correct unrealized gain loss calculation -- once closed, this will appear as a positive value, indicating addition to cost."""

    value: Optional[str] = None
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class OpenLotTypedDict(TypedDict):
    r"""OpenLot represents a cost basis open lot, fully adjusted for corporate actions, return of capital, wash sales, option premium, and so on."""

    account_id: NotRequired[str]
    r"""The account ID associated with the lot."""
    acquisition_adjusted_net_amount: NotRequired[
        Nullable[OpenLotAcquisitionAdjustedNetAmountTypedDict]
    ]
    r"""Acquisition cost for longs, proceeds for shorts, net of commissions and fees, adjusted for corporate actions, return of capital, liquidations, option premium paid or received, and wash sales."""
    acquisition_adjusted_net_per_share_amount: NotRequired[
        Nullable[OpenLotAcquisitionAdjustedNetPerShareAmountTypedDict]
    ]
    r"""Acquisition unit cost for longs, unit proceeds for shorts, expressed as a price using security multiplier."""
    acquisition_commission_fee_amount: NotRequired[
        Nullable[OpenLotAcquisitionCommissionFeeAmountTypedDict]
    ]
    r"""Commission and fee of original acquisition, when known, prorated for lot quantity, adjusted for corporate actions, return of capital, and liquidations."""
    acquisition_event_type: NotRequired[str]
    r"""Opening event type."""
    acquisition_execution_price_amount: NotRequired[
        Nullable[OpenLotAcquisitionExecutionPriceAmountTypedDict]
    ]
    r"""Execution price of original acquisition (buy-to-open or sell-to-open), when known, adjusted for corporate actions, return of capital, and liquidations."""
    acquisition_fx_rate_amount: NotRequired[
        Nullable[OpenLotAcquisitionFxRateAmountTypedDict]
    ]
    r"""Acquisition exchange rate, expressed as USD price of local currency (1 for USD lots)."""
    acquisition_original_net_amount: NotRequired[
        Nullable[OpenLotAcquisitionOriginalNetAmountTypedDict]
    ]
    r"""Original acquisition cost for longs, proceeds for shorts, net of commissions and fees."""
    acquisition_original_trade_date: NotRequired[
        Nullable[OpenLotAcquisitionOriginalTradeDateTypedDict]
    ]
    r"""Trade date of original buy-to-open or sell-to-open transaction."""
    acquisition_transaction_id: NotRequired[str]
    r"""Opening transaction identifier."""
    acquisition_true_zero_indicator: NotRequired[OpenLotAcquisitionTrueZeroIndicator]
    r"""Indicates whether the acquisition was a true-zero acquisition."""
    asset_id: NotRequired[str]
    r"""security identifier for the asset"""
    average_basis_indicator: NotRequired[OpenLotAverageBasisIndicator]
    r"""Indicates average basis acquisition."""
    covered_lot_indicator: NotRequired[OpenLotCoveredLotIndicator]
    r"""Indicates covered/non-covered status of lot."""
    currency_code: NotRequired[str]
    r"""currency code for the cost basis lot"""
    cusip: NotRequired[str]
    r"""security cusip for the asset"""
    drip_indicator: NotRequired[OpenLotDripIndicator]
    r"""Indicates acquisition through a dividend reinvestment plan."""
    gift_indicator: NotRequired[OpenLotGiftIndicator]
    r"""Indicates gifted shares."""
    holding_start_date: NotRequired[Nullable[OpenLotHoldingStartDateTypedDict]]
    r"""Holding period start date, adjusted for wash sales."""
    inherited_indicator: NotRequired[OpenLotInheritedIndicator]
    r"""Indicates inherited shares."""
    long_short_indicator: NotRequired[OpenLotLongShortIndicator]
    r"""Indicates whether the lot is long or short."""
    multiplier: NotRequired[Nullable[OpenLotMultiplierTypedDict]]
    r"""Pricing multiplier for the asset"""
    name: NotRequired[str]
    r"""The name field Format: accounts/{account}/openLots/{open_lot}"""
    open_lot_id: NotRequired[str]
    r"""Globally unique open lot identifier."""
    quantity: NotRequired[Nullable[OpenLotQuantityTypedDict]]
    r"""lot quantity."""
    replacement_share_indicator: NotRequired[OpenLotReplacementShareIndicator]
    r"""Indicates if lot represents wash sale replacement shares."""
    symbol: NotRequired[str]
    r"""security symbol for the asset"""
    term: NotRequired[OpenLotTerm]
    r"""Capital gains term, adjusted for wash sales."""
    wash_sale_adjustment_amount: NotRequired[
        Nullable[OpenLotWashSaleAdjustmentAmountTypedDict]
    ]
    r"""Adjustment due to wash sales, in USD. Note: For open short lots, wash sale adjustment is presented as a negative value, reducing proceeds for correct unrealized gain loss calculation -- once closed, this will appear as a positive value, indicating addition to cost."""


class OpenLot(BaseModel):
    r"""OpenLot represents a cost basis open lot, fully adjusted for corporate actions, return of capital, wash sales, option premium, and so on."""

    account_id: Optional[str] = None
    r"""The account ID associated with the lot."""

    acquisition_adjusted_net_amount: OptionalNullable[
        OpenLotAcquisitionAdjustedNetAmount
    ] = UNSET
    r"""Acquisition cost for longs, proceeds for shorts, net of commissions and fees, adjusted for corporate actions, return of capital, liquidations, option premium paid or received, and wash sales."""

    acquisition_adjusted_net_per_share_amount: OptionalNullable[
        OpenLotAcquisitionAdjustedNetPerShareAmount
    ] = UNSET
    r"""Acquisition unit cost for longs, unit proceeds for shorts, expressed as a price using security multiplier."""

    acquisition_commission_fee_amount: OptionalNullable[
        OpenLotAcquisitionCommissionFeeAmount
    ] = UNSET
    r"""Commission and fee of original acquisition, when known, prorated for lot quantity, adjusted for corporate actions, return of capital, and liquidations."""

    acquisition_event_type: Optional[str] = None
    r"""Opening event type."""

    acquisition_execution_price_amount: OptionalNullable[
        OpenLotAcquisitionExecutionPriceAmount
    ] = UNSET
    r"""Execution price of original acquisition (buy-to-open or sell-to-open), when known, adjusted for corporate actions, return of capital, and liquidations."""

    acquisition_fx_rate_amount: OptionalNullable[OpenLotAcquisitionFxRateAmount] = UNSET
    r"""Acquisition exchange rate, expressed as USD price of local currency (1 for USD lots)."""

    acquisition_original_net_amount: OptionalNullable[
        OpenLotAcquisitionOriginalNetAmount
    ] = UNSET
    r"""Original acquisition cost for longs, proceeds for shorts, net of commissions and fees."""

    acquisition_original_trade_date: OptionalNullable[
        OpenLotAcquisitionOriginalTradeDate
    ] = UNSET
    r"""Trade date of original buy-to-open or sell-to-open transaction."""

    acquisition_transaction_id: Optional[str] = None
    r"""Opening transaction identifier."""

    acquisition_true_zero_indicator: Annotated[
        Optional[OpenLotAcquisitionTrueZeroIndicator],
        PlainValidator(validate_open_enum(False)),
    ] = None
    r"""Indicates whether the acquisition was a true-zero acquisition."""

    asset_id: Optional[str] = None
    r"""security identifier for the asset"""

    average_basis_indicator: Annotated[
        Optional[OpenLotAverageBasisIndicator],
        PlainValidator(validate_open_enum(False)),
    ] = None
    r"""Indicates average basis acquisition."""

    covered_lot_indicator: Annotated[
        Optional[OpenLotCoveredLotIndicator], PlainValidator(validate_open_enum(False))
    ] = None
    r"""Indicates covered/non-covered status of lot."""

    currency_code: Optional[str] = None
    r"""currency code for the cost basis lot"""

    cusip: Optional[str] = None
    r"""security cusip for the asset"""

    drip_indicator: Annotated[
        Optional[OpenLotDripIndicator], PlainValidator(validate_open_enum(False))
    ] = None
    r"""Indicates acquisition through a dividend reinvestment plan."""

    gift_indicator: Annotated[
        Optional[OpenLotGiftIndicator], PlainValidator(validate_open_enum(False))
    ] = None
    r"""Indicates gifted shares."""

    holding_start_date: OptionalNullable[OpenLotHoldingStartDate] = UNSET
    r"""Holding period start date, adjusted for wash sales."""

    inherited_indicator: Annotated[
        Optional[OpenLotInheritedIndicator], PlainValidator(validate_open_enum(False))
    ] = None
    r"""Indicates inherited shares."""

    long_short_indicator: Annotated[
        Optional[OpenLotLongShortIndicator], PlainValidator(validate_open_enum(False))
    ] = None
    r"""Indicates whether the lot is long or short."""

    multiplier: OptionalNullable[OpenLotMultiplier] = UNSET
    r"""Pricing multiplier for the asset"""

    name: Optional[str] = None
    r"""The name field Format: accounts/{account}/openLots/{open_lot}"""

    open_lot_id: Optional[str] = None
    r"""Globally unique open lot identifier."""

    quantity: OptionalNullable[OpenLotQuantity] = UNSET
    r"""lot quantity."""

    replacement_share_indicator: Annotated[
        Optional[OpenLotReplacementShareIndicator],
        PlainValidator(validate_open_enum(False)),
    ] = None
    r"""Indicates if lot represents wash sale replacement shares."""

    symbol: Optional[str] = None
    r"""security symbol for the asset"""

    term: Annotated[
        Optional[OpenLotTerm], PlainValidator(validate_open_enum(False))
    ] = None
    r"""Capital gains term, adjusted for wash sales."""

    wash_sale_adjustment_amount: OptionalNullable[OpenLotWashSaleAdjustmentAmount] = (
        UNSET
    )
    r"""Adjustment due to wash sales, in USD. Note: For open short lots, wash sale adjustment is presented as a negative value, reducing proceeds for correct unrealized gain loss calculation -- once closed, this will appear as a positive value, indicating addition to cost."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = [
            "account_id",
            "acquisition_adjusted_net_amount",
            "acquisition_adjusted_net_per_share_amount",
            "acquisition_commission_fee_amount",
            "acquisition_event_type",
            "acquisition_execution_price_amount",
            "acquisition_fx_rate_amount",
            "acquisition_original_net_amount",
            "acquisition_original_trade_date",
            "acquisition_transaction_id",
            "acquisition_true_zero_indicator",
            "asset_id",
            "average_basis_indicator",
            "covered_lot_indicator",
            "currency_code",
            "cusip",
            "drip_indicator",
            "gift_indicator",
            "holding_start_date",
            "inherited_indicator",
            "long_short_indicator",
            "multiplier",
            "name",
            "open_lot_id",
            "quantity",
            "replacement_share_indicator",
            "symbol",
            "term",
            "wash_sale_adjustment_amount",
        ]
        nullable_fields = [
            "acquisition_adjusted_net_amount",
            "acquisition_adjusted_net_per_share_amount",
            "acquisition_commission_fee_amount",
            "acquisition_execution_price_amount",
            "acquisition_fx_rate_amount",
            "acquisition_original_net_amount",
            "acquisition_original_trade_date",
            "holding_start_date",
            "multiplier",
            "quantity",
            "wash_sale_adjustment_amount",
        ]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
