"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from ascend_sdk import utils
from ascend_sdk.types import BaseModel
from ascend_sdk.utils import validate_open_enum
from enum import Enum
from pydantic.functional_validators import PlainValidator
from typing_extensions import Annotated, TypedDict


class OptionOrderLegCreateAssetType(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""The type of the asset in this option order leg. Orders with only a single leg may only contain an OPTION asset type. Orders with multiple legs must contain at least one OPTION leg, and no more than one EQUITY leg."""

    EQUITY = "EQUITY"
    OPTION = "OPTION"


class OptionOrderLegCreateIdentifierType(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""The format of the identifier value used to look up the security. When `asset_type` is OPTION, the identifier_type must be OSI."""

    LEG_IDENTIFIER_TYPE_UNSPECIFIED = "LEG_IDENTIFIER_TYPE_UNSPECIFIED"
    OSI = "OSI"


class OptionOrderLegCreateSide(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""The side of the option order to be sent to the market."""

    SIDE_UNSPECIFIED = "SIDE_UNSPECIFIED"
    BUY = "BUY"
    SELL = "SELL"


class SideModifier(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""The open/close modification of the side, signaling whether this option order leg intends to OPEN a new position, or to CLOSE an existing one."""

    SIDE_MODIFIER_UNSPECIFIED = "SIDE_MODIFIER_UNSPECIFIED"
    OPEN = "OPEN"
    CLOSE = "CLOSE"


class OptionOrderLegCreateTypedDict(TypedDict):
    r"""The message describing an option order leg."""

    asset_type: OptionOrderLegCreateAssetType
    r"""The type of the asset in this option order leg. Orders with only a single leg may only contain an OPTION asset type. Orders with multiple legs must contain at least one OPTION leg, and no more than one EQUITY leg."""
    identifier: str
    r"""The identifier of the asset, in the format specified by `identifier_type`. When `identifier_type` is OSI, this field must be a valid OSI identifier, which is between 16 and 21 characters. (This value must not contain any spaces between the symbol and expiry date.) When `identifier_type` is SYMBOL, this field must contain the ticker value of the security, which is between 1 and 6 characters and must conform the same input constraints called out in the non-options single option order API."""
    identifier_type: OptionOrderLegCreateIdentifierType
    r"""The format of the identifier value used to look up the security. When `asset_type` is OPTION, the identifier_type must be OSI."""
    ratio_quantity: int
    r"""This specifies the quantity of security to be ordered in this leg. For a single-leg order, this value must be 1 (one). For a multi-leg order, this value must be greater than zero, and the total number of shares or contracts ordered at the market will be `order.quantity * leg.ratio_quantity`."""
    side: OptionOrderLegCreateSide
    r"""The side of the option order to be sent to the market."""
    side_modifier: SideModifier
    r"""The open/close modification of the side, signaling whether this option order leg intends to OPEN a new position, or to CLOSE an existing one."""


class OptionOrderLegCreate(BaseModel):
    r"""The message describing an option order leg."""

    asset_type: Annotated[
        OptionOrderLegCreateAssetType, PlainValidator(validate_open_enum(False))
    ]
    r"""The type of the asset in this option order leg. Orders with only a single leg may only contain an OPTION asset type. Orders with multiple legs must contain at least one OPTION leg, and no more than one EQUITY leg."""

    identifier: str
    r"""The identifier of the asset, in the format specified by `identifier_type`. When `identifier_type` is OSI, this field must be a valid OSI identifier, which is between 16 and 21 characters. (This value must not contain any spaces between the symbol and expiry date.) When `identifier_type` is SYMBOL, this field must contain the ticker value of the security, which is between 1 and 6 characters and must conform the same input constraints called out in the non-options single option order API."""

    identifier_type: Annotated[
        OptionOrderLegCreateIdentifierType, PlainValidator(validate_open_enum(False))
    ]
    r"""The format of the identifier value used to look up the security. When `asset_type` is OPTION, the identifier_type must be OSI."""

    ratio_quantity: int
    r"""This specifies the quantity of security to be ordered in this leg. For a single-leg order, this value must be 1 (one). For a multi-leg order, this value must be greater than zero, and the total number of shares or contracts ordered at the market will be `order.quantity * leg.ratio_quantity`."""

    side: Annotated[OptionOrderLegCreateSide, PlainValidator(validate_open_enum(False))]
    r"""The side of the option order to be sent to the market."""

    side_modifier: Annotated[SideModifier, PlainValidator(validate_open_enum(False))]
    r"""The open/close modification of the side, signaling whether this option order leg intends to OPEN a new position, or to CLOSE an existing one."""
