"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .optionorderleg import OptionOrderLeg, OptionOrderLegTypedDict
from .tradingfee import TradingFee, TradingFeeTypedDict
from ascend_sdk import utils
from ascend_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from ascend_sdk.utils import validate_open_enum
from datetime import datetime
from enum import Enum
from pydantic import model_serializer
from pydantic.functional_validators import PlainValidator
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class OptionOrderBrokerCapacity(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""The capacity in which the broker is acting for this option order."""

    BROKER_CAPACITY_UNSPECIFIED = "BROKER_CAPACITY_UNSPECIFIED"
    AGENCY = "AGENCY"
    PRINCIPAL = "PRINCIPAL"


class OptionOrderCancelRejectedReason(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""Used to denote when a cancel request has been rejected."""

    CANCEL_REJECT_REASON_UNSPECIFIED = "CANCEL_REJECT_REASON_UNSPECIFIED"
    TOO_LATE_TO_CANCEL = "TOO_LATE_TO_CANCEL"
    CANCELLATION_UNKNOWN_ORDER = "CANCELLATION_UNKNOWN_ORDER"
    BROKER_EXCHANGE_OPTION = "BROKER_EXCHANGE_OPTION"
    ORDER_ALREADY_IN_PENDING_CANCEL_OR_PENDING_REPLACE_STATUS = (
        "ORDER_ALREADY_IN_PENDING_CANCEL_OR_PENDING_REPLACE_STATUS"
    )
    DUPLICATE = "DUPLICATE"
    CANCELLATION_SYSTEM_ERROR = "CANCELLATION_SYSTEM_ERROR"
    ORDER_ALREADY_CANCELED = "ORDER_ALREADY_CANCELED"
    CANCELLATION_MISCONFIGURED_CLIENT = "CANCELLATION_MISCONFIGURED_CLIENT"


class OptionOrderCumulativeNotionalValueTypedDict(TypedDict):
    r"""This represents the absolute value of the notional amount (without fees) transacted across all of this legs. If present, this will always a positive number, or zero. This field will be empty if there are no leg executions."""

    value: NotRequired[str]
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class OptionOrderCumulativeNotionalValue(BaseModel):
    r"""This represents the absolute value of the notional amount (without fees) transacted across all of this legs. If present, this will always a positive number, or zero. This field will be empty if there are no leg executions."""

    value: Optional[str] = None
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class CumulativeNotionalValueDirection(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""This represents the direction of the total filled notional value, which will be present if the `cumulative_notional_value` is also present. If there are no executions, this value will be absent. When the summed notional value of all CREDIT legs exceeds that of the DEBIT legs a CREDIT will be reported here; otherwise a DEBIT will be reported."""

    DEBIT_CREDIT_TYPE_UNSPECIFIED = "DEBIT_CREDIT_TYPE_UNSPECIFIED"
    DEBIT = "DEBIT"
    CREDIT = "CREDIT"


class OptionOrderLimitPriceTypedDict(TypedDict):
    r"""The limit price for this option order. For single-leg option orders, this is the price per contract which the filled order must match or beat. For multi-leg orders, this represents the amortized \"price per unit\" that must be matched or beat. (E.g. with a limit price of a $4 DEBIT, and an order with 2 legs that includes one leg buy 100 shares of SBX and another leg to sell 1 contract of SBX, then the fills will be guaranteed to result in no more than a $400--4 USD X 100 shares/contract--total debit against the ordering account.)"""

    value: NotRequired[str]
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class OptionOrderLimitPrice(BaseModel):
    r"""The limit price for this option order. For single-leg option orders, this is the price per contract which the filled order must match or beat. For multi-leg orders, this represents the amortized \"price per unit\" that must be matched or beat. (E.g. with a limit price of a $4 DEBIT, and an order with 2 legs that includes one leg buy 100 shares of SBX and another leg to sell 1 contract of SBX, then the fills will be guaranteed to result in no more than a $400--4 USD X 100 shares/contract--total debit against the ordering account.)"""

    value: Optional[str] = None
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class OptionOrderOrderDateTypedDict(TypedDict):
    r"""The date on which the option order will go to the market: must be \"today\". Option orders will only be accepted during normal trading hours."""

    day: NotRequired[int]
    r"""Day of a month. Must be from 1 to 31 and valid for the year and month, or 0 to specify a year by itself or a year and month where the day isn't significant."""
    month: NotRequired[int]
    r"""Month of a year. Must be from 1 to 12, or 0 to specify a year without a month and day."""
    year: NotRequired[int]
    r"""Year of the date. Must be from 1 to 9999, or 0 to specify a date without a year."""


class OptionOrderOrderDate(BaseModel):
    r"""The date on which the option order will go to the market: must be \"today\". Option orders will only be accepted during normal trading hours."""

    day: Optional[int] = None
    r"""Day of a month. Must be from 1 to 31 and valid for the year and month, or 0 to specify a year by itself or a year and month where the day isn't significant."""

    month: Optional[int] = None
    r"""Month of a year. Must be from 1 to 12, or 0 to specify a year without a month and day."""

    year: Optional[int] = None
    r"""Year of the date. Must be from 1 to 9999, or 0 to specify a date without a year."""


class OptionOrderOrderRejectedReason(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""When an option order has the REJECTED status, this will be populated with a system code describing the rejection."""

    ORDER_REJECT_REASON_UNSPECIFIED = "ORDER_REJECT_REASON_UNSPECIFIED"
    BROKER_OPTION = "BROKER_OPTION"
    UNKNOWN_SECURITY = "UNKNOWN_SECURITY"
    EXCHANGE_CLOSED = "EXCHANGE_CLOSED"
    ORDER_EXCEEDS_LIMIT = "ORDER_EXCEEDS_LIMIT"
    TOO_LATE_TO_ENTER = "TOO_LATE_TO_ENTER"
    UNKNOWN_ORDER = "UNKNOWN_ORDER"
    DUPLICATE_ORDER = "DUPLICATE_ORDER"
    STALE_ORDER = "STALE_ORDER"
    BELOW_NOTIONAL_MINIMUM = "BELOW_NOTIONAL_MINIMUM"
    ORDER_DATE_UNAVAILABLE = "ORDER_DATE_UNAVAILABLE"
    AGGRESSIVE_LIMIT_PRICE = "AGGRESSIVE_LIMIT_PRICE"
    ACCOUNT_NOT_ENTITLED = "ACCOUNT_NOT_ENTITLED"
    SYSTEM_ERROR = "SYSTEM_ERROR"
    BLOCKING_CORPORATE_ACTION = "BLOCKING_CORPORATE_ACTION"
    UNAVAILABLE_PRICE_QUOTE = "UNAVAILABLE_PRICE_QUOTE"
    EXECUTION_MISCONFIGURED_CLIENT = "EXECUTION_MISCONFIGURED_CLIENT"
    NOTIONAL_QUANTITY_NOT_ALLOWED_FOR_SECURITY = (
        "NOTIONAL_QUANTITY_NOT_ALLOWED_FOR_SECURITY"
    )
    FRACTIONAL_QUANTITY_NOT_ALLOWED_FOR_SECURITY = (
        "FRACTIONAL_QUANTITY_NOT_ALLOWED_FOR_SECURITY"
    )
    ONLY_FRACTIONAL_SELL_OR_WHOLE_ORDERS_ALLOWED_FOR_SECURITY = (
        "ONLY_FRACTIONAL_SELL_OR_WHOLE_ORDERS_ALLOWED_FOR_SECURITY"
    )
    ABOVE_NOTIONAL_MAXIMUM = "ABOVE_NOTIONAL_MAXIMUM"
    ABOVE_SHARE_MAXIMUM = "ABOVE_SHARE_MAXIMUM"
    FAILED_BUYING_POWER = "FAILED_BUYING_POWER"
    INSUFFICIENT_POSITION = "INSUFFICIENT_POSITION"
    TRADES_DISABLED_FOR_ASSET_TYPE = "TRADES_DISABLED_FOR_ASSET_TYPE"
    COMMISSION_NOT_ALLOWED_FOR_NON_BROKER_DEALER = (
        "COMMISSION_NOT_ALLOWED_FOR_NON_BROKER_DEALER"
    )
    ASSET_NOT_SET_UP_TO_TRADE = "ASSET_NOT_SET_UP_TO_TRADE"
    INVALID_ORDER_QUANTITY = "INVALID_ORDER_QUANTITY"
    CLIENT_RECEIVED_TIME_REQUIRED = "CLIENT_RECEIVED_TIME_REQUIRED"
    UNSUPPORTED_PRICE_VALUE = "UNSUPPORTED_PRICE_VALUE"


class OptionOrderOrderStatus(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""The processing status of the option order"""

    ORDER_STATUS_UNSPECIFIED = "ORDER_STATUS_UNSPECIFIED"
    PENDING_NEW = "PENDING_NEW"
    NEW = "NEW"
    PENDING_QUEUED = "PENDING_QUEUED"
    QUEUED = "QUEUED"
    PARTIALLY_FILLED = "PARTIALLY_FILLED"
    FILLED = "FILLED"
    PENDING_CANCEL = "PENDING_CANCEL"
    CANCELED = "CANCELED"
    REJECTED = "REJECTED"


class OptionOrderOrderType(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""The execution type of this option order."""

    ORDER_TYPE_UNSPECIFIED = "ORDER_TYPE_UNSPECIFIED"
    LIMIT = "LIMIT"


class OptionOrderPriceDirection(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""The direction of the price, which indicates whether the entire option order should result in a credit to the account placing the order, or a debit from the account placing the order."""

    DEBIT_CREDIT_TYPE_UNSPECIFIED = "DEBIT_CREDIT_TYPE_UNSPECIFIED"
    DEBIT = "DEBIT"
    CREDIT = "CREDIT"


class OptionOrderQuantityTypedDict(TypedDict):
    r"""The quantity of the option order to be placed. The `ratio_quantity` of each leg will be multiplied by this value to determine the total number of units being ordered within each leg. (E.g. if a quantity of 3 is specified, and a leg with a `ratio_quantity` of 2 is specified, then the total number of contracts being ordered by that leg will be 6.)"""

    value: NotRequired[str]
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class OptionOrderQuantity(BaseModel):
    r"""The quantity of the option order to be placed. The `ratio_quantity` of each leg will be multiplied by this value to determine the total number of units being ordered within each leg. (E.g. if a quantity of 3 is specified, and a leg with a `ratio_quantity` of 2 is specified, then the total number of contracts being ordered by that leg will be 6.)"""

    value: Optional[str] = None
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class OptionOrderSpecialReportingInstructions(str, Enum, metaclass=utils.OpenEnumMeta):
    SPECIAL_REPORTING_INSTRUCTIONS_UNSPECIFIED = (
        "SPECIAL_REPORTING_INSTRUCTIONS_UNSPECIFIED"
    )
    CUSTOMER_DIRECTED = "CUSTOMER_DIRECTED"
    WITH_DIVIDEND = "WITH_DIVIDEND"
    WITH_RIGHTS = "WITH_RIGHTS"
    DISCRETION_EXERCISED = "DISCRETION_EXERCISED"
    DISCRETION_NOT_EXERCISED = "DISCRETION_NOT_EXERCISED"
    BROKER_DEALER_ORDER = "BROKER_DEALER_ORDER"
    FULLY_REGISTERED = "FULLY_REGISTERED"
    ODDLOT_DIFF_ON_REQUEST = "ODDLOT_DIFF_ON_REQUEST"
    PROSPECTUS_ENCLOSED = "PROSPECTUS_ENCLOSED"
    PROSPECTUS_SEPARATE_MAIL = "PROSPECTUS_SEPARATE_MAIL"
    SOLICITED = "SOLICITED"
    UNSOLICITED = "UNSOLICITED"
    X_DIVIDEND = "X_DIVIDEND"
    ACTING_AS_PRINCIPAL = "ACTING_AS_PRINCIPAL"
    AVERAGE_PRICE = "AVERAGE_PRICE"
    BROKER_LIQUIDATION = "BROKER_LIQUIDATION"
    INTERNET_ORDER = "INTERNET_ORDER"
    MARGIN_SELLOUT = "MARGIN_SELLOUT"
    NEGATIVE_NET_PROCEED = "NEGATIVE_NET_PROCEED"
    RISKLESS_PRINCIPAL = "RISKLESS_PRINCIPAL"
    THIRD_MARKET = "THIRD_MARKET"
    SUPPRESS_TRACE_REPORTING = "SUPPRESS_TRACE_REPORTING"
    WHEN_DISTRIBUTED = "WHEN_DISTRIBUTED"
    ROUND_UP = "ROUND_UP"
    CAT_PARENT_ALGO = "CAT_PARENT_ALGO"
    CAT_PARENT_GTC = "CAT_PARENT_GTC"


class OptionOrderTimeInForce(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""Must be the value \"DAY\". Regulatory requirements dictate the system captures the intended time_in_force, which is why this a mandatory field."""

    TIME_IN_FORCE_UNSPECIFIED = "TIME_IN_FORCE_UNSPECIFIED"
    DAY = "DAY"


class OptionOrderTypedDict(TypedDict):
    r"""The message describing an option order"""

    account_id: NotRequired[str]
    r"""The identifier of the account transacting this option order"""
    broker_capacity: NotRequired[OptionOrderBrokerCapacity]
    r"""The capacity in which the broker is acting for this option order."""
    cancel_reason: NotRequired[str]
    r"""Used to explain why an option order is canceled"""
    cancel_rejected_reason: NotRequired[OptionOrderCancelRejectedReason]
    r"""Used to denote when a cancel request has been rejected."""
    client_order_id: NotRequired[str]
    r"""User-supplied unique option order ID. Cannot be more than 40 characters long."""
    client_received_time: NotRequired[Nullable[datetime]]
    r"""Required for any client who is having Apex do CAT reporting on their behalf."""
    create_time: NotRequired[Nullable[datetime]]
    r"""Time of the option order creation"""
    cumulative_notional_value: NotRequired[
        Nullable[OptionOrderCumulativeNotionalValueTypedDict]
    ]
    r"""This represents the absolute value of the notional amount (without fees) transacted across all of this legs. If present, this will always a positive number, or zero. This field will be empty if there are no leg executions."""
    cumulative_notional_value_direction: NotRequired[CumulativeNotionalValueDirection]
    r"""This represents the direction of the total filled notional value, which will be present if the `cumulative_notional_value` is also present. If there are no executions, this value will be absent. When the summed notional value of all CREDIT legs exceeds that of the DEBIT legs a CREDIT will be reported here; otherwise a DEBIT will be reported."""
    currency_code: NotRequired[str]
    r"""Only \"USD\" is supported. Full list of currency codes is defined at: https://en.wikipedia.org/wiki/ISO_4217"""
    fees: NotRequired[List[TradingFeeTypedDict]]
    r"""Fees that will be applied to this option order."""
    last_update_time: NotRequired[Nullable[datetime]]
    r"""Time of the last option order update"""
    legs: NotRequired[List[OptionOrderLegTypedDict]]
    r"""The legs of this option order. Only a single leg is allowed to be specified, and it must be for an OPTION security."""
    limit_price: NotRequired[Nullable[OptionOrderLimitPriceTypedDict]]
    r"""The limit price for this option order. For single-leg option orders, this is the price per contract which the filled order must match or beat. For multi-leg orders, this represents the amortized \"price per unit\" that must be matched or beat. (E.g. with a limit price of a $4 DEBIT, and an order with 2 legs that includes one leg buy 100 shares of SBX and another leg to sell 1 contract of SBX, then the fills will be guaranteed to result in no more than a $400--4 USD X 100 shares/contract--total debit against the ordering account.)"""
    name: NotRequired[str]
    r"""System generated name of the option order."""
    option_order_id: NotRequired[str]
    r"""System generated unique id for the option order."""
    order_date: NotRequired[Nullable[OptionOrderOrderDateTypedDict]]
    r"""The date on which the option order will go to the market: must be \"today\". Option orders will only be accepted during normal trading hours."""
    order_rejected_reason: NotRequired[OptionOrderOrderRejectedReason]
    r"""When an option order has the REJECTED status, this will be populated with a system code describing the rejection."""
    order_status: NotRequired[OptionOrderOrderStatus]
    r"""The processing status of the option order"""
    order_type: NotRequired[OptionOrderOrderType]
    r"""The execution type of this option order."""
    price_direction: NotRequired[OptionOrderPriceDirection]
    r"""The direction of the price, which indicates whether the entire option order should result in a credit to the account placing the order, or a debit from the account placing the order."""
    quantity: NotRequired[Nullable[OptionOrderQuantityTypedDict]]
    r"""The quantity of the option order to be placed. The `ratio_quantity` of each leg will be multiplied by this value to determine the total number of units being ordered within each leg. (E.g. if a quantity of 3 is specified, and a leg with a `ratio_quantity` of 2 is specified, then the total number of contracts being ordered by that leg will be 6.)"""
    special_reporting_instructions: NotRequired[
        List[OptionOrderSpecialReportingInstructions]
    ]
    r"""Special Reporting Instructions to be applied to this option order. Can include multiple Instructions."""
    time_in_force: NotRequired[OptionOrderTimeInForce]
    r"""Must be the value \"DAY\". Regulatory requirements dictate the system captures the intended time_in_force, which is why this a mandatory field."""


class OptionOrder(BaseModel):
    r"""The message describing an option order"""

    account_id: Optional[str] = None
    r"""The identifier of the account transacting this option order"""

    broker_capacity: Annotated[
        Optional[OptionOrderBrokerCapacity], PlainValidator(validate_open_enum(False))
    ] = None
    r"""The capacity in which the broker is acting for this option order."""

    cancel_reason: Optional[str] = None
    r"""Used to explain why an option order is canceled"""

    cancel_rejected_reason: Annotated[
        Optional[OptionOrderCancelRejectedReason],
        PlainValidator(validate_open_enum(False)),
    ] = None
    r"""Used to denote when a cancel request has been rejected."""

    client_order_id: Optional[str] = None
    r"""User-supplied unique option order ID. Cannot be more than 40 characters long."""

    client_received_time: OptionalNullable[datetime] = UNSET
    r"""Required for any client who is having Apex do CAT reporting on their behalf."""

    create_time: OptionalNullable[datetime] = UNSET
    r"""Time of the option order creation"""

    cumulative_notional_value: OptionalNullable[OptionOrderCumulativeNotionalValue] = (
        UNSET
    )
    r"""This represents the absolute value of the notional amount (without fees) transacted across all of this legs. If present, this will always a positive number, or zero. This field will be empty if there are no leg executions."""

    cumulative_notional_value_direction: Annotated[
        Optional[CumulativeNotionalValueDirection],
        PlainValidator(validate_open_enum(False)),
    ] = None
    r"""This represents the direction of the total filled notional value, which will be present if the `cumulative_notional_value` is also present. If there are no executions, this value will be absent. When the summed notional value of all CREDIT legs exceeds that of the DEBIT legs a CREDIT will be reported here; otherwise a DEBIT will be reported."""

    currency_code: Optional[str] = None
    r"""Only \"USD\" is supported. Full list of currency codes is defined at: https://en.wikipedia.org/wiki/ISO_4217"""

    fees: Optional[List[TradingFee]] = None
    r"""Fees that will be applied to this option order."""

    last_update_time: OptionalNullable[datetime] = UNSET
    r"""Time of the last option order update"""

    legs: Optional[List[OptionOrderLeg]] = None
    r"""The legs of this option order. Only a single leg is allowed to be specified, and it must be for an OPTION security."""

    limit_price: OptionalNullable[OptionOrderLimitPrice] = UNSET
    r"""The limit price for this option order. For single-leg option orders, this is the price per contract which the filled order must match or beat. For multi-leg orders, this represents the amortized \"price per unit\" that must be matched or beat. (E.g. with a limit price of a $4 DEBIT, and an order with 2 legs that includes one leg buy 100 shares of SBX and another leg to sell 1 contract of SBX, then the fills will be guaranteed to result in no more than a $400--4 USD X 100 shares/contract--total debit against the ordering account.)"""

    name: Optional[str] = None
    r"""System generated name of the option order."""

    option_order_id: Optional[str] = None
    r"""System generated unique id for the option order."""

    order_date: OptionalNullable[OptionOrderOrderDate] = UNSET
    r"""The date on which the option order will go to the market: must be \"today\". Option orders will only be accepted during normal trading hours."""

    order_rejected_reason: Annotated[
        Optional[OptionOrderOrderRejectedReason],
        PlainValidator(validate_open_enum(False)),
    ] = None
    r"""When an option order has the REJECTED status, this will be populated with a system code describing the rejection."""

    order_status: Annotated[
        Optional[OptionOrderOrderStatus], PlainValidator(validate_open_enum(False))
    ] = None
    r"""The processing status of the option order"""

    order_type: Annotated[
        Optional[OptionOrderOrderType], PlainValidator(validate_open_enum(False))
    ] = None
    r"""The execution type of this option order."""

    price_direction: Annotated[
        Optional[OptionOrderPriceDirection], PlainValidator(validate_open_enum(False))
    ] = None
    r"""The direction of the price, which indicates whether the entire option order should result in a credit to the account placing the order, or a debit from the account placing the order."""

    quantity: OptionalNullable[OptionOrderQuantity] = UNSET
    r"""The quantity of the option order to be placed. The `ratio_quantity` of each leg will be multiplied by this value to determine the total number of units being ordered within each leg. (E.g. if a quantity of 3 is specified, and a leg with a `ratio_quantity` of 2 is specified, then the total number of contracts being ordered by that leg will be 6.)"""

    special_reporting_instructions: Optional[
        List[
            Annotated[
                OptionOrderSpecialReportingInstructions,
                PlainValidator(validate_open_enum(False)),
            ]
        ]
    ] = None
    r"""Special Reporting Instructions to be applied to this option order. Can include multiple Instructions."""

    time_in_force: Annotated[
        Optional[OptionOrderTimeInForce], PlainValidator(validate_open_enum(False))
    ] = None
    r"""Must be the value \"DAY\". Regulatory requirements dictate the system captures the intended time_in_force, which is why this a mandatory field."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = [
            "account_id",
            "broker_capacity",
            "cancel_reason",
            "cancel_rejected_reason",
            "client_order_id",
            "client_received_time",
            "create_time",
            "cumulative_notional_value",
            "cumulative_notional_value_direction",
            "currency_code",
            "fees",
            "last_update_time",
            "legs",
            "limit_price",
            "name",
            "option_order_id",
            "order_date",
            "order_rejected_reason",
            "order_status",
            "order_type",
            "price_direction",
            "quantity",
            "special_reporting_instructions",
            "time_in_force",
        ]
        nullable_fields = [
            "client_received_time",
            "create_time",
            "cumulative_notional_value",
            "last_update_time",
            "limit_price",
            "order_date",
            "quantity",
        ]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
