"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .optionorderleg_execution import (
    OptionOrderLegExecution,
    OptionOrderLegExecutionTypedDict,
)
from ascend_sdk import utils
from ascend_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from ascend_sdk.utils import validate_open_enum
from enum import Enum
from pydantic import model_serializer
from pydantic.functional_validators import PlainValidator
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class OptionOrderLegAssetType(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""The type of the asset in this option order leg. Orders with only a single leg may only contain an OPTION asset type. Orders with multiple legs must contain at least one OPTION leg, and no more than one EQUITY leg."""

    EQUITY = "EQUITY"
    OPTION = "OPTION"


class AveragePriceTypedDict(TypedDict):
    r"""The computed average price for this leg, which is a weighted average (by quantity) of the executed prices."""

    value: NotRequired[str]
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class AveragePrice(BaseModel):
    r"""The computed average price for this leg, which is a weighted average (by quantity) of the executed prices."""

    value: Optional[str] = None
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class OptionOrderLegDirection(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""The computed direction for this leg. When `side` is BUY, `direction` will be DEBIT. When `side` is SELL, `direction` will be CREDIT."""

    DEBIT_CREDIT_TYPE_UNSPECIFIED = "DEBIT_CREDIT_TYPE_UNSPECIFIED"
    DEBIT = "DEBIT"
    CREDIT = "CREDIT"


class OptionOrderLegIdentifierType(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""The format of the identifier value used to look up the security. When `asset_type` is OPTION, the identifier_type must be OSI."""

    LEG_IDENTIFIER_TYPE_UNSPECIFIED = "LEG_IDENTIFIER_TYPE_UNSPECIFIED"
    OSI = "OSI"


class OptionOrderLegSide(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""The side of the option order to be sent to the market."""

    SIDE_UNSPECIFIED = "SIDE_UNSPECIFIED"
    BUY = "BUY"
    SELL = "SELL"


class OptionOrderLegSideModifier(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""The open/close modification of the side, signaling whether this option order leg intends to OPEN a new position, or to CLOSE an existing one."""

    SIDE_MODIFIER_UNSPECIFIED = "SIDE_MODIFIER_UNSPECIFIED"
    OPEN = "OPEN"
    CLOSE = "CLOSE"


class OptionOrderLegTypedDict(TypedDict):
    r"""The message describing an option order leg."""

    asset_id: NotRequired[str]
    r"""The unique identifier of the asset in the Apex system. If the requested identifier does not match any known Apex asset, then this field will not be set."""
    asset_type: NotRequired[OptionOrderLegAssetType]
    r"""The type of the asset in this option order leg. Orders with only a single leg may only contain an OPTION asset type. Orders with multiple legs must contain at least one OPTION leg, and no more than one EQUITY leg."""
    average_price: NotRequired[Nullable[AveragePriceTypedDict]]
    r"""The computed average price for this leg, which is a weighted average (by quantity) of the executed prices."""
    direction: NotRequired[OptionOrderLegDirection]
    r"""The computed direction for this leg. When `side` is BUY, `direction` will be DEBIT. When `side` is SELL, `direction` will be CREDIT."""
    executions: NotRequired[List[OptionOrderLegExecutionTypedDict]]
    r"""The list of executions contributing to the fill of this leg of the option order."""
    identifier: NotRequired[str]
    r"""The identifier of the asset, in the format specified by `identifier_type`. When `identifier_type` is OSI, this field must be a valid OSI identifier, which is between 16 and 21 characters. (This value must not contain any spaces between the symbol and expiry date.) When `identifier_type` is SYMBOL, this field must contain the ticker value of the security, which is between 1 and 6 characters and must conform the same input constraints called out in the non-options single option order API."""
    identifier_type: NotRequired[OptionOrderLegIdentifierType]
    r"""The format of the identifier value used to look up the security. When `asset_type` is OPTION, the identifier_type must be OSI."""
    ratio_quantity: NotRequired[int]
    r"""This specifies the quantity of security to be ordered in this leg. For a single-leg order, this value must be 1 (one). For a multi-leg order, this value must be greater than zero, and the total number of shares or contracts ordered at the market will be `order.quantity * leg.ratio_quantity`."""
    side: NotRequired[OptionOrderLegSide]
    r"""The side of the option order to be sent to the market."""
    side_modifier: NotRequired[OptionOrderLegSideModifier]
    r"""The open/close modification of the side, signaling whether this option order leg intends to OPEN a new position, or to CLOSE an existing one."""


class OptionOrderLeg(BaseModel):
    r"""The message describing an option order leg."""

    asset_id: Optional[str] = None
    r"""The unique identifier of the asset in the Apex system. If the requested identifier does not match any known Apex asset, then this field will not be set."""

    asset_type: Annotated[
        Optional[OptionOrderLegAssetType], PlainValidator(validate_open_enum(False))
    ] = None
    r"""The type of the asset in this option order leg. Orders with only a single leg may only contain an OPTION asset type. Orders with multiple legs must contain at least one OPTION leg, and no more than one EQUITY leg."""

    average_price: OptionalNullable[AveragePrice] = UNSET
    r"""The computed average price for this leg, which is a weighted average (by quantity) of the executed prices."""

    direction: Annotated[
        Optional[OptionOrderLegDirection], PlainValidator(validate_open_enum(False))
    ] = None
    r"""The computed direction for this leg. When `side` is BUY, `direction` will be DEBIT. When `side` is SELL, `direction` will be CREDIT."""

    executions: Optional[List[OptionOrderLegExecution]] = None
    r"""The list of executions contributing to the fill of this leg of the option order."""

    identifier: Optional[str] = None
    r"""The identifier of the asset, in the format specified by `identifier_type`. When `identifier_type` is OSI, this field must be a valid OSI identifier, which is between 16 and 21 characters. (This value must not contain any spaces between the symbol and expiry date.) When `identifier_type` is SYMBOL, this field must contain the ticker value of the security, which is between 1 and 6 characters and must conform the same input constraints called out in the non-options single option order API."""

    identifier_type: Annotated[
        Optional[OptionOrderLegIdentifierType],
        PlainValidator(validate_open_enum(False)),
    ] = None
    r"""The format of the identifier value used to look up the security. When `asset_type` is OPTION, the identifier_type must be OSI."""

    ratio_quantity: Optional[int] = None
    r"""This specifies the quantity of security to be ordered in this leg. For a single-leg order, this value must be 1 (one). For a multi-leg order, this value must be greater than zero, and the total number of shares or contracts ordered at the market will be `order.quantity * leg.ratio_quantity`."""

    side: Annotated[
        Optional[OptionOrderLegSide], PlainValidator(validate_open_enum(False))
    ] = None
    r"""The side of the option order to be sent to the market."""

    side_modifier: Annotated[
        Optional[OptionOrderLegSideModifier], PlainValidator(validate_open_enum(False))
    ] = None
    r"""The open/close modification of the side, signaling whether this option order leg intends to OPEN a new position, or to CLOSE an existing one."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = [
            "asset_id",
            "asset_type",
            "average_price",
            "direction",
            "executions",
            "identifier",
            "identifier_type",
            "ratio_quantity",
            "side",
            "side_modifier",
        ]
        nullable_fields = ["average_price"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
