"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from ascend_sdk.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class PendingInvestorActionTypedDict(TypedDict):
    r"""A pending investor action required for an alternative order."""

    action_uri: NotRequired[str]
    r"""The link to the document that requires action. Using this link will open the document in a new window or browser tab."""
    action_uri_embeddable: NotRequired[str]
    r"""The link to the document that requires action, suitable for embedding via iframe."""
    description: NotRequired[str]
    r"""The description of the action."""
    party_id: NotRequired[str]
    r"""The ID of the party responsible for performing the action."""


class PendingInvestorAction(BaseModel):
    r"""A pending investor action required for an alternative order."""

    action_uri: Optional[str] = None
    r"""The link to the document that requires action. Using this link will open the document in a new window or browser tab."""

    action_uri_embeddable: Optional[str] = None
    r"""The link to the document that requires action, suitable for embedding via iframe."""

    description: Optional[str] = None
    r"""The description of the action."""

    party_id: Optional[str] = None
    r"""The ID of the party responsible for performing the action."""
