"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .preipocompanyfundinground_closing import (
    PreIpoCompanyFundingRoundClosing,
    PreIpoCompanyFundingRoundClosingTypedDict,
)
from ascend_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from datetime import datetime
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class PreIpoCompanyFundingRoundTypedDict(TypedDict):
    r"""A Pre IPO Company Funding Round."""

    closings: NotRequired[List[PreIpoCompanyFundingRoundClosingTypedDict]]
    r"""The closings associated with the Pre IPO Company Funding Round."""
    funding_round_id: NotRequired[str]
    r"""The ID of the Pre IPO Company Funding Round."""
    issue_time: NotRequired[Nullable[datetime]]
    r"""The time the Pre IPO Company Funding Round was issued."""
    name: NotRequired[str]
    r"""The resource name of the Pre IPO Company Funding Round. Format: preIpoCompanies/{pre_ipo_company}/fundingRounds/{funding_round}"""
    pre_ipo_company_id: NotRequired[str]
    r"""The ID of the Pre IPO Company."""
    round: NotRequired[str]
    r"""The round of funding for the Pre IPO Company."""


class PreIpoCompanyFundingRound(BaseModel):
    r"""A Pre IPO Company Funding Round."""

    closings: Optional[List[PreIpoCompanyFundingRoundClosing]] = None
    r"""The closings associated with the Pre IPO Company Funding Round."""

    funding_round_id: Optional[str] = None
    r"""The ID of the Pre IPO Company Funding Round."""

    issue_time: OptionalNullable[datetime] = UNSET
    r"""The time the Pre IPO Company Funding Round was issued."""

    name: Optional[str] = None
    r"""The resource name of the Pre IPO Company Funding Round. Format: preIpoCompanies/{pre_ipo_company}/fundingRounds/{funding_round}"""

    pre_ipo_company_id: Optional[str] = None
    r"""The ID of the Pre IPO Company."""

    round: Optional[str] = None
    r"""The round of funding for the Pre IPO Company."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = [
            "closings",
            "funding_round_id",
            "issue_time",
            "name",
            "pre_ipo_company_id",
            "round",
        ]
        nullable_fields = ["issue_time"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
