"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from ascend_sdk import utils
from ascend_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from ascend_sdk.utils import validate_open_enum
from enum import Enum
from pydantic import model_serializer
from pydantic.functional_validators import PlainValidator
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class LastValuationTypedDict(TypedDict):
    r"""The last valuation of the Pre IPO Company in USD."""

    value: NotRequired[str]
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class LastValuation(BaseModel):
    r"""The last valuation of the Pre IPO Company in USD."""

    value: Optional[str] = None
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class TotalFundingTypedDict(TypedDict):
    r"""The total funding amount the Pre IPO Company has raised in USD."""

    value: NotRequired[str]
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class TotalFunding(BaseModel):
    r"""The total funding amount the Pre IPO Company has raised in USD."""

    value: Optional[str] = None
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class TwelveMonthTrailingRevenueTypedDict(TypedDict):
    r"""The total revenue generated by the Pre IPO Company in the last twelve months in USD."""

    value: NotRequired[str]
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class TwelveMonthTrailingRevenue(BaseModel):
    r"""The total revenue generated by the Pre IPO Company in the last twelve months in USD."""

    value: Optional[str] = None
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class PreIpoCompanyType(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""The type of the Pre IPO Company."""

    TYPE_UNSPECIFIED = "TYPE_UNSPECIFIED"
    SOLE_PROPRIETOR = "SOLE_PROPRIETOR"
    SINGLE_MEMBER_LLC = "SINGLE_MEMBER_LLC"
    LLC = "LLC"
    PARTNERSHIP = "PARTNERSHIP"
    C_CORPORATION = "C_CORPORATION"
    S_CORPORATION = "S_CORPORATION"
    TRUST = "TRUST"
    IRA_OR_TAX_EXEMPT = "IRA_OR_TAX_EXEMPT"
    NON_US_CORPORATION = "NON_US_CORPORATION"
    PRIVATE_LIMITED_COMPANY = "PRIVATE_LIMITED_COMPANY"
    PUBLIC_LIMITED_COMPANY = "PUBLIC_LIMITED_COMPANY"
    TAX_EXEMPT_ENTITY = "TAX_EXEMPT_ENTITY"
    FOREIGN_TRUST = "FOREIGN_TRUST"
    OTHER = "OTHER"


class PreIpoCompanyTypedDict(TypedDict):
    r"""A Pre IPO Company."""

    active: NotRequired[bool]
    r"""Whether the Pre IPO Company is currently active. Companies are updated to inactive if they experience a bankruptcy, shutdown, or similar corporate event."""
    categories: NotRequired[List[str]]
    r"""The categories the Pre IPO Company belongs to."""
    description: NotRequired[str]
    r"""The description of the Pre IPO Company."""
    executive_team: NotRequired[List[str]]
    r"""The executive team of the Pre IPO Company."""
    facebook_uri: NotRequired[str]
    r"""The company's Facebook URI."""
    founder: NotRequired[str]
    r"""The founder of the Pre IPO Company."""
    last_valuation: NotRequired[Nullable[LastValuationTypedDict]]
    r"""The last valuation of the Pre IPO Company in USD."""
    linkedin_uri: NotRequired[str]
    r"""The company's LinkedIn URI."""
    logo_uri: NotRequired[str]
    r"""The company's logo URI."""
    name: NotRequired[str]
    r"""The resource name of the Pre IPO Company. Format: preIpoCompanies/{pre_ipo_company}"""
    pre_ipo_company_id: NotRequired[str]
    r"""The ID of the Pre IPO Company."""
    region_code: NotRequired[str]
    r"""The region code where the Pre IPO Company is located."""
    symbol: NotRequired[str]
    r"""The unique symbol assigned to the Pre IPO Company."""
    title: NotRequired[str]
    r"""The title of the Pre IPO Company."""
    total_funding: NotRequired[Nullable[TotalFundingTypedDict]]
    r"""The total funding amount the Pre IPO Company has raised in USD."""
    twelve_month_trailing_revenue: NotRequired[
        Nullable[TwelveMonthTrailingRevenueTypedDict]
    ]
    r"""The total revenue generated by the Pre IPO Company in the last twelve months in USD."""
    type: NotRequired[PreIpoCompanyType]
    r"""The type of the Pre IPO Company."""
    website_uri: NotRequired[str]
    r"""The company's official website URI."""
    x_uri: NotRequired[str]
    r"""The company's X URI."""
    year_established: NotRequired[int]
    r"""The year the Pre IPO Company was established."""


class PreIpoCompany(BaseModel):
    r"""A Pre IPO Company."""

    active: Optional[bool] = None
    r"""Whether the Pre IPO Company is currently active. Companies are updated to inactive if they experience a bankruptcy, shutdown, or similar corporate event."""

    categories: Optional[List[str]] = None
    r"""The categories the Pre IPO Company belongs to."""

    description: Optional[str] = None
    r"""The description of the Pre IPO Company."""

    executive_team: Optional[List[str]] = None
    r"""The executive team of the Pre IPO Company."""

    facebook_uri: Optional[str] = None
    r"""The company's Facebook URI."""

    founder: Optional[str] = None
    r"""The founder of the Pre IPO Company."""

    last_valuation: OptionalNullable[LastValuation] = UNSET
    r"""The last valuation of the Pre IPO Company in USD."""

    linkedin_uri: Optional[str] = None
    r"""The company's LinkedIn URI."""

    logo_uri: Optional[str] = None
    r"""The company's logo URI."""

    name: Optional[str] = None
    r"""The resource name of the Pre IPO Company. Format: preIpoCompanies/{pre_ipo_company}"""

    pre_ipo_company_id: Optional[str] = None
    r"""The ID of the Pre IPO Company."""

    region_code: Optional[str] = None
    r"""The region code where the Pre IPO Company is located."""

    symbol: Optional[str] = None
    r"""The unique symbol assigned to the Pre IPO Company."""

    title: Optional[str] = None
    r"""The title of the Pre IPO Company."""

    total_funding: OptionalNullable[TotalFunding] = UNSET
    r"""The total funding amount the Pre IPO Company has raised in USD."""

    twelve_month_trailing_revenue: OptionalNullable[TwelveMonthTrailingRevenue] = UNSET
    r"""The total revenue generated by the Pre IPO Company in the last twelve months in USD."""

    type: Annotated[
        Optional[PreIpoCompanyType], PlainValidator(validate_open_enum(False))
    ] = None
    r"""The type of the Pre IPO Company."""

    website_uri: Optional[str] = None
    r"""The company's official website URI."""

    x_uri: Optional[str] = None
    r"""The company's X URI."""

    year_established: Optional[int] = None
    r"""The year the Pre IPO Company was established."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = [
            "active",
            "categories",
            "description",
            "executive_team",
            "facebook_uri",
            "founder",
            "last_valuation",
            "linkedin_uri",
            "logo_uri",
            "name",
            "pre_ipo_company_id",
            "region_code",
            "symbol",
            "title",
            "total_funding",
            "twelve_month_trailing_revenue",
            "type",
            "website_uri",
            "x_uri",
            "year_established",
        ]
        nullable_fields = [
            "last_valuation",
            "total_funding",
            "twelve_month_trailing_revenue",
        ]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
