"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from ascend_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from datetime import datetime
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class IssuePriceTypedDict(TypedDict):
    r"""The issue price of the closing."""

    value: NotRequired[str]
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class IssuePrice(BaseModel):
    r"""The issue price of the closing."""

    value: Optional[str] = None
    r"""The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details"""


class PreIpoCompanyFundingRoundClosingTypedDict(TypedDict):
    r"""Closing details of a Pre IPO Company Funding Round."""

    issue_price: NotRequired[Nullable[IssuePriceTypedDict]]
    r"""The issue price of the closing."""
    issue_time: NotRequired[Nullable[datetime]]
    r"""The time shares were issued."""
    name: NotRequired[str]
    r"""The name of the closing."""
    update_time: NotRequired[Nullable[datetime]]
    r"""The time the closing was updated."""


class PreIpoCompanyFundingRoundClosing(BaseModel):
    r"""Closing details of a Pre IPO Company Funding Round."""

    issue_price: OptionalNullable[IssuePrice] = UNSET
    r"""The issue price of the closing."""

    issue_time: OptionalNullable[datetime] = UNSET
    r"""The time shares were issued."""

    name: Optional[str] = None
    r"""The name of the closing."""

    update_time: OptionalNullable[datetime] = UNSET
    r"""The time the closing was updated."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["issue_price", "issue_time", "name", "update_time"]
        nullable_fields = ["issue_price", "issue_time", "update_time"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
