"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .pendinginvestoraction import PendingInvestorAction, PendingInvestorActionTypedDict
from ascend_sdk.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class RetrievePendingInvestorActionsResponseTypedDict(TypedDict):
    r"""Response to RetrievePendingInvestorActions request."""

    account_id: NotRequired[str]
    r"""The ID of the account specified in the request."""
    alternative_order_id: NotRequired[str]
    r"""The ID for the alternative investment order resource."""
    pending_investor_actions: NotRequired[List[PendingInvestorActionTypedDict]]
    r"""The object containing the pending action URIs that provide access to the document that is awaiting signature and the id of the responsible party."""


class RetrievePendingInvestorActionsResponse(BaseModel):
    r"""Response to RetrievePendingInvestorActions request."""

    account_id: Optional[str] = None
    r"""The ID of the account specified in the request."""

    alternative_order_id: Optional[str] = None
    r"""The ID for the alternative investment order resource."""

    pending_investor_actions: Optional[List[PendingInvestorAction]] = None
    r"""The object containing the pending action URIs that provide access to the document that is awaiting signature and the id of the responsible party."""
