"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .datecreate import DateCreate, DateCreateTypedDict
from ascend_sdk import utils
from ascend_sdk.types import BaseModel
from ascend_sdk.utils import validate_open_enum
from enum import Enum
from pydantic.functional_validators import PlainValidator
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class SearchOpenLotsRequestCreateIdentifierType(
    str, Enum, metaclass=utils.OpenEnumMeta
):
    r"""The type of the identifier provided in the identifier field. Please include an identifier_type if you are using an identifier. (-- api-linter: core::0140::abbreviations=disabled   aip.dev/not-precedent: Aligning with apex api standard for identifiers)"""

    IDENTIFIER_TYPE_UNSPECIFIED = "IDENTIFIER_TYPE_UNSPECIFIED"
    ASSET_ID = "ASSET_ID"
    SYMBOL = "SYMBOL"
    CUSIP = "CUSIP"


class SearchOpenLotsRequestCreateTypedDict(TypedDict):
    r"""Request message for retrieving open lots."""

    parent: str
    r"""The parent resource name, which is the account_id. Format: accounts/{account}"""
    identifier: NotRequired[str]
    r"""The security identifiers (see identifier_type) to filter open lots for one or more securities. If not specified, open lots meeting all other request criteria are returned regardless of security. (-- api-linter: core::0140::abbreviations=disabled   aip.dev/not-precedent: Aligning with apex api standard for identifiers)"""
    identifier_type: NotRequired[SearchOpenLotsRequestCreateIdentifierType]
    r"""The type of the identifier provided in the identifier field. Please include an identifier_type if you are using an identifier. (-- api-linter: core::0140::abbreviations=disabled   aip.dev/not-precedent: Aligning with apex api standard for identifiers)"""
    page_size: NotRequired[int]
    r"""Default page_size is 100, max page_size is 1000. Please note that the page_size must remain constant across all the requests when using a page_token to retrieve results of a given page."""
    page_token: NotRequired[str]
    r"""page_token to retrieve results of a given page."""
    start_trade_date: NotRequired[DateCreateTypedDict]
    r"""Represents a whole or partial calendar date, such as a birthday. The time of day and time zone are either specified elsewhere or are insignificant. The date is relative to the Gregorian Calendar. This can represent one of the following:

    * A full date, with non-zero year, month, and day values * A month and day value, with a zero year, such as an anniversary * A year on its own, with zero month and day values * A year and month value, with a zero day, such as a credit card expiration date

    Related types are [google.type.TimeOfDay][google.type.TimeOfDay] and `google.protobuf.Timestamp`.
    """


class SearchOpenLotsRequestCreate(BaseModel):
    r"""Request message for retrieving open lots."""

    parent: str
    r"""The parent resource name, which is the account_id. Format: accounts/{account}"""

    identifier: Optional[str] = None
    r"""The security identifiers (see identifier_type) to filter open lots for one or more securities. If not specified, open lots meeting all other request criteria are returned regardless of security. (-- api-linter: core::0140::abbreviations=disabled   aip.dev/not-precedent: Aligning with apex api standard for identifiers)"""

    identifier_type: Annotated[
        Optional[SearchOpenLotsRequestCreateIdentifierType],
        PlainValidator(validate_open_enum(False)),
    ] = None
    r"""The type of the identifier provided in the identifier field. Please include an identifier_type if you are using an identifier. (-- api-linter: core::0140::abbreviations=disabled   aip.dev/not-precedent: Aligning with apex api standard for identifiers)"""

    page_size: Optional[int] = None
    r"""Default page_size is 100, max page_size is 1000. Please note that the page_size must remain constant across all the requests when using a page_token to retrieve results of a given page."""

    page_token: Optional[str] = None
    r"""page_token to retrieve results of a given page."""

    start_trade_date: Optional[DateCreate] = None
    r"""Represents a whole or partial calendar date, such as a birthday. The time of day and time zone are either specified elsewhere or are insignificant. The date is relative to the Gregorian Calendar. This can represent one of the following:

    * A full date, with non-zero year, month, and day values * A month and day value, with a zero year, such as an anniversary * A year on its own, with zero month and day values * A year and month value, with a zero day, such as a credit card expiration date

    Related types are [google.type.TimeOfDay][google.type.TimeOfDay] and `google.protobuf.Timestamp`.
    """
