"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .openlot import OpenLot, OpenLotTypedDict
from ascend_sdk.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class SearchOpenLotsResponseTypedDict(TypedDict):
    r"""Response message containing a list of open lots. Please note that the response is sorted by acquisition date of an open lot adjusted for wash sales in ascending order, and also asset_id in ascending order."""

    next_page_token: NotRequired[str]
    r"""A token, which can be sent as page_token to retrieve the next page results. Please note that when the results size is less than the requested page_size in the last page, next_page_token will be empty. But when results size is equal to the requested page_size in the last page, the next_page_token won’t be empty; and user would have to make one more additional request to get the end of the results set."""
    open_lots: NotRequired[List[OpenLotTypedDict]]
    r"""The list of open lots."""


class SearchOpenLotsResponse(BaseModel):
    r"""Response message containing a list of open lots. Please note that the response is sorted by acquisition date of an open lot adjusted for wash sales in ascending order, and also asset_id in ascending order."""

    next_page_token: Optional[str] = None
    r"""A token, which can be sent as page_token to retrieve the next page results. Please note that when the results size is less than the requested page_size in the last page, next_page_token will be empty. But when results size is equal to the requested page_size in the last page, the next_page_token won’t be empty; and user would have to make one more additional request to get the end of the results set."""

    open_lots: Optional[List[OpenLot]] = None
    r"""The list of open lots."""
