"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .cashjournalschedule import CashJournalSchedule, CashJournalScheduleTypedDict
from ascend_sdk.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class SearchCashJournalSchedulesResponseTypedDict(TypedDict):
    r"""A paged response containing a list of Cash Journal transfer schedules"""

    cash_journal_schedules: NotRequired[List[CashJournalScheduleTypedDict]]
    r"""The list of transfer schedules"""
    next_page_token: NotRequired[str]
    r"""The next page token"""


class SearchCashJournalSchedulesResponse(BaseModel):
    r"""A paged response containing a list of Cash Journal transfer schedules"""

    cash_journal_schedules: Optional[List[CashJournalSchedule]] = None
    r"""The list of transfer schedules"""

    next_page_token: Optional[str] = None
    r"""The next page token"""
