"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from ascend_sdk import utils
from ascend_sdk.types import BaseModel
from ascend_sdk.utils import validate_open_enum
from enum import Enum
from pydantic.functional_validators import PlainValidator
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class OrderSettlementTarget(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""The desired target settlement state of the order. If unspecified, the order settlement state will default to \"FILLED\"."""

    ORDER_SETTLEMENT_TARGET_UNSPECIFIED = "ORDER_SETTLEMENT_TARGET_UNSPECIFIED"
    BOOKED = "BOOKED"
    FILLED = "FILLED"


class SettleAlternativeOrderRequestCreateTypedDict(TypedDict):
    r"""Request to settle an alternative order. Note: This is a simulation of settlement for testing purposes only, not to be used in production."""

    name: str
    r"""The name of the alternative order to settle.

    Format: accounts/{account}/alternativeOrders/{alternative_order}
    """
    order_settlement_target: NotRequired[OrderSettlementTarget]
    r"""The desired target settlement state of the order. If unspecified, the order settlement state will default to \"FILLED\"."""


class SettleAlternativeOrderRequestCreate(BaseModel):
    r"""Request to settle an alternative order. Note: This is a simulation of settlement for testing purposes only, not to be used in production."""

    name: str
    r"""The name of the alternative order to settle.

    Format: accounts/{account}/alternativeOrders/{alternative_order}
    """

    order_settlement_target: Annotated[
        Optional[OrderSettlementTarget], PlainValidator(validate_open_enum(False))
    ] = None
    r"""The desired target settlement state of the order. If unspecified, the order settlement state will default to \"FILLED\"."""
