"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from ascend_sdk.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class UpdateAccountGroupRequestUpdateTypedDict(TypedDict):
    r"""The request for updating account group an Account."""

    account_group_id: NotRequired[str]
    r"""An Account Group is a way of segmenting accounts within a Correspondent; It is up to the client to define what these groups are and AFS Operations is responsible for configuring them; If the client requests additional groups/codes, they can be added; Examples of Account Groups could hypothetically include HNW (High Net Worth), GOLD (Gold Status Customer), and NWC (Northwest Branch Customer)"""
    name: NotRequired[str]
    r"""The name of the account to update."""


class UpdateAccountGroupRequestUpdate(BaseModel):
    r"""The request for updating account group an Account."""

    account_group_id: Optional[str] = None
    r"""An Account Group is a way of segmenting accounts within a Correspondent; It is up to the client to define what these groups are and AFS Operations is responsible for configuring them; If the client requests additional groups/codes, they can be added; Examples of Account Groups could hypothetically include HNW (High Net Worth), GOLD (Gold Status Customer), and NWC (Northwest Branch Customer)"""

    name: Optional[str] = None
    r"""The name of the account to update."""
